* Generated by open-abap-gui converter 0.1.0.
* Source object: ZEXAMPLE_DDIC
* Source file: input/zexample_ddic.prog.abap
* Source SHA-256: d736ee875fc6268552b715df73edd84d68eebe46136947c56637235941206b71
* Target class: ZCL_EXAMPLE_DDIC
* Manifest schema: 1
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_example_ddic DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_program_v1.
    INTERFACES zif_gg_list_processing_v1.

  PRIVATE SECTION.
    DATA gv_date TYPE zexample_date.
    DATA mv_p_amount TYPE zexample_amount.
    DATA mv_p_carr TYPE zexample_carrier.
    DATA mv_p_count TYPE zexample_count.
    DATA mv_p_date TYPE zexample_date.
    DATA mv_s_date LIKE RANGE OF gv_date.

ENDCLASS.

CLASS zcl_example_ddic IMPLEMENTATION.

  METHOD zif_gg_program_v1~get_program.
    rs_program = VALUE #( program = 'ZEXAMPLE_DDIC' description = 'Converted executable report' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    ro_list_processing = me.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    io_builder->add_parameter( VALUE #( name = 'P_COUNT' text = 'P_COUNT' data_type = VALUE #( rollname = 'ZEXAMPLE_COUNT' typ = 'I' ) default = CONV string( 3 ) ) ).
    io_builder->add_parameter( VALUE #( name = 'P_AMOUNT' text = 'P_AMOUNT' data_type = VALUE #( rollname = 'ZEXAMPLE_AMOUNT' typ = 'P' length = 7 decimals = 2 ) ) ).
    io_builder->add_parameter( VALUE #( name = 'P_DATE' text = 'P_DATE' data_type = VALUE #( rollname = 'ZEXAMPLE_DATE' typ = 'D' length = 8 ) ) ).
    io_builder->add_parameter( VALUE #( name = 'P_CARR' text = 'P_CARR' data_type = VALUE #( rollname = 'ZEXAMPLE_CARRIER' typ = 'C' length = 3 ) ) ).
    io_builder->add_select_option( VALUE #( name = 'S_DATE' text = 'S_DATE' data_type = VALUE #( rollname = 'ZEXAMPLE_DATE' typ = 'D' length = 8 ) ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    mv_p_amount = ct_values[ name = 'P_AMOUNT' ]-value.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    mv_p_count = ct_values[ name = 'P_COUNT' ]-value.
    mv_p_date = ct_values[ name = 'P_DATE' ]-value.
    mv_s_date = CORRESPONDING #( ct_values[ name = 'S_DATE' ]-ranges ).
    IF ct_values[ name = 'P_AMOUNT' ]-value <> mv_p_amount.
      ct_values[ name = 'P_AMOUNT' ]-value = |{ mv_p_amount }|.
    ENDIF.
    IF ct_values[ name = 'P_CARR' ]-value <> mv_p_carr.
      ct_values[ name = 'P_CARR' ]-value = |{ mv_p_carr }|.
    ENDIF.
    IF ct_values[ name = 'P_COUNT' ]-value <> mv_p_count.
      ct_values[ name = 'P_COUNT' ]-value = |{ mv_p_count }|.
    ENDIF.
    IF ct_values[ name = 'P_DATE' ]-value <> mv_p_date.
      ct_values[ name = 'P_DATE' ]-value = |{ mv_p_date }|.
    ENDIF.
    DATA(lt_ggconv_s_date) = mv_s_date.
    lt_ggconv_s_date = CORRESPONDING #( ct_values[ name = 'S_DATE' ]-ranges ).
    IF lt_ggconv_s_date <> mv_s_date.
      ct_values[ name = 'S_DATE' ]-ranges = CORRESPONDING #( mv_s_date ).
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    mv_p_amount = ct_values[ name = 'P_AMOUNT' ]-value.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    mv_p_count = ct_values[ name = 'P_COUNT' ]-value.
    mv_p_date = ct_values[ name = 'P_DATE' ]-value.
    mv_s_date = CORRESPONDING #( ct_values[ name = 'S_DATE' ]-ranges ).
    IF ct_values[ name = 'P_AMOUNT' ]-value <> mv_p_amount.
      ct_values[ name = 'P_AMOUNT' ]-value = |{ mv_p_amount }|.
    ENDIF.
    IF ct_values[ name = 'P_CARR' ]-value <> mv_p_carr.
      ct_values[ name = 'P_CARR' ]-value = |{ mv_p_carr }|.
    ENDIF.
    IF ct_values[ name = 'P_COUNT' ]-value <> mv_p_count.
      ct_values[ name = 'P_COUNT' ]-value = |{ mv_p_count }|.
    ENDIF.
    IF ct_values[ name = 'P_DATE' ]-value <> mv_p_date.
      ct_values[ name = 'P_DATE' ]-value = |{ mv_p_date }|.
    ENDIF.
    DATA(lt_ggconv_s_date) = mv_s_date.
    lt_ggconv_s_date = CORRESPONDING #( ct_values[ name = 'S_DATE' ]-ranges ).
    IF lt_ggconv_s_date <> mv_s_date.
      ct_values[ name = 'S_DATE' ]-ranges = CORRESPONDING #( mv_s_date ).
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    mv_p_amount = ct_values[ name = 'P_AMOUNT' ]-value.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    mv_p_count = ct_values[ name = 'P_COUNT' ]-value.
    mv_p_date = ct_values[ name = 'P_DATE' ]-value.
    mv_s_date = CORRESPONDING #( ct_values[ name = 'S_DATE' ]-ranges ).
    IF ct_values[ name = 'P_AMOUNT' ]-value <> mv_p_amount.
      ct_values[ name = 'P_AMOUNT' ]-value = |{ mv_p_amount }|.
    ENDIF.
    IF ct_values[ name = 'P_CARR' ]-value <> mv_p_carr.
      ct_values[ name = 'P_CARR' ]-value = |{ mv_p_carr }|.
    ENDIF.
    IF ct_values[ name = 'P_COUNT' ]-value <> mv_p_count.
      ct_values[ name = 'P_COUNT' ]-value = |{ mv_p_count }|.
    ENDIF.
    IF ct_values[ name = 'P_DATE' ]-value <> mv_p_date.
      ct_values[ name = 'P_DATE' ]-value = |{ mv_p_date }|.
    ENDIF.
    DATA(lt_ggconv_s_date) = mv_s_date.
    lt_ggconv_s_date = CORRESPONDING #( ct_values[ name = 'S_DATE' ]-ranges ).
    IF lt_ggconv_s_date <> mv_s_date.
      ct_values[ name = 'S_DATE' ]-ranges = CORRESPONDING #( mv_s_date ).
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    mv_p_amount = ct_values[ name = 'P_AMOUNT' ]-value.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    mv_p_count = ct_values[ name = 'P_COUNT' ]-value.
    mv_p_date = ct_values[ name = 'P_DATE' ]-value.
    mv_s_date = CORRESPONDING #( ct_values[ name = 'S_DATE' ]-ranges ).
    IF ct_values[ name = 'P_AMOUNT' ]-value <> mv_p_amount.
      ct_values[ name = 'P_AMOUNT' ]-value = |{ mv_p_amount }|.
    ENDIF.
    IF ct_values[ name = 'P_CARR' ]-value <> mv_p_carr.
      ct_values[ name = 'P_CARR' ]-value = |{ mv_p_carr }|.
    ENDIF.
    IF ct_values[ name = 'P_COUNT' ]-value <> mv_p_count.
      ct_values[ name = 'P_COUNT' ]-value = |{ mv_p_count }|.
    ENDIF.
    IF ct_values[ name = 'P_DATE' ]-value <> mv_p_date.
      ct_values[ name = 'P_DATE' ]-value = |{ mv_p_date }|.
    ENDIF.
    DATA(lt_ggconv_s_date) = mv_s_date.
    lt_ggconv_s_date = CORRESPONDING #( ct_values[ name = 'S_DATE' ]-ranges ).
    IF lt_ggconv_s_date <> mv_s_date.
      ct_values[ name = 'S_DATE' ]-ranges = CORRESPONDING #( mv_s_date ).
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    mv_p_amount = ct_values[ name = 'P_AMOUNT' ]-value.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    mv_p_count = ct_values[ name = 'P_COUNT' ]-value.
    mv_p_date = ct_values[ name = 'P_DATE' ]-value.
    mv_s_date = CORRESPONDING #( ct_values[ name = 'S_DATE' ]-ranges ).
    IF ct_values[ name = 'P_AMOUNT' ]-value <> mv_p_amount.
      ct_values[ name = 'P_AMOUNT' ]-value = |{ mv_p_amount }|.
    ENDIF.
    IF ct_values[ name = 'P_CARR' ]-value <> mv_p_carr.
      ct_values[ name = 'P_CARR' ]-value = |{ mv_p_carr }|.
    ENDIF.
    IF ct_values[ name = 'P_COUNT' ]-value <> mv_p_count.
      ct_values[ name = 'P_COUNT' ]-value = |{ mv_p_count }|.
    ENDIF.
    IF ct_values[ name = 'P_DATE' ]-value <> mv_p_date.
      ct_values[ name = 'P_DATE' ]-value = |{ mv_p_date }|.
    ENDIF.
    DATA(lt_ggconv_s_date) = mv_s_date.
    lt_ggconv_s_date = CORRESPONDING #( ct_values[ name = 'S_DATE' ]-ranges ).
    IF lt_ggconv_s_date <> mv_s_date.
      ct_values[ name = 'S_DATE' ]-ranges = CORRESPONDING #( mv_s_date ).
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    mv_p_amount = ct_values[ name = 'P_AMOUNT' ]-value.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    mv_p_count = ct_values[ name = 'P_COUNT' ]-value.
    mv_p_date = ct_values[ name = 'P_DATE' ]-value.
    mv_s_date = CORRESPONDING #( ct_values[ name = 'S_DATE' ]-ranges ).
    IF ct_values[ name = 'P_AMOUNT' ]-value <> mv_p_amount.
      ct_values[ name = 'P_AMOUNT' ]-value = |{ mv_p_amount }|.
    ENDIF.
    IF ct_values[ name = 'P_CARR' ]-value <> mv_p_carr.
      ct_values[ name = 'P_CARR' ]-value = |{ mv_p_carr }|.
    ENDIF.
    IF ct_values[ name = 'P_COUNT' ]-value <> mv_p_count.
      ct_values[ name = 'P_COUNT' ]-value = |{ mv_p_count }|.
    ENDIF.
    IF ct_values[ name = 'P_DATE' ]-value <> mv_p_date.
      ct_values[ name = 'P_DATE' ]-value = |{ mv_p_date }|.
    ENDIF.
    DATA(lt_ggconv_s_date) = mv_s_date.
    lt_ggconv_s_date = CORRESPONDING #( ct_values[ name = 'S_DATE' ]-ranges ).
    IF lt_ggconv_s_date <> mv_s_date.
      ct_values[ name = 'S_DATE' ]-ranges = CORRESPONDING #( mv_s_date ).
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    mv_p_amount = ct_values[ name = 'P_AMOUNT' ]-value.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    mv_p_count = ct_values[ name = 'P_COUNT' ]-value.
    mv_p_date = ct_values[ name = 'P_DATE' ]-value.
    mv_s_date = CORRESPONDING #( ct_values[ name = 'S_DATE' ]-ranges ).
    IF ct_values[ name = 'P_AMOUNT' ]-value <> mv_p_amount.
      ct_values[ name = 'P_AMOUNT' ]-value = |{ mv_p_amount }|.
    ENDIF.
    IF ct_values[ name = 'P_CARR' ]-value <> mv_p_carr.
      ct_values[ name = 'P_CARR' ]-value = |{ mv_p_carr }|.
    ENDIF.
    IF ct_values[ name = 'P_COUNT' ]-value <> mv_p_count.
      ct_values[ name = 'P_COUNT' ]-value = |{ mv_p_count }|.
    ENDIF.
    IF ct_values[ name = 'P_DATE' ]-value <> mv_p_date.
      ct_values[ name = 'P_DATE' ]-value = |{ mv_p_date }|.
    ENDIF.
    DATA(lt_ggconv_s_date) = mv_s_date.
    lt_ggconv_s_date = CORRESPONDING #( ct_values[ name = 'S_DATE' ]-ranges ).
    IF lt_ggconv_s_date <> mv_s_date.
      ct_values[ name = 'S_DATE' ]-ranges = CORRESPONDING #( mv_s_date ).
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    mv_p_amount = it_values[ name = 'P_AMOUNT' ]-value.
    mv_p_carr = it_values[ name = 'P_CARR' ]-value.
    mv_p_count = it_values[ name = 'P_COUNT' ]-value.
    mv_p_date = it_values[ name = 'P_DATE' ]-value.
    mv_s_date = CORRESPONDING #( it_values[ name = 'S_DATE' ]-ranges ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'ZCL_EXAMPLE_DDIC' ).
    mv_p_amount = it_values[ name = 'P_AMOUNT' ]-value.
    mv_p_carr = it_values[ name = 'P_CARR' ]-value.
    mv_p_count = it_values[ name = 'P_COUNT' ]-value.
    mv_p_date = it_values[ name = 'P_DATE' ]-value.
    mv_s_date = CORRESPONDING #( it_values[ name = 'S_DATE' ]-ranges ).
* Parameters typed with data elements: abaplint resolves each to its
* built-in type through the dictionary objects next to the report, so an
* integer data element renders as a number field and a date one as a date.
    io_session->get_list( )->set_title( 'ZCL_EXAMPLE_DDIC' ).
    DATA(lo_writer) = io_session->get_list( )->get_writer( ).
    mv_p_amount = it_values[ name = 'P_AMOUNT' ]-value.
    mv_p_carr = it_values[ name = 'P_CARR' ]-value.
    mv_p_count = it_values[ name = 'P_COUNT' ]-value.
    mv_p_date = it_values[ name = 'P_DATE' ]-value.
    mv_s_date = CORRESPONDING #( it_values[ name = 'S_DATE' ]-ranges ).
    lo_writer->write_field( VALUE #( text = 'Runs:' placement = VALUE #( new_line = abap_true ) ) ).
    lo_writer->write_field( VALUE #( text = |{ mv_p_count }| ) ).
    lo_writer->write_field( VALUE #( text = 'Amount:' placement = VALUE #( new_line = abap_true ) ) ).
    lo_writer->write_field( VALUE #( text = |{ mv_p_amount }| ) ).
    lo_writer->write_field( VALUE #( text = 'Date:' placement = VALUE #( new_line = abap_true ) ) ).
    lo_writer->write_field( VALUE #( text = |{ mv_p_date }| ) ).
    lo_writer->write_field( VALUE #( text = 'Carrier:' placement = VALUE #( new_line = abap_true ) ) ).
    lo_writer->write_field( VALUE #( text = |{ mv_p_carr }| ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    mv_p_amount = it_values[ name = 'P_AMOUNT' ]-value.
    mv_p_carr = it_values[ name = 'P_CARR' ]-value.
    mv_p_count = it_values[ name = 'P_COUNT' ]-value.
    mv_p_date = it_values[ name = 'P_DATE' ]-value.
    mv_s_date = CORRESPONDING #( it_values[ name = 'S_DATE' ]-ranges ).
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~get_settings.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~end_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page_during_line_sel.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_line_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_user_command.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_pf.
    RETURN.
  ENDMETHOD.

ENDCLASS.
