REPORT zexample_texts.

SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME TITLE TEXT-t01.
PARAMETERS: p_user TYPE c LENGTH 12,
            p_days TYPE i DEFAULT 7.
SELECTION-SCREEN COMMENT /1(40) TEXT-c01.
SELECTION-SCREEN END OF BLOCK b1.

START-OF-SELECTION.
  WRITE: / TEXT-001, p_user.
  WRITE: / TEXT-002, p_days.
