* Generated by open-abap-gui converter 0.1.0.
* Source object: ZEXAMPLE_MEMORY
* Source file: input/zexample_memory.prog.abap
* Source SHA-256: a0f79546313ce8225c40d6645fd0f21face0949fdd052500dc882cfb1fc99853
* Target class: ZCL_EXAMPLE_MEMORY
* Manifest schema: 1
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_example_memory DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_transaction_v1.
    INTERFACES zif_gg_list_processing_v1.

  PRIVATE SECTION.
    DATA gv_counter TYPE i.
    DATA gv_text TYPE string.

ENDCLASS.

CLASS zcl_example_memory IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZEXAMPLE_MEMORY' description = 'Converted executable report' program = 'ZEXAMPLE_MEMORY' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    ro_list_processing = me.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'ZCL_EXAMPLE_MEMORY' ).
    DATA(lo_writer) = io_session->get_list( )->get_writer( ).
    gv_counter = 42.
    gv_text = `stored`.
    io_session->export_memory( iv_id = 'ZEXAMPLE' iv_name = 'GV_COUNTER' iv_value = gv_counter ).
    io_session->export_memory( iv_id = 'ZEXAMPLE' iv_name = 'GV_TEXT' iv_value = gv_text ).
    CLEAR gv_counter.
    CLEAR gv_text.
    io_session->import_memory( EXPORTING iv_id = 'ZEXAMPLE' iv_name = 'GV_COUNTER' CHANGING cv_value = gv_counter ).
    io_session->import_memory( EXPORTING iv_id = 'ZEXAMPLE' iv_name = 'GV_TEXT' CHANGING cv_value = gv_text ).
    lo_writer->write_field( VALUE #( text = |{ gv_counter }| placement = VALUE #( new_line = abap_true ) ) ).
    lo_writer->write_field( VALUE #( text = |{ gv_text }| ) ).
    io_session->free_memory( iv_id = 'ZEXAMPLE' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~get_settings.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~end_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page_during_line_sel.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_line_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_user_command.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_pf.
    RETURN.
  ENDMETHOD.

ENDCLASS.
