REPORT zgg_ex_71.

PARAMETERS p_car TYPE c LENGTH 2 AS LISTBOX VISIBLE LENGTH 10 DEFAULT 'AA'.
PARAMETERS p_con TYPE c LENGTH 5 AS LISTBOX VISIBLE LENGTH 10.
PARAMETERS p_req TYPE c LENGTH 20 OBLIGATORY.

AT SELECTION-SCREEN OUTPUT.
  IF p_car = 'LH'.
    WRITE / 'Connection values are supplied by the screen callback.'.
  ENDIF.

START-OF-SELECTION.
  WRITE p_car.
  WRITE / p_con.
