REPORT zgg_ex_067.

PARAMETERS p_date TYPE d DEFAULT '20260830'.
PARAMETERS p_time TYPE t DEFAULT '123456'.
PARAMETERS p_int TYPE i DEFAULT 42.
PARAMETERS p_dec TYPE p DECIMALS 2 DEFAULT '123.45'.
PARAMETERS p_char TYPE c LENGTH 12 OBLIGATORY.

START-OF-SELECTION.
  WRITE p_date.
  WRITE / p_time.
  WRITE / p_int.
  WRITE / p_dec.
  WRITE / p_char.
