REPORT zgg_ex_055.

TYPES abaplist TYPE c LENGTH 1.
DATA gt_list TYPE STANDARD TABLE OF abaplist WITH DEFAULT KEY.

START-OF-SELECTION.
  SUBMIT zgg_ex_001 EXPORTING LIST TO MEMORY AND RETURN.
  CALL FUNCTION 'LIST_FROM_MEMORY'
    TABLES
      listobject = gt_list.
