REPORT zgg_ex_23.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(10) TEXT-c01.
PARAMETERS p_low TYPE i.
SELECTION-SCREEN POSITION 40.
PARAMETERS p_high TYPE i.
SELECTION-SCREEN END OF LINE.
