REPORT zgg_ex_26.

SELECTION-SCREEN BEGIN OF TABBED BLOCK tb FOR 10 LINES.
SELECTION-SCREEN TAB (20) tab1 USER-COMMAND ut1 DEFAULT SCREEN 100.
SELECTION-SCREEN TAB (20) tab2 USER-COMMAND ut2 DEFAULT SCREEN 200.
SELECTION-SCREEN END OF BLOCK tb.
