REPORT zgg_ex_51.

SELECTION-SCREEN BEGIN OF SCREEN 500 AS WINDOW.
PARAMETERS p_b TYPE c LENGTH 1.
SELECTION-SCREEN END OF SCREEN 500.

START-OF-SELECTION.
  CALL SELECTION-SCREEN 500 STARTING AT 10 5.
  IF sy-subrc = 0.
    WRITE p_b.
  ENDIF.
