REPORT zgg_ex_034.

PARAMETERS p_all RADIOBUTTON GROUP g1 DEFAULT 'X'.
PARAMETERS p_one RADIOBUTTON GROUP g1.
PARAMETERS p_key TYPE c LENGTH 3.

AT SELECTION-SCREEN ON RADIOBUTTON GROUP g1.
  IF p_one = abap_true AND p_key IS INITIAL.
    MESSAGE 'key required for single mode' TYPE 'E'.
  ENDIF.
