REPORT zgg_ex_099.
SELECTION-SCREEN BEGIN OF SCREEN 100.
PARAMETERS p_input TYPE c LENGTH 20.
SELECTION-SCREEN PUSHBUTTON /1(10) TEXT-001 USER-COMMAND go.
SELECTION-SCREEN END OF SCREEN 100.
START-OF-SELECTION.
  WRITE / p_input.
