REPORT zgg_ex_44.

START-OF-SELECTION.
  SET PF-STATUS 'LIST' EXCLUDING 'DEL'.
  WRITE 'body'.

AT USER-COMMAND.
  CASE sy-ucomm.
    WHEN 'REFR'.
      WRITE / 'refreshed'.
    WHEN OTHERS.
      RETURN.
  ENDCASE.
