REPORT zgg_ex_87.
START-OF-SELECTION.
  FORMAT COLOR COL_HEADING INTENSIFIED ON.
  WRITE 'heading'.
  FORMAT COLOR COL_POSITIVE HOTSPOT ON.
  WRITE ' positive'.
  FORMAT COLOR COL_NEGATIVE INVERSE ON.
  WRITE ' negative'.
