REPORT zgg_ex_69.

PARAMETERS p_enable AS CHECKBOX DEFAULT 'X'.
PARAMETERS p_grp_a TYPE c LENGTH 20.
PARAMETERS p_grp_b TYPE c LENGTH 20.
PARAMETERS p_req TYPE c LENGTH 20 OBLIGATORY.

START-OF-SELECTION.
  WRITE p_grp_a.
  WRITE / p_grp_b.
