* Generated by open-abap-gui converter 0.1.0.
* Source object: ZEXAMPLE_MAIN
* Source file: input/zexample_main.prog.abap
* Source SHA-256: b53402a3b3d5cf57600320ed014dfde4e38ea07f461ff77ae46bbcbbdf4f0e73
* Target class: ZCL_EXAMPLE_MAIN
* Manifest schema: 1
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_example_main DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_program_v1.
    INTERFACES zif_gg_list_processing_v1.

  PRIVATE SECTION.
    CONSTANTS gc_prefix TYPE string VALUE `Built in an include`.
    DATA gv_message TYPE string.
    METHODS form_build_message
      IMPORTING
        io_session TYPE REF TO zif_gg_session_v1.

ENDCLASS.

CLASS zcl_example_main IMPLEMENTATION.

  METHOD zif_gg_program_v1~get_program.
    rs_program = VALUE #( program = 'ZEXAMPLE_MAIN' description = 'Converted executable report' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    ro_list_processing = me.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'ZCL_EXAMPLE_MAIN' ).
* Global data for ZEXAMPLE_MAIN.
* Routines for ZEXAMPLE_MAIN.
    io_session->get_list( )->set_title( 'ZCL_EXAMPLE_MAIN' ).
    DATA(lo_writer) = io_session->get_list( )->get_writer( ).
    form_build_message( io_session = io_session ).
    lo_writer->write_field( VALUE #( text = |{ gv_message }| placement = VALUE #( new_line = abap_true ) ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~get_settings.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~end_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page_during_line_sel.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_line_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_user_command.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_pf.
    RETURN.
  ENDMETHOD.

  METHOD form_build_message.
    gv_message = |{ gc_prefix }: { io_session->get_context( )-program-program }|.
  ENDMETHOD.

ENDCLASS.
