* Generated by open-abap-gui converter 0.1.0.
* Source object: ZEXAMPLE_LSTATIC
* Source file: input/zexample_lstatic.prog.abap
* Source SHA-256: d4e1ce32345f04ac1772c2cdfe2d02956eabcdee1a9e291bd1eddbacb1717ec3
* Target class: ZCL_EXAMPLE_LSTATIC_H1
* Manifest schema: 1
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_example_lstatic_h1 DEFINITION PUBLIC CREATE PUBLIC.

  PUBLIC SECTION.
    METHODS constructor IMPORTING io_owner TYPE REF TO zcl_example_lstatic io_session TYPE REF TO zif_gg_session_v1.
    DATA mo_owner TYPE REF TO zcl_example_lstatic.
    DATA mo_session TYPE REF TO zif_gg_session_v1.
  CLASS-METHODS greet IMPORTING iv_name TYPE string io_owner TYPE REF TO zcl_example_lstatic io_session TYPE REF TO zif_gg_session_v1 RETURNING VALUE(rv_text) TYPE string.
  CLASS-METHODS remember IMPORTING iv_text TYPE string io_owner TYPE REF TO zcl_example_lstatic io_session TYPE REF TO zif_gg_session_v1.

ENDCLASS.

CLASS zcl_example_lstatic_h1 IMPLEMENTATION.
  METHOD constructor.
    mo_owner = io_owner.
    mo_session = io_session.
  ENDMETHOD.

  METHOD greet.
    rv_text = |Hello { iv_name }|.
  ENDMETHOD.

  METHOD remember.
    io_owner->gv_greeting = iv_text.
  ENDMETHOD.
ENDCLASS.
