* Generated by open-abap-gui converter 0.1.0.
* Source object: ZEXAMPLE_FORMS
* Source file: input/zexample_forms.prog.abap
* Source SHA-256: e36a1cb25cdb81da49c2d215df614d18c1d962a9ebd5eba844f4e05a8f4df709
* Target class: ZCL_EXAMPLE_FORMS
* Manifest schema: 1
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_example_forms DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_program_v1.
    INTERFACES zif_gg_list_processing_v1.

  PRIVATE SECTION.
    TYPES: BEGIN OF ty_item, name TYPE string, qty TYPE i, END OF ty_item.
    TYPES ty_items TYPE STANDARD TABLE OF ty_item WITH EMPTY KEY.
    DATA gt_items TYPE ty_items.
    DATA gv_total TYPE i.
    METHODS form_fill_items
      IMPORTING
        io_session TYPE REF TO zif_gg_session_v1.
    METHODS form_sum_items
      IMPORTING
        io_session TYPE REF TO zif_gg_session_v1
        it_items   TYPE ty_items
      CHANGING
        cv_total   TYPE i.
    METHODS form_print_total
      IMPORTING
        io_session TYPE REF TO zif_gg_session_v1
        iv_total   TYPE i.

ENDCLASS.

CLASS zcl_example_forms IMPLEMENTATION.

  METHOD zif_gg_program_v1~get_program.
    rs_program = VALUE #( program = 'ZEXAMPLE_FORMS' description = 'Converted executable report' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    ro_list_processing = me.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'ZCL_EXAMPLE_FORMS' ).
    form_fill_items( io_session = io_session ).
    form_sum_items(
      EXPORTING
        io_session = io_session
        it_items   = gt_items
      CHANGING
        cv_total   = gv_total ).
    form_print_total(
      EXPORTING
        io_session = io_session
        iv_total   = gv_total ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~get_settings.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~end_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page_during_line_sel.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_line_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_user_command.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_pf.
    RETURN.
  ENDMETHOD.

  METHOD form_fill_items.
    APPEND VALUE #( name = `Apple` qty = 3 ) TO gt_items.
    APPEND VALUE #( name = `Pear` qty = 4 ) TO gt_items.
  ENDMETHOD.

  METHOD form_sum_items.
    DATA ls_item TYPE ty_item.
    CLEAR cv_total.
    LOOP AT it_items INTO ls_item.
      cv_total = cv_total + ls_item-qty.
    ENDLOOP.
  ENDMETHOD.

  METHOD form_print_total.
    DATA(lo_writer) = io_session->get_list( )->get_writer( ).
    lo_writer->write_field( VALUE #( text = 'Total quantity:' placement = VALUE #( new_line = abap_true ) ) ).
    lo_writer->write_field( VALUE #( text = |{ iv_total }| ) ).
  ENDMETHOD.

ENDCLASS.
