* Generated by open-abap-gui converter 0.1.0.
* Source object: ZGG_EX_116
* Source file: examples/zgg_ex_116.prog.abap
* Source SHA-256: 273adf1d140f729dcec4480d44beb1ef68d8474d7385da070e23104f68febbc0
* Target class: ZCL_GG_EX_116
* Manifest schema: 1
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_116 DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_screen_provider_v1.
    INTERFACES zif_gg_transaction_v1.
    INTERFACES zif_gg_list_processing_v1.
    INTERFACES zif_gg_resumable_v1.

  PRIVATE SECTION.
    TYPES: BEGIN OF ty_flight, carrid TYPE c LENGTH 3, connid TYPE n LENGTH 4, cityfrom TYPE c LENGTH 20, cityto TYPE c LENGTH 20, END OF ty_flight.
    TYPES: BEGIN OF ty_carrier, carrid TYPE c LENGTH 3, carrname TYPE c LENGTH 20, END OF ty_carrier.
    DATA gv_ok_code TYPE sy-ucomm.
    DATA gv_carrid TYPE c LENGTH 3 VALUE 'LH'.
    DATA gt_carriers TYPE STANDARD TABLE OF ty_carrier WITH DEFAULT KEY.
    DATA gt_flights TYPE STANDARD TABLE OF ty_flight WITH DEFAULT KEY.
    DATA gt_shown TYPE STANDARD TABLE OF ty_flight WITH DEFAULT KEY.
    DATA gs_flight TYPE ty_flight.
    DATA tc_flights TYPE zif_gg_dynpro_types_v1=>ty_table_runtime.
    METHODS output_modules
      IMPORTING
        is_context TYPE zif_gg_dynpro_types_v1=>ty_module_context
        io_session TYPE REF TO zif_gg_session_v1
      CHANGING
        ct_values  TYPE zif_gg_dynpro_types_v1=>ty_values
        ct_states  TYPE zif_gg_dynpro_types_v1=>ty_states.
    METHODS input_modules
      IMPORTING
        is_context TYPE zif_gg_dynpro_types_v1=>ty_module_context
        io_session TYPE REF TO zif_gg_session_v1
      CHANGING
        ct_values  TYPE zif_gg_dynpro_types_v1=>ty_values.
    METHODS table_values_in
      IMPORTING
        it_values TYPE zif_gg_dynpro_types_v1=>ty_values.
    METHODS table_values_out
      CHANGING
        ct_values TYPE zif_gg_dynpro_types_v1=>ty_values.

ENDCLASS.

CLASS zcl_gg_ex_116 IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZGG_EX_116' description = 'Two-screen flight editor' program = 'ZGG_EX_116' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'Two-screen flight editor' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    ro_list_processing = me.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'Two-screen flight editor' ).
* CONTROLS declaration represented by dynpro metadata.
    io_session->get_list( )->set_title( 'Two-screen flight editor' ).
    gt_carriers = VALUE #( ( carrid = 'LH' carrname = 'Lufthansa' ) ( carrid = 'UA' carrname = 'United Airlines' ) ).
    gt_flights = VALUE #( ( carrid = 'LH' connid = '0400' cityfrom = 'Frankfurt' cityto = 'New York' ) ( carrid = 'LH' connid = '0402' cityfrom = 'Frankfurt' cityto = 'New York' ) ( carrid = 'UA' connid = '0941' cityfrom = 'Frankfurt' cityto = 'San Francisco' ) ).
    io_session->get_dialog( )->call_screen(
      is_call         = VALUE #( screen = '0100' )
      is_continuation = VALUE #( id = 'AFTER_0100' ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~get_initial_screen.
    rv_screen = '0100'.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~build_screens.
    io_builder->begin_screen( VALUE #( number = '0100' title = 'Airline' next_screen = '0100' ok_code = 'GV_OK_CODE' width = 800 height = 644 ) ).
    io_builder->add_text( VALUE #( control = VALUE #( name = 'LBL_CARRID' position = VALUE #( row = 10 column = 5 width = 100 height = 26 ) ) text = 'Airline' ) ).
    io_builder->add_input_field( VALUE #( control = VALUE #( name = 'GV_CARRID' position = VALUE #( row = 10 column = 115 width = 30 height = 26 ) ) data_type = VALUE #( typ = 'C' length = 3 ) value_help = abap_true ) ).
    io_builder->end_screen( ).
    io_builder->begin_screen( VALUE #( number = '0200' title = 'Flights' next_screen = '0200' ok_code = 'GV_OK_CODE' width = 800 height = 644 ) ).
    io_builder->begin_table_control( VALUE #( control = VALUE #( name = 'TC_FLIGHTS' position = VALUE #( row = 10 column = 5 width = 600 height = 156 ) ) visible_rows = 5 selection_mode = 'NONE' with_hscroll = abap_true with_vscroll = abap_true ) ).
    io_builder->add_table_column( VALUE #( table_control = 'TC_FLIGHTS' name = 'CONNID' state_name = 'GS_FLIGHT-CONNID' title = 'Flight' data_type = VALUE #( typ = 'C' length = 4 ) width = 60 input = abap_false required = abap_false checkbox = abap_false ) ).
    io_builder->add_table_column( VALUE #( table_control = 'TC_FLIGHTS' name = 'CITYFROM' state_name = 'GS_FLIGHT-CITYFROM' title = 'From' data_type = VALUE #( typ = 'C' length = 20 ) width = 200 input = abap_true required = abap_false checkbox = abap_false ) ).
    io_builder->add_table_column( VALUE #( table_control = 'TC_FLIGHTS' name = 'CITYTO' state_name = 'GS_FLIGHT-CITYTO' title = 'To' data_type = VALUE #( typ = 'C' length = 20 ) width = 200 input = abap_true required = abap_false checkbox = abap_false ) ).
    io_builder->end_table_control( ).
    io_builder->end_screen( ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~build_flow_logic.
    io_builder->begin_screen( '0100' ).
    io_builder->begin_pbo( ).
    io_builder->add_module( VALUE #( name = 'STATUS_0100' ) ).
    io_builder->end_processing( ).
    io_builder->begin_pai( ).
    io_builder->add_module( VALUE #( name = 'EXIT_0100' on_input = abap_true at_exit_command = abap_true ) ).
    io_builder->add_field( 'GV_CARRID' ).
    io_builder->add_module( VALUE #( name = 'CHECK_CARRID' on_input = abap_true ) ).
    io_builder->add_module( VALUE #( name = 'USER_COMMAND_0100' on_input = abap_true ) ).
    io_builder->end_processing( ).
    io_builder->begin_value_request( '' ).
    io_builder->add_module( VALUE #( name = 'F4_CARRID' ) ).
    io_builder->end_processing( ).
    io_builder->end_screen( ).
    io_builder->begin_screen( '0200' ).
    io_builder->begin_pbo( ).
    io_builder->add_module( VALUE #( name = 'STATUS_0200' ) ).
    io_builder->begin_table_loop( VALUE #( table_control = 'TC_FLIGHTS' ) ).
    io_builder->end_table_loop( ).
    io_builder->end_processing( ).
    io_builder->begin_pai( ).
    io_builder->add_module( VALUE #( name = 'EXIT_0200' on_input = abap_true at_exit_command = abap_true ) ).
    io_builder->begin_table_loop( VALUE #( table_control = 'TC_FLIGHTS' ) ).
    io_builder->add_module( VALUE #( name = 'MODIFY_FLIGHT' on_input = abap_true ) ).
    io_builder->end_table_loop( ).
    io_builder->add_module( VALUE #( name = 'USER_COMMAND_0200' on_input = abap_true ) ).
    io_builder->end_processing( ).
    io_builder->end_screen( ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~initialization.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_CARRID' ] ).
      ct_values[ name = 'GV_CARRID' ]-value = CONV string( gv_carrid ).
    ELSE.
      INSERT VALUE #( name = 'GV_CARRID' value = CONV string( gv_carrid ) ) INTO TABLE ct_values.
    ENDIF.
    table_values_out( CHANGING ct_values = ct_values ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_output_module.
    DATA lx_unwind TYPE REF TO zcx_gg_control_flow.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      gv_ok_code = CONV #( ct_values[ name = 'GV_OK_CODE' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_CARRID' ] ).
      gv_carrid = CONV #( ct_values[ name = 'GV_CARRID' ]-value ).
    ENDIF.
    table_values_in( ct_values ).
    IF is_context-table_control = 'TC_FLIGHTS' AND is_context-row > 0.
      tc_flights-current_line = is_context-row.
      READ TABLE gt_shown INTO gs_flight INDEX is_context-row.
    ELSEIF is_context-row = 0.
      CLEAR gs_flight.
    ENDIF.
    TRY.
        output_modules(
          EXPORTING
            is_context = is_context
            io_session = io_session
          CHANGING
            ct_values  = ct_values
            ct_states  = ct_states ).
      CATCH zcx_gg_control_flow INTO lx_unwind.
    ENDTRY.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_CARRID' ] ).
      ct_values[ name = 'GV_CARRID' ]-value = CONV string( gv_carrid ).
    ELSE.
      INSERT VALUE #( name = 'GV_CARRID' value = CONV string( gv_carrid ) ) INTO TABLE ct_values.
    ENDIF.
    table_values_out( CHANGING ct_values = ct_values ).
    IF lx_unwind IS BOUND.
      RAISE EXCEPTION lx_unwind.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_input_module.
    DATA lx_unwind TYPE REF TO zcx_gg_control_flow.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      gv_ok_code = CONV #( ct_values[ name = 'GV_OK_CODE' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_CARRID' ] ).
      gv_carrid = CONV #( ct_values[ name = 'GV_CARRID' ]-value ).
    ENDIF.
    table_values_in( ct_values ).
    IF is_context-table_control = 'TC_FLIGHTS' AND is_context-row > 0.
      tc_flights-current_line = is_context-row.
      READ TABLE gt_shown INTO gs_flight INDEX is_context-row.
    ELSEIF is_context-row = 0.
      CLEAR gs_flight.
    ENDIF.
    TRY.
        input_modules(
          EXPORTING
            is_context = is_context
            io_session = io_session
          CHANGING
            ct_values  = ct_values ).
      CATCH zcx_gg_control_flow INTO lx_unwind.
    ENDTRY.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_CARRID' ] ).
      ct_values[ name = 'GV_CARRID' ]-value = CONV string( gv_carrid ).
    ELSE.
      INSERT VALUE #( name = 'GV_CARRID' value = CONV string( gv_carrid ) ) INTO TABLE ct_values.
    ENDIF.
    table_values_out( CHANGING ct_values = ct_values ).
    IF lx_unwind IS BOUND.
      RAISE EXCEPTION lx_unwind.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_on_value_request.
    DATA ct_values TYPE zif_gg_dynpro_types_v1=>ty_values.
    ct_values = it_values.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      gv_ok_code = CONV #( ct_values[ name = 'GV_OK_CODE' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_CARRID' ] ).
      gv_carrid = CONV #( ct_values[ name = 'GV_CARRID' ]-value ).
    ENDIF.
    table_values_in( ct_values ).
    IF is_context-table_control = 'TC_FLIGHTS' AND is_context-row > 0.
      tc_flights-current_line = is_context-row.
      READ TABLE gt_shown INTO gs_flight INDEX is_context-row.
    ELSEIF is_context-row = 0.
      CLEAR gs_flight.
    ENDIF.
    CASE is_context-module.
      WHEN 'F4_CARRID'.
        io_session->get_compatibility( )->f4_table_value_request( EXPORTING is_request = VALUE #( retfield = 'CARRID' dynpprog = io_session->get_context( )-program-program dynpnr = io_session->get_context( )-dynpro-screen dynprofield = 'GV_CARRID' value_org = 'S' ) CHANGING ct_value_tab = gt_carriers ).
      WHEN OTHERS.
        RETURN.
    ENDCASE.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_CARRID' ] ).
      ct_values[ name = 'GV_CARRID' ]-value = CONV string( gv_carrid ).
    ELSE.
      INSERT VALUE #( name = 'GV_CARRID' value = CONV string( gv_carrid ) ) INTO TABLE ct_values.
    ENDIF.
    table_values_out( CHANGING ct_values = ct_values ).
    rt_values = io_session->get_compatibility( )->get_value_help_values( ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_on_help_request.
    DATA ct_values TYPE zif_gg_dynpro_types_v1=>ty_values.
    ct_values = it_values.
    IF line_exists( ct_values[ name = 'GV_RESULT' ] ).
      rv_text = ct_values[ name = 'GV_RESULT' ]-value.
    ENDIF.
  ENDMETHOD.

  METHOD output_modules.
    CASE is_context-module.
      WHEN 'STATUS_0100'.
* Screen 100 chooses the airline, screen 200 edits its flights.
        io_session->get_dialog( )->set_status( VALUE #( status = 'HEADER' active_ucomm = VALUE #( ( 'BACK' ) ( 'EXIT' ) ( 'CANCEL' ) ( 'EDIT' ) ) active_pf_keys = VALUE #( ( 3 ) ( 15 ) ( 12 ) ( 13 ) ) exit_ucomm = VALUE #( ( 'BACK' ) ( 'CANCEL' ) ( 'EXIT' ) ) icon_bar = VALUE #( ( ucomm = 'EDIT' label = 'Edit flights' icon = 'ICON_CHANGE' ) ) pf_actions = VALUE #( ( number = 3 ucomm = 'BACK' ) ( number = 15 ucomm = 'EXIT' ) ( number = 12 ucomm = 'CANCEL' ) ( number = 13 ucomm = 'EDIT' ) ) ) ).
        io_session->get_dialog( )->set_title( 'Airline' ).
      WHEN 'STATUS_0200'.
        io_session->get_dialog( )->set_status( VALUE #( status = 'ITEMS' active_ucomm = VALUE #( ( 'BACK' ) ( 'EXIT' ) ( 'CANCEL' ) ( 'SAVE' ) ) active_pf_keys = VALUE #( ( 3 ) ( 15 ) ( 12 ) ( 11 ) ( 13 ) ) exit_ucomm = VALUE #( ( 'BACK' ) ( 'CANCEL' ) ( 'EXIT' ) ) icon_bar = VALUE #( ( ucomm = 'SAVE' label = 'Save' icon = 'ICON_SYSTEM_SAVE' ) ) pf_actions = VALUE #( ( number = 3 ucomm = 'BACK' ) ( number = 15 ucomm = 'EXIT' ) ( number = 12 ucomm = 'CANCEL' ) ( number = 11 ucomm = 'SAVE' ) ( number = 13 ucomm = 'SAVE' ) ) ) ).
        io_session->get_dialog( )->set_title( |Flights of { gv_carrid }| ).
        tc_flights-lines = lines( gt_shown ).
      WHEN OTHERS.
        RETURN.
    ENDCASE.
  ENDMETHOD.

  METHOD input_modules.
    CASE is_context-module.
      WHEN 'EXIT_0100'.
        CLEAR gv_ok_code.
        io_session->get_dialog( )->leave_to_screen( '0000' ).
      WHEN 'CHECK_CARRID'.
        IF NOT line_exists( gt_carriers[ carrid = gv_carrid ] ).
          io_session->message( VALUE #( type = zif_gg_session_types_v1=>message_type_error text = |Airline { gv_carrid } does not exist| ) ).
        ENDIF.
      WHEN 'F4_CARRID'.
        io_session->get_compatibility( )->f4_table_value_request( EXPORTING is_request = VALUE #( retfield = 'CARRID' dynpprog = io_session->get_context( )-program-program dynpnr = io_session->get_context( )-dynpro-screen dynprofield = 'GV_CARRID' value_org = 'S' ) CHANGING ct_value_tab = gt_carriers ).
      WHEN 'USER_COMMAND_0100'.
        IF gv_ok_code = 'EDIT'.
          CLEAR gv_ok_code.
          gt_shown = VALUE #( FOR ls_flight IN gt_flights WHERE ( carrid = gv_carrid ) ( ls_flight ) ).
          io_session->get_dialog( )->leave_to_screen( '0200' ).
        ENDIF.
        CLEAR gv_ok_code.
      WHEN 'EXIT_0200'.
        CLEAR gv_ok_code.
        io_session->get_dialog( )->leave_to_screen( '0100' ).
      WHEN 'MODIFY_FLIGHT'.
        MODIFY gt_shown FROM gs_flight INDEX tc_flights-current_line.
      WHEN 'USER_COMMAND_0200'.
        IF gv_ok_code = 'SAVE'.
          LOOP AT gt_shown INTO gs_flight.
            MODIFY gt_flights FROM gs_flight TRANSPORTING cityfrom cityto WHERE carrid = gs_flight-carrid AND connid = gs_flight-connid.
          ENDLOOP.
          io_session->message( VALUE #( type = zif_gg_session_types_v1=>message_type_success text = |{ lines( gt_shown ) } flights of { gv_carrid } saved| ) ).
        ENDIF.
        CLEAR gv_ok_code.
      WHEN OTHERS.
        RETURN.
    ENDCASE.
  ENDMETHOD.

  METHOD table_values_in.
    LOOP AT gt_shown ASSIGNING FIELD-SYMBOL(<ls_table1_hydrate_row>).
      DATA(lv_table1_hydrate_row) = sy-tabix.
      IF line_exists( it_values[ container = 'TC_FLIGHTS' name = 'CONNID' row = lv_table1_hydrate_row ] ).
        <ls_table1_hydrate_row>-connid = CONV #( it_values[ container = 'TC_FLIGHTS' name = 'CONNID' row = lv_table1_hydrate_row ]-value ).
      ENDIF.
      IF line_exists( it_values[ container = 'TC_FLIGHTS' name = 'CITYFROM' row = lv_table1_hydrate_row ] ).
        <ls_table1_hydrate_row>-cityfrom = CONV #( it_values[ container = 'TC_FLIGHTS' name = 'CITYFROM' row = lv_table1_hydrate_row ]-value ).
      ENDIF.
      IF line_exists( it_values[ container = 'TC_FLIGHTS' name = 'CITYTO' row = lv_table1_hydrate_row ] ).
        <ls_table1_hydrate_row>-cityto = CONV #( it_values[ container = 'TC_FLIGHTS' name = 'CITYTO' row = lv_table1_hydrate_row ]-value ).
      ENDIF.
    ENDLOOP.
    IF line_exists( it_values[ name = 'TC_FLIGHTS-TOP_LINE' ] ).
      tc_flights-top_line = CONV #( it_values[ name = 'TC_FLIGHTS-TOP_LINE' ]-value ).
    ENDIF.
    IF line_exists( it_values[ name = 'TC_FLIGHTS-LINES' ] ).
      tc_flights-lines = CONV #( it_values[ name = 'TC_FLIGHTS-LINES' ]-value ).
    ENDIF.
    IF tc_flights-top_line = 0.
      tc_flights-top_line = 1.
    ENDIF.
  ENDMETHOD.

  METHOD table_values_out.
    DELETE ct_values WHERE container = 'TC_FLIGHTS'.
    LOOP AT gt_shown ASSIGNING FIELD-SYMBOL(<ls_table1_flush_row>).
      DATA(lv_table1_flush_row) = sy-tabix.
      INSERT VALUE #( container = 'TC_FLIGHTS' name = 'CONNID' row = lv_table1_flush_row value = CONV string( <ls_table1_flush_row>-connid ) ) INTO TABLE ct_values.
      INSERT VALUE #( container = 'TC_FLIGHTS' name = 'CITYFROM' row = lv_table1_flush_row value = CONV string( <ls_table1_flush_row>-cityfrom ) ) INTO TABLE ct_values.
      INSERT VALUE #( container = 'TC_FLIGHTS' name = 'CITYTO' row = lv_table1_flush_row value = CONV string( <ls_table1_flush_row>-cityto ) ) INTO TABLE ct_values.
    ENDLOOP.
    IF line_exists( ct_values[ name = 'TC_FLIGHTS-TOP_LINE' ] ).
      ct_values[ name = 'TC_FLIGHTS-TOP_LINE' ]-value = CONV string( tc_flights-top_line ).
    ELSE.
      INSERT VALUE #( name = 'TC_FLIGHTS-TOP_LINE' value = CONV string( tc_flights-top_line ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'TC_FLIGHTS-LINES' ] ).
      ct_values[ name = 'TC_FLIGHTS-LINES' ]-value = CONV string( tc_flights-lines ).
    ELSE.
      INSERT VALUE #( name = 'TC_FLIGHTS-LINES' value = CONV string( tc_flights-lines ) ) INTO TABLE ct_values.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~get_settings.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~end_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page_during_line_sel.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_line_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_user_command.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_pf.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_resumable_v1~resume.
* Continuation states are explicit so unsupported suspension semantics remain visible.
    CASE is_resume-continuation-id.
      WHEN 'AFTER_0100'.
        RETURN.
      WHEN OTHERS.
        RETURN.
    ENDCASE.
  ENDMETHOD.

ENDCLASS.
