* Generated by open-abap-gui converter 0.1.0.
* Source object: ZGG_EX_121
* Source file: examples/zgg_ex_121.prog.abap
* Source SHA-256: ce0fc5f87e3e6beadc3ea4091e4daef61cb575527681c863e84d97022c5198a6
* Target class: ZCL_GG_EX_121
* Manifest schema: 1
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_121 DEFINITION PUBLIC FINAL CREATE PUBLIC FRIENDS zcl_gg_ex_121_h1.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_screen_provider_v1.
    INTERFACES zif_gg_transaction_v1.
    INTERFACES zif_gg_resumable_v1.

  PRIVATE SECTION.
    DATA go_dialog TYPE REF TO cl_gui_dialogbox_container.
    DATA go_editor TYPE REF TO cl_gui_textedit.
    DATA gv_ok_code TYPE sy-ucomm.
    DATA gv_state TYPE c LENGTH 60.
    METHODS form_open_dialog
      IMPORTING
        io_session TYPE REF TO zif_gg_session_v1.

ENDCLASS.

CLASS zcl_gg_ex_121 IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZGG_EX_121' description = 'Dialog box container' program = 'ZGG_EX_121' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'Dialog box container' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'Dialog box container' ).
    io_session->get_dialog( )->call_screen(
      is_call         = VALUE #( screen = '0100' )
      is_continuation = VALUE #( id = 'AFTER_0100' ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~get_initial_screen.
    rv_screen = '0100'.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~build_screens.
    io_builder->begin_screen( VALUE #( number = '0100' title = 'Dialog box container' next_screen = '0100' ok_code = 'GV_OK_CODE' width = 800 height = 644 ) ).
    io_builder->add_pushbutton( VALUE #( control = VALUE #( name = 'BTN_OPEN' position = VALUE #( row = 36 column = 5 width = 180 height = 26 ) ) text = 'Open dialog box' ucomm = 'OPEN' ) ).
    io_builder->add_text( VALUE #( control = VALUE #( name = 'LBL_STATE' position = VALUE #( row = 88 column = 5 width = 60 height = 26 ) ) text = 'State' ) ).
    io_builder->add_output_field( VALUE #( control = VALUE #( name = 'GV_STATE' position = VALUE #( row = 88 column = 75 width = 600 height = 26 ) ) data_type = VALUE #( typ = 'C' length = 60 ) ) ).
    io_builder->end_screen( ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~build_flow_logic.
    io_builder->begin_screen( '0100' ).
    io_builder->begin_pbo( ).
    io_builder->add_module( VALUE #( name = 'STATUS_0100' ) ).
    io_builder->end_processing( ).
    io_builder->begin_pai( ).
    io_builder->add_module( VALUE #( name = 'USER_COMMAND_0100' on_input = abap_true ) ).
    io_builder->end_processing( ).
    io_builder->end_screen( ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~initialization.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_STATE' ] ).
      ct_values[ name = 'GV_STATE' ]-value = CONV string( gv_state ).
    ELSE.
      INSERT VALUE #( name = 'GV_STATE' value = CONV string( gv_state ) ) INTO TABLE ct_values.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_output_module.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      gv_ok_code = CONV #( ct_values[ name = 'GV_OK_CODE' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_STATE' ] ).
      gv_state = CONV #( ct_values[ name = 'GV_STATE' ]-value ).
    ENDIF.
    CASE is_context-module.
      WHEN 'STATUS_0100'.
        IF go_dialog IS INITIAL AND gv_state IS INITIAL.
          form_open_dialog( io_session = io_session ).
        ENDIF.
      WHEN OTHERS.
        RETURN.
    ENDCASE.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_STATE' ] ).
      ct_values[ name = 'GV_STATE' ]-value = CONV string( gv_state ).
    ELSE.
      INSERT VALUE #( name = 'GV_STATE' value = CONV string( gv_state ) ) INTO TABLE ct_values.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_input_module.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      gv_ok_code = CONV #( ct_values[ name = 'GV_OK_CODE' ]-value ).
    ENDIF.
    CASE is_context-module.
      WHEN 'USER_COMMAND_0100'.
        IF gv_ok_code = 'OPEN' AND go_dialog IS INITIAL.
          form_open_dialog( io_session = io_session ).
        ENDIF.
        CLEAR gv_ok_code.
      WHEN OTHERS.
        RETURN.
    ENDCASE.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_STATE' ] ).
      ct_values[ name = 'GV_STATE' ]-value = CONV string( gv_state ).
    ELSE.
      INSERT VALUE #( name = 'GV_STATE' value = CONV string( gv_state ) ) INTO TABLE ct_values.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_on_value_request.
    DATA ct_values TYPE zif_gg_dynpro_types_v1=>ty_values.
    ct_values = it_values.
    rt_values = io_session->get_compatibility( )->get_value_help_values( ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_on_help_request.
    DATA ct_values TYPE zif_gg_dynpro_types_v1=>ty_values.
    ct_values = it_values.
    IF line_exists( ct_values[ name = 'GV_RESULT' ] ).
      rv_text = ct_values[ name = 'GV_RESULT' ]-value.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_resumable_v1~resume.
* Continuation states are explicit so unsupported suspension semantics remain visible.
    CASE is_resume-continuation-id.
      WHEN 'AFTER_0100'.
        RETURN.
      WHEN OTHERS.
        RETURN.
    ENDCASE.
  ENDMETHOD.

  METHOD form_open_dialog.
    CREATE OBJECT go_dialog EXPORTING width   = 360
                                      height  = 180
                                      caption = 'Dialog content'.
    zcl_gg_ex_121_h1=>go_owner = me.
    zcl_gg_ex_121_h1=>go_session = io_session.
    SET HANDLER zcl_gg_ex_121_h1=>on_close FOR go_dialog.
    CREATE OBJECT go_editor EXPORTING parent = go_dialog.
    go_editor->set_textstream( 'Modal dialog body' ).
    gv_state = 'Dialog box open'.
  ENDMETHOD.

ENDCLASS.
