* Generated by open-abap-gui converter 0.1.0.
* Source object: ZGG_EX_055
* Source file: examples/zgg_ex_055.prog.abap
* Source SHA-256: 61d0948fc86871791add62a36f794e1e7d05544193169b86e53805f9b5fa4dc5
* Target class: ZCL_GG_EX_055
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_055 DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_transaction_v1.
    INTERFACES zif_gg_resumable_v1.

  PRIVATE SECTION.
    TYPES abaplist TYPE c LENGTH 1.
    DATA gt_list TYPE STANDARD TABLE OF abaplist WITH DEFAULT KEY.

ENDCLASS.

CLASS zcl_gg_ex_055 IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZGG_EX_055' description = 'SUBMIT EXPORTING LIST TO MEMORY' program = 'ZGG_EX_055' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'SUBMIT EXPORTING LIST TO MEMORY' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'SUBMIT EXPORTING LIST TO MEMORY' ).
    io_session->get_navigation( )->submit_and_return(
      is_submit       = VALUE #( program = 'ZGG_EX_001' list_to_memory = abap_true )
      is_continuation = VALUE #( id = 'AFTER_SUBMIT' ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_resumable_v1~resume.
* Continuation states are explicit so unsupported suspension semantics remain visible.
    CASE is_resume-continuation-id.
      WHEN 'AFTER_SUBMIT'.
        DATA(lt_lines) = io_session->get_navigation( )->get_list_from_memory( ).
        LOOP AT lt_lines INTO DATA(lv_line).
          io_session->get_list( )->get_writer( )->write_field( VALUE #( text = lv_line placement = VALUE #( new_line = abap_true ) ) ).
        ENDLOOP.
      WHEN OTHERS.
        RETURN.
    ENDCASE.
  ENDMETHOD.

ENDCLASS.
