* Generated by open-abap-gui converter 0.1.0.
* Source object: ZGG_EX_144
* Source file: examples/zgg_ex_144.prog.abap
* Source SHA-256: 0045a805319e6c9c2bd5ddf42f6e89d4a5ed3512e590fc4b29998e624ebe479c
* Target class: ZCL_GG_EX_144
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_144 DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_transaction_v1.

  PRIVATE SECTION.
    TYPES: BEGIN OF ty_flight, carrid TYPE c LENGTH 3, connid TYPE n LENGTH 4, cityfrom TYPE c LENGTH 20, cityto TYPE c LENGTH 20, seatsocc TYPE i, END OF ty_flight.
    DATA gt_flights TYPE STANDARD TABLE OF ty_flight WITH DEFAULT KEY.
    DATA go_alv TYPE REF TO cl_salv_table.
    DATA go_column TYPE REF TO cl_salv_column.
    DATA gx_msg TYPE REF TO cx_salv_msg.
    DATA gx_not_found TYPE REF TO cx_salv_not_found.

ENDCLASS.

CLASS zcl_gg_ex_144 IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZGG_EX_144' description = 'SALV table' program = 'ZGG_EX_144' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'SALV table' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'SALV table' ).
    gt_flights = VALUE #( ( carrid = 'LH' connid = '0400' cityfrom = 'Frankfurt' cityto = 'New York' seatsocc = 180 ) ( carrid = 'UA' connid = '0941' cityfrom = 'Frankfurt' cityto = 'San Francisco' seatsocc = 210 ) ( carrid = 'AF' connid = '0010' cityfrom = 'Paris' cityto = 'New York' seatsocc = 160 ) ).
    TRY.
        cl_salv_table=>factory( IMPORTING r_salv_table = go_alv CHANGING t_table = gt_flights ).
      CATCH cx_salv_msg INTO gx_msg.
        io_session->message(
          is_message = VALUE #( type = zif_gg_session_types_v1=>message_type_error )
          ia_text    = gx_msg ).
    ENDTRY.
    go_alv->get_functions( )->set_all( abap_true ).
    go_alv->get_columns( )->set_optimize( abap_true ).
    go_alv->get_display_settings( )->set_list_header( 'Flights' ).
    go_alv->get_display_settings( )->set_striped_pattern( abap_true ).
    TRY.
        go_column = go_alv->get_columns( )->get_column( 'CARRID' ).
        go_column->set_long_text( 'Airline' ).
        go_column = go_alv->get_columns( )->get_column( 'CONNID' ).
        go_column->set_long_text( 'Flight' ).
        go_column = go_alv->get_columns( )->get_column( 'CITYFROM' ).
        go_column->set_long_text( 'From' ).
        go_column = go_alv->get_columns( )->get_column( 'CITYTO' ).
        go_column->set_long_text( 'To' ).
        go_column = go_alv->get_columns( )->get_column( 'SEATSOCC' ).
        go_column->set_long_text( 'Occupied' ).
      CATCH cx_salv_not_found INTO gx_not_found.
        io_session->message(
          is_message = VALUE #( type = zif_gg_session_types_v1=>message_type_error )
          ia_text    = gx_not_found ).
    ENDTRY.
    go_alv->display( ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    RETURN.
  ENDMETHOD.

ENDCLASS.
