* Generated by open-abap-gui converter 0.1.0.
* Source object: ZGG_EX_066
* Source file: examples/zgg_ex_066.prog.abap
* Source SHA-256: 3578af25f2644b39f4c0ce6b0e72587b3ce8c5c941f003204c070ef4e07da563
* Target class: ZCL_GG_EX_066
* Manifest schema: 1
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_066 DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_transaction_v1.
    INTERFACES zif_gg_list_processing_v1.

ENDCLASS.

CLASS zcl_gg_ex_066 IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZGG_EX_066' description = 'Unicode and hostile shell text' program = 'ZGG_EX_066' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'Unicode and hostile shell text' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    ro_list_processing = me.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'Unicode and hostile shell text' ).
* The title, the function text and the list texts hold right-to-left script,
* combining characters, an emoji and markup characters. They live in the GUI
* status and the text pool, as on SAP, and must reach the browser as text.
    io_session->get_list( )->set_title( 'Unicode and hostile shell text' ).
    DATA(lo_writer) = io_session->get_list( )->get_writer( ).
    io_session->get_list( )->set_status( VALUE #( status = 'SHELL66' active_ucomm = VALUE #( ( 'RUN66' ) ) active_pf_keys = VALUE #( ( 13 ) ) icon_bar = VALUE #( ( ucomm = 'RUN66' label = cl_abap_codepage=>convert_from( CONV xstring( '52756E20226E6F77222026203C676F3E20F09F9A80' ) ) icon = 'ICON_EXECUTE_OBJECT' ) ) pf_actions = VALUE #( ( number = 13 ucomm = 'RUN66' ) ) ) ).
    io_session->get_list( )->set_title( cl_abap_codepage=>convert_from( CONV xstring( '52544C20D7A9D79CD795D79D20F09F9A802026203C7469746C653E' ) ) ).
    lo_writer->write_field( VALUE #( text = |{ TEXT-001 }| placement = VALUE #( new_line = abap_true ) ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~get_settings.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~end_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page_during_line_sel.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_line_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_user_command.
    DATA(lo_writer) = io_session->get_list( )->get_writer( ).
    IF iv_ucomm = 'RUN66'.
      lo_writer->write_field( VALUE #( text = |{ TEXT-002 }| placement = VALUE #( new_line = abap_true ) ) ).
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_pf.
    RETURN.
  ENDMETHOD.

ENDCLASS.
