* Generated by open-abap-gui converter 0.1.0.
* Source object: ZGG_EX_078
* Source file: examples/zgg_ex_078.prog.abap
* Source SHA-256: 0afa11ca3dc2fb9ae4684df76b49c3185c9f68eb09f9d5f139d0370b96ea1041
* Target class: ZCL_GG_EX_078
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_078 DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_transaction_v1.
    INTERFACES zif_gg_list_processing_v1.

  PRIVATE SECTION.
    TYPES: BEGIN OF ty_carrier, carrid TYPE c LENGTH 3, END OF ty_carrier.
    DATA zsflight TYPE zsflight.
    DATA gt_carriers TYPE STANDARD TABLE OF ty_carrier WITH DEFAULT KEY.
    DATA mv_p_car TYPE c LENGTH 3.
    DATA mv_p_req TYPE c LENGTH 20.
    DATA mv_s_rng LIKE RANGE OF zsflight-carrid.
    METHODS form_carrier_help
      IMPORTING
        io_session TYPE REF TO zif_gg_session_v1
        iv_field   TYPE csequence.

ENDCLASS.

CLASS zcl_gg_ex_078 IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZGG_EX_078' description = 'Field and range value help' program = 'ZGG_EX_078' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'Field and range value help' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    ro_list_processing = me.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    io_builder->add_parameter( VALUE #( name = 'P_CAR' text = 'Carrier' data_type = VALUE #( typ = 'C' length = 3 ) value_help = abap_true ) ).
    io_builder->add_select_option( VALUE #( name = 'S_RNG' text = 'Range' data_type = VALUE #( typ = 'C' length = 3 ) value_help = abap_true ) ).
    io_builder->add_parameter( VALUE #( name = 'P_REQ' text = 'Required value' data_type = VALUE #( typ = 'C' length = 20 ) obligatory = abap_true ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    DATA lt_ggconv_s_rng LIKE mv_s_rng.
    mv_p_car = ct_values[ name = 'P_CAR' ]-value.
    mv_p_req = ct_values[ name = 'P_REQ' ]-value.
    mv_s_rng = CORRESPONDING #( ct_values[ name = 'S_RNG' ]-ranges ).
    IF ct_values[ name = 'P_CAR' ]-value <> mv_p_car.
      ct_values[ name = 'P_CAR' ]-value = |{ mv_p_car }|.
    ENDIF.
    IF ct_values[ name = 'P_REQ' ]-value <> mv_p_req.
      ct_values[ name = 'P_REQ' ]-value = |{ mv_p_req }|.
    ENDIF.
    lt_ggconv_s_rng = mv_s_rng.
    lt_ggconv_s_rng = CORRESPONDING #( ct_values[ name = 'S_RNG' ]-ranges ).
    IF lt_ggconv_s_rng <> mv_s_rng.
      ct_values[ name = 'S_RNG' ]-ranges = CORRESPONDING #( mv_s_rng ).
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    DATA lt_ggconv_s_rng LIKE mv_s_rng.
    mv_p_car = ct_values[ name = 'P_CAR' ]-value.
    mv_p_req = ct_values[ name = 'P_REQ' ]-value.
    mv_s_rng = CORRESPONDING #( ct_values[ name = 'S_RNG' ]-ranges ).
    IF ct_values[ name = 'P_CAR' ]-value <> mv_p_car.
      ct_values[ name = 'P_CAR' ]-value = |{ mv_p_car }|.
    ENDIF.
    IF ct_values[ name = 'P_REQ' ]-value <> mv_p_req.
      ct_values[ name = 'P_REQ' ]-value = |{ mv_p_req }|.
    ENDIF.
    lt_ggconv_s_rng = mv_s_rng.
    lt_ggconv_s_rng = CORRESPONDING #( ct_values[ name = 'S_RNG' ]-ranges ).
    IF lt_ggconv_s_rng <> mv_s_rng.
      ct_values[ name = 'S_RNG' ]-ranges = CORRESPONDING #( mv_s_rng ).
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    DATA lt_ggconv_s_rng LIKE mv_s_rng.
    mv_p_car = ct_values[ name = 'P_CAR' ]-value.
    mv_p_req = ct_values[ name = 'P_REQ' ]-value.
    mv_s_rng = CORRESPONDING #( ct_values[ name = 'S_RNG' ]-ranges ).
    IF ct_values[ name = 'P_CAR' ]-value <> mv_p_car.
      ct_values[ name = 'P_CAR' ]-value = |{ mv_p_car }|.
    ENDIF.
    IF ct_values[ name = 'P_REQ' ]-value <> mv_p_req.
      ct_values[ name = 'P_REQ' ]-value = |{ mv_p_req }|.
    ENDIF.
    lt_ggconv_s_rng = mv_s_rng.
    lt_ggconv_s_rng = CORRESPONDING #( ct_values[ name = 'S_RNG' ]-ranges ).
    IF lt_ggconv_s_rng <> mv_s_rng.
      ct_values[ name = 'S_RNG' ]-ranges = CORRESPONDING #( mv_s_rng ).
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    DATA lt_ggconv_s_rng LIKE mv_s_rng.
    mv_p_car = ct_values[ name = 'P_CAR' ]-value.
    mv_p_req = ct_values[ name = 'P_REQ' ]-value.
    mv_s_rng = CORRESPONDING #( ct_values[ name = 'S_RNG' ]-ranges ).
    IF ct_values[ name = 'P_CAR' ]-value <> mv_p_car.
      ct_values[ name = 'P_CAR' ]-value = |{ mv_p_car }|.
    ENDIF.
    IF ct_values[ name = 'P_REQ' ]-value <> mv_p_req.
      ct_values[ name = 'P_REQ' ]-value = |{ mv_p_req }|.
    ENDIF.
    lt_ggconv_s_rng = mv_s_rng.
    lt_ggconv_s_rng = CORRESPONDING #( ct_values[ name = 'S_RNG' ]-ranges ).
    IF lt_ggconv_s_rng <> mv_s_rng.
      ct_values[ name = 'S_RNG' ]-ranges = CORRESPONDING #( mv_s_rng ).
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    DATA lt_ggconv_s_rng LIKE mv_s_rng.
    mv_p_car = ct_values[ name = 'P_CAR' ]-value.
    mv_p_req = ct_values[ name = 'P_REQ' ]-value.
    mv_s_rng = CORRESPONDING #( ct_values[ name = 'S_RNG' ]-ranges ).
    IF ct_values[ name = 'P_CAR' ]-value <> mv_p_car.
      ct_values[ name = 'P_CAR' ]-value = |{ mv_p_car }|.
    ENDIF.
    IF ct_values[ name = 'P_REQ' ]-value <> mv_p_req.
      ct_values[ name = 'P_REQ' ]-value = |{ mv_p_req }|.
    ENDIF.
    lt_ggconv_s_rng = mv_s_rng.
    lt_ggconv_s_rng = CORRESPONDING #( ct_values[ name = 'S_RNG' ]-ranges ).
    IF lt_ggconv_s_rng <> mv_s_rng.
      ct_values[ name = 'S_RNG' ]-ranges = CORRESPONDING #( mv_s_rng ).
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    DATA lt_ggconv_s_rng LIKE mv_s_rng.
    mv_p_car = ct_values[ name = 'P_CAR' ]-value.
    mv_p_req = ct_values[ name = 'P_REQ' ]-value.
    mv_s_rng = CORRESPONDING #( ct_values[ name = 'S_RNG' ]-ranges ).
    IF ct_values[ name = 'P_CAR' ]-value <> mv_p_car.
      ct_values[ name = 'P_CAR' ]-value = |{ mv_p_car }|.
    ENDIF.
    IF ct_values[ name = 'P_REQ' ]-value <> mv_p_req.
      ct_values[ name = 'P_REQ' ]-value = |{ mv_p_req }|.
    ENDIF.
    lt_ggconv_s_rng = mv_s_rng.
    lt_ggconv_s_rng = CORRESPONDING #( ct_values[ name = 'S_RNG' ]-ranges ).
    IF lt_ggconv_s_rng <> mv_s_rng.
      ct_values[ name = 'S_RNG' ]-ranges = CORRESPONDING #( mv_s_rng ).
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    DATA lt_ggconv_s_rng LIKE mv_s_rng.
    mv_p_car = ct_values[ name = 'P_CAR' ]-value.
    mv_p_req = ct_values[ name = 'P_REQ' ]-value.
    mv_s_rng = CORRESPONDING #( ct_values[ name = 'S_RNG' ]-ranges ).
    IF ct_values[ name = 'P_CAR' ]-value <> mv_p_car.
      ct_values[ name = 'P_CAR' ]-value = |{ mv_p_car }|.
    ENDIF.
    IF ct_values[ name = 'P_REQ' ]-value <> mv_p_req.
      ct_values[ name = 'P_REQ' ]-value = |{ mv_p_req }|.
    ENDIF.
    lt_ggconv_s_rng = mv_s_rng.
    lt_ggconv_s_rng = CORRESPONDING #( ct_values[ name = 'S_RNG' ]-ranges ).
    IF lt_ggconv_s_rng <> mv_s_rng.
      ct_values[ name = 'S_RNG' ]-ranges = CORRESPONDING #( mv_s_rng ).
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    IF iv_name = 'P_CAR'.
      mv_p_car = it_values[ name = 'P_CAR' ]-value.
      mv_p_req = it_values[ name = 'P_REQ' ]-value.
      mv_s_rng = CORRESPONDING #( it_values[ name = 'S_RNG' ]-ranges ).
      form_carrier_help(
        io_session = io_session
        iv_field   = 'P_CAR' ).
      IF mv_p_car <> it_values[ name = 'P_CAR' ]-value.
        rt_values = VALUE #( ( sign = zif_gg_selection_screen_types=>sign_include option = zif_gg_selection_screen_types=>option_eq low = |{ mv_p_car }| ) ).
      ENDIF.
    ENDIF.
    IF iv_name = 'S_RNG'.
      mv_p_car = it_values[ name = 'P_CAR' ]-value.
      mv_p_req = it_values[ name = 'P_REQ' ]-value.
      mv_s_rng = CORRESPONDING #( it_values[ name = 'S_RNG' ]-ranges ).
      form_carrier_help(
        io_session = io_session
        iv_field   = 'S_RNG-LOW' ).
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    mv_p_car = it_values[ name = 'P_CAR' ]-value.
    mv_p_req = it_values[ name = 'P_REQ' ]-value.
    mv_s_rng = CORRESPONDING #( it_values[ name = 'S_RNG' ]-ranges ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'Field and range value help' ).
    DATA(lo_writer) = io_session->get_list( )->get_writer( ).
    mv_p_car = it_values[ name = 'P_CAR' ]-value.
    mv_p_req = it_values[ name = 'P_REQ' ]-value.
    mv_s_rng = CORRESPONDING #( it_values[ name = 'S_RNG' ]-ranges ).
    lo_writer->write_field( VALUE #( text = |{ mv_p_car }| ) ).
    LOOP AT mv_s_rng INTO DATA(ls_s_rng_range).
      lo_writer->write_field( VALUE #( text = |{ ls_s_rng_range-low }| placement = VALUE #( new_line = abap_true ) ) ).
    ENDLOOP.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    mv_p_car = it_values[ name = 'P_CAR' ]-value.
    mv_p_req = it_values[ name = 'P_REQ' ]-value.
    mv_s_rng = CORRESPONDING #( it_values[ name = 'S_RNG' ]-ranges ).
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~get_settings.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~end_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page_during_line_sel.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_line_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_user_command.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_pf.
    RETURN.
  ENDMETHOD.

  METHOD form_carrier_help.
    gt_carriers = VALUE #( ( carrid = 'AA' ) ( carrid = 'LH' ) ( carrid = 'SQ' ) ).
    io_session->get_compatibility( )->f4_table_value_request( EXPORTING is_request = VALUE #( retfield = 'CARRID' dynpprog = io_session->get_context( )-program-program dynpnr = io_session->get_context( )-selection-screen dynprofield = iv_field value_org = 'S' ) CHANGING ct_value_tab = gt_carriers ).
  ENDMETHOD.

ENDCLASS.
