* Generated by open-abap-gui converter.
* Source object: ZGG_EX_117
* Source file: examples/zgg_ex_117.prog.abap
* Source SHA-256: d332c142ce13eef4c59d8ec967b3f26d6e2d7fb8a9f8c4b8b7f3bc4b4565a0d1
* Target class: ZCL_GG_EX_117
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_117 DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_screen_provider_v1.
    INTERFACES zif_gg_transaction_v1.
    INTERFACES zif_gg_resumable_v1.

  PRIVATE SECTION.
    DATA go_container TYPE REF TO cl_gui_custom_container.
    DATA go_editor TYPE REF TO cl_gui_textedit.
    DATA gv_ok_code TYPE sy-ucomm.
    DATA gv_generation TYPE i.
    DATA gv_large TYPE abap_bool.
    DATA gv_state TYPE c LENGTH 60.
    METHODS form_create_editor
      IMPORTING
        io_session TYPE REF TO zif_gg_session_v1.
    METHODS output_modules
      IMPORTING
        is_context TYPE zif_gg_dynpro_types_v1=>ty_module_context
        io_session TYPE REF TO zif_gg_session_v1
      CHANGING
        ct_values  TYPE zif_gg_dynpro_types_v1=>ty_values
        ct_states  TYPE zif_gg_dynpro_types_v1=>ty_states.
    METHODS input_modules
      IMPORTING
        is_context TYPE zif_gg_dynpro_types_v1=>ty_module_context
        io_session TYPE REF TO zif_gg_session_v1
      CHANGING
        ct_values  TYPE zif_gg_dynpro_types_v1=>ty_values.

ENDCLASS.

CLASS zcl_gg_ex_117 IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZGG_EX_117' description = 'Custom container' program = 'ZGG_EX_117' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'Custom container' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'Custom container' ).
    io_session->get_dialog( )->call_screen(
      is_call         = VALUE #( screen = '0100' )
      is_continuation = VALUE #( id = 'AFTER_0100' ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~get_initial_screen.
    rv_screen = '0100'.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~build_screens.
    io_builder->begin_screen( VALUE #( number = '0100' title = 'Custom container' next_screen = '0100' ok_code = 'GV_OK_CODE' width = 800 height = 644 ) ).
    io_builder->add_custom_control( VALUE #( control = VALUE #( name = 'CC_MAIN' position = VALUE #( row = 10 column = 5 width = 780 height = 416 ) ) resizing = VALUE #( vertical = abap_true min_height = 130 horizontal = abap_true min_width = 200 ) ) ).
    io_builder->add_pushbutton( VALUE #( control = VALUE #( name = 'BTN_RESIZE' position = VALUE #( row = 452 column = 5 width = 160 height = 26 ) ) text = 'Resize child' ucomm = 'RESIZE' ) ).
    io_builder->add_pushbutton( VALUE #( control = VALUE #( name = 'BTN_REPLACE' position = VALUE #( row = 452 column = 185 width = 160 height = 26 ) ) text = 'Replace child' ucomm = 'REPLACE' ) ).
    io_builder->add_text( VALUE #( control = VALUE #( name = 'LBL_STATE' position = VALUE #( row = 504 column = 5 width = 60 height = 26 ) ) text = 'State' ) ).
    io_builder->add_output_field( VALUE #( control = VALUE #( name = 'GV_STATE' position = VALUE #( row = 504 column = 75 width = 600 height = 26 ) ) data_type = VALUE #( typ = 'C' length = 60 ) ) ).
    io_builder->end_screen( ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~build_flow_logic.
    io_builder->begin_screen( '0100' ).
    io_builder->begin_pbo( ).
    io_builder->add_module( VALUE #( name = 'STATUS_0100' ) ).
    io_builder->end_processing( ).
    io_builder->begin_pai( ).
    io_builder->add_module( VALUE #( name = 'USER_COMMAND_0100' on_input = abap_true ) ).
    io_builder->end_processing( ).
    io_builder->end_screen( ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~initialization.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_GENERATION' ] ).
      ct_values[ name = 'GV_GENERATION' ]-value = CONV string( gv_generation ).
    ELSE.
      INSERT VALUE #( name = 'GV_GENERATION' value = CONV string( gv_generation ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_LARGE' ] ).
      ct_values[ name = 'GV_LARGE' ]-value = CONV string( gv_large ).
    ELSE.
      INSERT VALUE #( name = 'GV_LARGE' value = CONV string( gv_large ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_STATE' ] ).
      ct_values[ name = 'GV_STATE' ]-value = CONV string( gv_state ).
    ELSE.
      INSERT VALUE #( name = 'GV_STATE' value = CONV string( gv_state ) ) INTO TABLE ct_values.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_output_module.
    DATA lx_unwind TYPE REF TO zcx_gg_control_flow.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      gv_ok_code = CONV #( ct_values[ name = 'GV_OK_CODE' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_GENERATION' ] ).
      gv_generation = CONV #( ct_values[ name = 'GV_GENERATION' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_LARGE' ] ).
      gv_large = CONV #( ct_values[ name = 'GV_LARGE' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_STATE' ] ).
      gv_state = CONV #( ct_values[ name = 'GV_STATE' ]-value ).
    ENDIF.
    TRY.
        output_modules(
          EXPORTING
            is_context = is_context
            io_session = io_session
          CHANGING
            ct_values  = ct_values
            ct_states  = ct_states ).
      CATCH zcx_gg_control_flow INTO lx_unwind.
    ENDTRY.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_GENERATION' ] ).
      ct_values[ name = 'GV_GENERATION' ]-value = CONV string( gv_generation ).
    ELSE.
      INSERT VALUE #( name = 'GV_GENERATION' value = CONV string( gv_generation ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_LARGE' ] ).
      ct_values[ name = 'GV_LARGE' ]-value = CONV string( gv_large ).
    ELSE.
      INSERT VALUE #( name = 'GV_LARGE' value = CONV string( gv_large ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_STATE' ] ).
      ct_values[ name = 'GV_STATE' ]-value = CONV string( gv_state ).
    ELSE.
      INSERT VALUE #( name = 'GV_STATE' value = CONV string( gv_state ) ) INTO TABLE ct_values.
    ENDIF.
    IF lx_unwind IS BOUND.
      RAISE EXCEPTION lx_unwind.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_input_module.
    DATA lx_unwind TYPE REF TO zcx_gg_control_flow.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      gv_ok_code = CONV #( ct_values[ name = 'GV_OK_CODE' ]-value ).
    ENDIF.
    TRY.
        input_modules(
          EXPORTING
            is_context = is_context
            io_session = io_session
          CHANGING
            ct_values  = ct_values ).
      CATCH zcx_gg_control_flow INTO lx_unwind.
    ENDTRY.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_GENERATION' ] ).
      ct_values[ name = 'GV_GENERATION' ]-value = CONV string( gv_generation ).
    ELSE.
      INSERT VALUE #( name = 'GV_GENERATION' value = CONV string( gv_generation ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_LARGE' ] ).
      ct_values[ name = 'GV_LARGE' ]-value = CONV string( gv_large ).
    ELSE.
      INSERT VALUE #( name = 'GV_LARGE' value = CONV string( gv_large ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_STATE' ] ).
      ct_values[ name = 'GV_STATE' ]-value = CONV string( gv_state ).
    ELSE.
      INSERT VALUE #( name = 'GV_STATE' value = CONV string( gv_state ) ) INTO TABLE ct_values.
    ENDIF.
    IF lx_unwind IS BOUND.
      RAISE EXCEPTION lx_unwind.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_on_value_request.
    DATA ct_values TYPE zif_gg_dynpro_types_v1=>ty_values.
    ct_values = it_values.
    rt_values = io_session->get_compatibility( )->get_value_help_values( ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_on_help_request.
    DATA ct_values TYPE zif_gg_dynpro_types_v1=>ty_values.
    ct_values = it_values.
  ENDMETHOD.

  METHOD output_modules.
    CASE is_context-module.
      WHEN 'STATUS_0100'.
        IF go_container IS INITIAL.
          go_container = NEW #( container_name = 'CC_MAIN' ).
          form_create_editor( io_session = io_session ).
        ENDIF.
      WHEN OTHERS.
        RETURN.
    ENDCASE.
  ENDMETHOD.

  METHOD input_modules.
    CASE is_context-module.
      WHEN 'USER_COMMAND_0100'.
        CASE gv_ok_code.
          WHEN 'RESIZE'.
            gv_large = xsdbool( gv_large = abap_false ).
            IF gv_large = abap_true.
              go_editor->set_position( left   = 4
                                       top    = 4
                                       width  = 560
                                       height = 300 ).
            ELSE.
              go_editor->set_position( left   = 16
                                       top    = 12
                                       width  = 380
                                       height = 180 ).
            ENDIF.
            gv_state = 'Child geometry changed'.
          WHEN 'REPLACE'.
            go_editor->free( ).
            CLEAR go_editor.
            form_create_editor( io_session = io_session ).
        ENDCASE.
        CLEAR gv_ok_code.
      WHEN OTHERS.
        RETURN.
    ENDCASE.
  ENDMETHOD.

  METHOD zif_gg_resumable_v1~resume.
* Continuation states are explicit so unsupported suspension semantics remain visible.
    CASE is_resume-continuation-id.
      WHEN 'AFTER_0100'.
        RETURN.
      WHEN OTHERS.
        RETURN.
    ENDCASE.
  ENDMETHOD.

  METHOD form_create_editor.
    gv_generation = gv_generation + 1.
    go_editor = NEW #( parent = go_container ).
    go_editor->set_textstream( |Text editor in custom container CC_MAIN, generation { gv_generation }| ).
    gv_state = |Child created, generation { gv_generation }|.
  ENDMETHOD.

ENDCLASS.
