* Generated by open-abap-gui converter 0.1.0.
* Source object: ZGG_EX_159
* Source file: examples/zgg_ex_159.prog.abap
* Source SHA-256: 9d9bd81b46f9914667db39533d2747878046d9d422aa35535876be5350662d09
* Target class: ZCL_GG_EX_159
* Manifest schema: 1
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_159 DEFINITION PUBLIC FINAL CREATE PUBLIC FRIENDS zcl_gg_ex_159_h1.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_screen_provider_v1.
    INTERFACES zif_gg_transaction_v1.
    INTERFACES zif_gg_resumable_v1.

  PRIVATE SECTION.
    DATA go_container TYPE REF TO cl_gui_custom_container.
    DATA go_calendar TYPE REF TO cl_gui_calendar.
    DATA gt_events TYPE cntl_simple_events.
    DATA gv_ok_code TYPE sy-ucomm.
    DATA gv_week_begin TYPE d.
    DATA gv_week_end TYPE d.
    METHODS output_modules
      IMPORTING
        is_context TYPE zif_gg_dynpro_types_v1=>ty_module_context
        io_session TYPE REF TO zif_gg_session_v1
      CHANGING
        ct_values  TYPE zif_gg_dynpro_types_v1=>ty_values
        ct_states  TYPE zif_gg_dynpro_types_v1=>ty_states.
    METHODS input_modules
      IMPORTING
        is_context TYPE zif_gg_dynpro_types_v1=>ty_module_context
        io_session TYPE REF TO zif_gg_session_v1
      CHANGING
        ct_values  TYPE zif_gg_dynpro_types_v1=>ty_values.

ENDCLASS.

CLASS zcl_gg_ex_159 IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZGG_EX_159' description = 'Multi-month calendar' program = 'ZGG_EX_159' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'Multi-month calendar' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'Multi-month calendar' ).
    io_session->get_dialog( )->call_screen(
      is_call         = VALUE #( screen = '0100' )
      is_continuation = VALUE #( id = 'AFTER_0100' ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~get_initial_screen.
    rv_screen = '0100'.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~build_screens.
    io_builder->begin_screen( VALUE #( number = '0100' title = 'Multi-month calendar' next_screen = '0100' ok_code = 'GV_OK_CODE' width = 800 height = 644 ) ).
    io_builder->add_custom_control( VALUE #( control = VALUE #( name = 'CC_CALENDAR' position = VALUE #( row = 10 column = 5 width = 780 height = 312 ) ) resizing = VALUE #( vertical = abap_true min_height = 130 horizontal = abap_true min_width = 200 ) ) ).
    io_builder->add_pushbutton( VALUE #( control = VALUE #( name = 'BTN_THIS_YEAR' position = VALUE #( row = 348 column = 5 width = 100 height = 26 ) ) text = '2026' ucomm = 'THIS_YEAR' ) ).
    io_builder->add_pushbutton( VALUE #( control = VALUE #( name = 'BTN_NEXT_YEAR' position = VALUE #( row = 348 column = 115 width = 100 height = 26 ) ) text = '2027' ucomm = 'NEXT_YEAR' ) ).
    io_builder->add_pushbutton( VALUE #( control = VALUE #( name = 'BTN_CLEAR' position = VALUE #( row = 348 column = 225 width = 180 height = 26 ) ) text = 'Clear selection' ucomm = 'CLEAR' ) ).
    io_builder->add_text( VALUE #( control = VALUE #( name = 'LBL_WEEK' position = VALUE #( row = 400 column = 5 width = 50 height = 26 ) ) text = 'Week' ) ).
    io_builder->add_output_field( VALUE #( control = VALUE #( name = 'GV_WEEK_BEGIN' position = VALUE #( row = 400 column = 65 width = 100 height = 26 ) ) data_type = VALUE #( typ = 'D' length = 10 ) ) ).
    io_builder->add_text( VALUE #( control = VALUE #( name = 'LBL_TO' position = VALUE #( row = 400 column = 175 width = 20 height = 26 ) ) text = 'to' ) ).
    io_builder->add_output_field( VALUE #( control = VALUE #( name = 'GV_WEEK_END' position = VALUE #( row = 400 column = 205 width = 100 height = 26 ) ) data_type = VALUE #( typ = 'D' length = 10 ) ) ).
    io_builder->end_screen( ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~build_flow_logic.
    io_builder->begin_screen( '0100' ).
    io_builder->begin_pbo( ).
    io_builder->add_module( VALUE #( name = 'STATUS_0100' ) ).
    io_builder->end_processing( ).
    io_builder->begin_pai( ).
    io_builder->add_module( VALUE #( name = 'USER_COMMAND_0100' on_input = abap_true ) ).
    io_builder->end_processing( ).
    io_builder->end_screen( ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~initialization.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_WEEK_BEGIN' ] ).
      ct_values[ name = 'GV_WEEK_BEGIN' ]-value = CONV string( gv_week_begin ).
    ELSE.
      INSERT VALUE #( name = 'GV_WEEK_BEGIN' value = CONV string( gv_week_begin ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_WEEK_END' ] ).
      ct_values[ name = 'GV_WEEK_END' ]-value = CONV string( gv_week_end ).
    ELSE.
      INSERT VALUE #( name = 'GV_WEEK_END' value = CONV string( gv_week_end ) ) INTO TABLE ct_values.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_output_module.
    DATA lx_unwind TYPE REF TO zcx_gg_control_flow.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      gv_ok_code = CONV #( ct_values[ name = 'GV_OK_CODE' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_WEEK_BEGIN' ] ).
      gv_week_begin = CONV #( ct_values[ name = 'GV_WEEK_BEGIN' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_WEEK_END' ] ).
      gv_week_end = CONV #( ct_values[ name = 'GV_WEEK_END' ]-value ).
    ENDIF.
    TRY.
        output_modules(
          EXPORTING
            is_context = is_context
            io_session = io_session
          CHANGING
            ct_values  = ct_values
            ct_states  = ct_states ).
      CATCH zcx_gg_control_flow INTO lx_unwind.
    ENDTRY.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_WEEK_BEGIN' ] ).
      ct_values[ name = 'GV_WEEK_BEGIN' ]-value = CONV string( gv_week_begin ).
    ELSE.
      INSERT VALUE #( name = 'GV_WEEK_BEGIN' value = CONV string( gv_week_begin ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_WEEK_END' ] ).
      ct_values[ name = 'GV_WEEK_END' ]-value = CONV string( gv_week_end ).
    ELSE.
      INSERT VALUE #( name = 'GV_WEEK_END' value = CONV string( gv_week_end ) ) INTO TABLE ct_values.
    ENDIF.
    IF lx_unwind IS BOUND.
      RAISE EXCEPTION lx_unwind.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_input_module.
    DATA lx_unwind TYPE REF TO zcx_gg_control_flow.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      gv_ok_code = CONV #( ct_values[ name = 'GV_OK_CODE' ]-value ).
    ENDIF.
    TRY.
        input_modules(
          EXPORTING
            is_context = is_context
            io_session = io_session
          CHANGING
            ct_values  = ct_values ).
      CATCH zcx_gg_control_flow INTO lx_unwind.
    ENDTRY.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_WEEK_BEGIN' ] ).
      ct_values[ name = 'GV_WEEK_BEGIN' ]-value = CONV string( gv_week_begin ).
    ELSE.
      INSERT VALUE #( name = 'GV_WEEK_BEGIN' value = CONV string( gv_week_begin ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_WEEK_END' ] ).
      ct_values[ name = 'GV_WEEK_END' ]-value = CONV string( gv_week_end ).
    ELSE.
      INSERT VALUE #( name = 'GV_WEEK_END' value = CONV string( gv_week_end ) ) INTO TABLE ct_values.
    ENDIF.
    IF lx_unwind IS BOUND.
      RAISE EXCEPTION lx_unwind.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_on_value_request.
    DATA ct_values TYPE zif_gg_dynpro_types_v1=>ty_values.
    ct_values = it_values.
    rt_values = io_session->get_compatibility( )->get_value_help_values( ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_on_help_request.
    DATA ct_values TYPE zif_gg_dynpro_types_v1=>ty_values.
    ct_values = it_values.
    IF line_exists( ct_values[ name = 'GV_RESULT' ] ).
      rv_text = ct_values[ name = 'GV_RESULT' ]-value.
    ENDIF.
  ENDMETHOD.

  METHOD output_modules.
    CASE is_context-module.
      WHEN 'STATUS_0100'.
        IF go_container IS INITIAL.
          CREATE OBJECT go_container EXPORTING container_name = 'CC_CALENDAR'.
          CREATE OBJECT go_calendar EXPORTING parent          = go_container
                                              selection_style = cnca_sel_week
                                              focus_date      = '20260830'.
          gt_events = VALUE #( ( eventid = cl_gui_calendar=>m_id_date_selected appl_event = abap_true ) ).
          go_calendar->set_registered_events( gt_events ).
          zcl_gg_ex_159_h1=>go_owner = me.
          zcl_gg_ex_159_h1=>go_session = io_session.
          SET HANDLER zcl_gg_ex_159_h1=>on_date_selected FOR go_calendar.
        ENDIF.
      WHEN OTHERS.
        RETURN.
    ENDCASE.
  ENDMETHOD.

  METHOD input_modules.
    CASE is_context-module.
      WHEN 'USER_COMMAND_0100'.
        cl_gui_cfw=>dispatch( ).
        CASE gv_ok_code.
          WHEN 'NEXT_YEAR'.
            go_calendar->go_to_date( '20270830' ).
          WHEN 'THIS_YEAR'.
            go_calendar->go_to_date( '20260830' ).
          WHEN 'CLEAR'.
            go_calendar->reset_selection( ).
            CLEAR gv_week_begin.
            CLEAR gv_week_end.
        ENDCASE.
        CLEAR gv_ok_code.
      WHEN OTHERS.
        RETURN.
    ENDCASE.
  ENDMETHOD.

  METHOD zif_gg_resumable_v1~resume.
* Continuation states are explicit so unsupported suspension semantics remain visible.
    CASE is_resume-continuation-id.
      WHEN 'AFTER_0100'.
        RETURN.
      WHEN OTHERS.
        RETURN.
    ENDCASE.
  ENDMETHOD.

ENDCLASS.
