* Generated by open-abap-gui converter.
* Source object: ZGG_EX_026
* Source file: examples/zgg_ex_026.prog.abap
* Source SHA-256: f676cc4cafcb30906ad0905a6da0c007e7dca649271ed244f8b4cd942f4d6942
* Target class: ZCL_GG_EX_026
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_026 DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_transaction_v1.
    INTERFACES zif_gg_list_processing_v1.

  PRIVATE SECTION.
    DATA tab1 TYPE string.
    DATA tab2 TYPE string.
    DATA mv_active_tab TYPE string.
    DATA mv_p_active TYPE c LENGTH 1.
    DATA mv_p_city TYPE c LENGTH 20.
    DATA mv_p_count TYPE i.
    DATA mv_p_name TYPE c LENGTH 20.

ENDCLASS.

CLASS zcl_gg_ex_026 IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZGG_EX_026' description = 'Selection-screen tabbed block and tabs' program = 'ZGG_EX_026' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'Selection-screen tabbed block and tabs' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    ro_list_processing = me.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    io_builder->begin_tabbed_block( VALUE #( name = 'TB' lines = 10 ) ).
    io_builder->add_tab( VALUE #( name = 'TAB1' text = 'General' subscreen = '0100' ucomm = 'UT1' ) ).
    io_builder->add_tab( VALUE #( name = 'TAB2' text = 'Details' subscreen = '0200' ucomm = 'UT2' ) ).
    io_builder->end_tabbed_block( ).
    io_builder->begin_screen( VALUE #( number = '0100' as_subscreen = abap_true ) ).
    io_builder->add_parameter( VALUE #( name = 'P_NAME' text = 'Name' data_type = VALUE #( typ = 'C' length = 20 ) default = 'Ada Lovelace' ) ).
    io_builder->add_parameter( VALUE #( name = 'P_CITY' text = 'City' data_type = VALUE #( typ = 'C' length = 20 ) default = 'London' ) ).
    io_builder->end_screen( ).
    io_builder->begin_screen( VALUE #( number = '0200' as_subscreen = abap_true ) ).
    io_builder->add_parameter( VALUE #( name = 'P_COUNT' text = 'Count' data_type = VALUE #( typ = 'I' ) default = '3' ) ).
    io_builder->add_checkbox( VALUE #( name = 'P_ACTIVE' text = 'Active' default = abap_true ) ).
    io_builder->end_screen( ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    mv_p_active = ct_values[ name = 'P_ACTIVE' ]-value.
    mv_p_city = ct_values[ name = 'P_CITY' ]-value.
    mv_p_count = ct_values[ name = 'P_COUNT' ]-value.
    mv_p_name = ct_values[ name = 'P_NAME' ]-value.
    tab1 = 'General'.
    tab2 = 'Details'.
    IF ct_values[ name = 'P_ACTIVE' ]-value <> mv_p_active.
      ct_values[ name = 'P_ACTIVE' ]-value = |{ mv_p_active }|.
    ENDIF.
    IF ct_values[ name = 'P_CITY' ]-value <> mv_p_city.
      ct_values[ name = 'P_CITY' ]-value = |{ mv_p_city }|.
    ENDIF.
    IF ct_values[ name = 'P_COUNT' ]-value <> mv_p_count.
      ct_values[ name = 'P_COUNT' ]-value = |{ mv_p_count }|.
    ENDIF.
    IF ct_values[ name = 'P_NAME' ]-value <> mv_p_name.
      ct_values[ name = 'P_NAME' ]-value = |{ mv_p_name }|.
    ENDIF.
    ct_values[ name = 'TAB1' ]-value = tab1.
    ct_values[ name = 'TAB2' ]-value = tab2.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    mv_p_active = ct_values[ name = 'P_ACTIVE' ]-value.
    mv_p_city = ct_values[ name = 'P_CITY' ]-value.
    mv_p_count = ct_values[ name = 'P_COUNT' ]-value.
    mv_p_name = ct_values[ name = 'P_NAME' ]-value.
    IF ct_values[ name = 'P_ACTIVE' ]-value <> mv_p_active.
      ct_values[ name = 'P_ACTIVE' ]-value = |{ mv_p_active }|.
    ENDIF.
    IF ct_values[ name = 'P_CITY' ]-value <> mv_p_city.
      ct_values[ name = 'P_CITY' ]-value = |{ mv_p_city }|.
    ENDIF.
    IF ct_values[ name = 'P_COUNT' ]-value <> mv_p_count.
      ct_values[ name = 'P_COUNT' ]-value = |{ mv_p_count }|.
    ENDIF.
    IF ct_values[ name = 'P_NAME' ]-value <> mv_p_name.
      ct_values[ name = 'P_NAME' ]-value = |{ mv_p_name }|.
    ENDIF.
    ct_values[ name = 'TAB1' ]-value = tab1.
    ct_values[ name = 'TAB2' ]-value = tab2.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    IF iv_ucomm = 'UT1' OR iv_ucomm = 'UT2'.
      mv_active_tab = iv_ucomm.
    ENDIF.
    mv_p_active = ct_values[ name = 'P_ACTIVE' ]-value.
    mv_p_city = ct_values[ name = 'P_CITY' ]-value.
    mv_p_count = ct_values[ name = 'P_COUNT' ]-value.
    mv_p_name = ct_values[ name = 'P_NAME' ]-value.
    IF ct_values[ name = 'P_ACTIVE' ]-value <> mv_p_active.
      ct_values[ name = 'P_ACTIVE' ]-value = |{ mv_p_active }|.
    ENDIF.
    IF ct_values[ name = 'P_CITY' ]-value <> mv_p_city.
      ct_values[ name = 'P_CITY' ]-value = |{ mv_p_city }|.
    ENDIF.
    IF ct_values[ name = 'P_COUNT' ]-value <> mv_p_count.
      ct_values[ name = 'P_COUNT' ]-value = |{ mv_p_count }|.
    ENDIF.
    IF ct_values[ name = 'P_NAME' ]-value <> mv_p_name.
      ct_values[ name = 'P_NAME' ]-value = |{ mv_p_name }|.
    ENDIF.
    ct_values[ name = 'TAB1' ]-value = tab1.
    ct_values[ name = 'TAB2' ]-value = tab2.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    mv_p_active = ct_values[ name = 'P_ACTIVE' ]-value.
    mv_p_city = ct_values[ name = 'P_CITY' ]-value.
    mv_p_count = ct_values[ name = 'P_COUNT' ]-value.
    mv_p_name = ct_values[ name = 'P_NAME' ]-value.
    IF ct_values[ name = 'P_ACTIVE' ]-value <> mv_p_active.
      ct_values[ name = 'P_ACTIVE' ]-value = |{ mv_p_active }|.
    ENDIF.
    IF ct_values[ name = 'P_CITY' ]-value <> mv_p_city.
      ct_values[ name = 'P_CITY' ]-value = |{ mv_p_city }|.
    ENDIF.
    IF ct_values[ name = 'P_COUNT' ]-value <> mv_p_count.
      ct_values[ name = 'P_COUNT' ]-value = |{ mv_p_count }|.
    ENDIF.
    IF ct_values[ name = 'P_NAME' ]-value <> mv_p_name.
      ct_values[ name = 'P_NAME' ]-value = |{ mv_p_name }|.
    ENDIF.
    ct_values[ name = 'TAB1' ]-value = tab1.
    ct_values[ name = 'TAB2' ]-value = tab2.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    mv_p_active = ct_values[ name = 'P_ACTIVE' ]-value.
    mv_p_city = ct_values[ name = 'P_CITY' ]-value.
    mv_p_count = ct_values[ name = 'P_COUNT' ]-value.
    mv_p_name = ct_values[ name = 'P_NAME' ]-value.
    IF ct_values[ name = 'P_ACTIVE' ]-value <> mv_p_active.
      ct_values[ name = 'P_ACTIVE' ]-value = |{ mv_p_active }|.
    ENDIF.
    IF ct_values[ name = 'P_CITY' ]-value <> mv_p_city.
      ct_values[ name = 'P_CITY' ]-value = |{ mv_p_city }|.
    ENDIF.
    IF ct_values[ name = 'P_COUNT' ]-value <> mv_p_count.
      ct_values[ name = 'P_COUNT' ]-value = |{ mv_p_count }|.
    ENDIF.
    IF ct_values[ name = 'P_NAME' ]-value <> mv_p_name.
      ct_values[ name = 'P_NAME' ]-value = |{ mv_p_name }|.
    ENDIF.
    ct_values[ name = 'TAB1' ]-value = tab1.
    ct_values[ name = 'TAB2' ]-value = tab2.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    mv_p_active = ct_values[ name = 'P_ACTIVE' ]-value.
    mv_p_city = ct_values[ name = 'P_CITY' ]-value.
    mv_p_count = ct_values[ name = 'P_COUNT' ]-value.
    mv_p_name = ct_values[ name = 'P_NAME' ]-value.
    IF ct_values[ name = 'P_ACTIVE' ]-value <> mv_p_active.
      ct_values[ name = 'P_ACTIVE' ]-value = |{ mv_p_active }|.
    ENDIF.
    IF ct_values[ name = 'P_CITY' ]-value <> mv_p_city.
      ct_values[ name = 'P_CITY' ]-value = |{ mv_p_city }|.
    ENDIF.
    IF ct_values[ name = 'P_COUNT' ]-value <> mv_p_count.
      ct_values[ name = 'P_COUNT' ]-value = |{ mv_p_count }|.
    ENDIF.
    IF ct_values[ name = 'P_NAME' ]-value <> mv_p_name.
      ct_values[ name = 'P_NAME' ]-value = |{ mv_p_name }|.
    ENDIF.
    ct_values[ name = 'TAB1' ]-value = tab1.
    ct_values[ name = 'TAB2' ]-value = tab2.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    mv_p_active = ct_values[ name = 'P_ACTIVE' ]-value.
    mv_p_city = ct_values[ name = 'P_CITY' ]-value.
    mv_p_count = ct_values[ name = 'P_COUNT' ]-value.
    mv_p_name = ct_values[ name = 'P_NAME' ]-value.
    IF ct_values[ name = 'P_ACTIVE' ]-value <> mv_p_active.
      ct_values[ name = 'P_ACTIVE' ]-value = |{ mv_p_active }|.
    ENDIF.
    IF ct_values[ name = 'P_CITY' ]-value <> mv_p_city.
      ct_values[ name = 'P_CITY' ]-value = |{ mv_p_city }|.
    ENDIF.
    IF ct_values[ name = 'P_COUNT' ]-value <> mv_p_count.
      ct_values[ name = 'P_COUNT' ]-value = |{ mv_p_count }|.
    ENDIF.
    IF ct_values[ name = 'P_NAME' ]-value <> mv_p_name.
      ct_values[ name = 'P_NAME' ]-value = |{ mv_p_name }|.
    ENDIF.
    ct_values[ name = 'TAB1' ]-value = tab1.
    ct_values[ name = 'TAB2' ]-value = tab2.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    mv_p_active = it_values[ name = 'P_ACTIVE' ]-value.
    mv_p_city = it_values[ name = 'P_CITY' ]-value.
    mv_p_count = it_values[ name = 'P_COUNT' ]-value.
    mv_p_name = it_values[ name = 'P_NAME' ]-value.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'Selection-screen tabbed block and tabs' ).
    DATA(lo_writer) = io_session->get_list( )->get_writer( ).
    mv_p_active = it_values[ name = 'P_ACTIVE' ]-value.
    mv_p_city = it_values[ name = 'P_CITY' ]-value.
    mv_p_count = it_values[ name = 'P_COUNT' ]-value.
    mv_p_name = it_values[ name = 'P_NAME' ]-value.
    lo_writer->write_field( VALUE #( text = 'Name:' placement = VALUE #( new_line = abap_true ) ) ).
    lo_writer->write_field( VALUE #( text = |{ mv_p_name }| ) ).
    lo_writer->write_field( VALUE #( text = 'City:' placement = VALUE #( new_line = abap_true ) ) ).
    lo_writer->write_field( VALUE #( text = |{ mv_p_city }| ) ).
    lo_writer->write_field( VALUE #( text = 'Count:' placement = VALUE #( new_line = abap_true ) ) ).
    lo_writer->write_field( VALUE #( text = |{ mv_p_count }| ) ).
    IF mv_p_active = abap_true.
      lo_writer->write_field( VALUE #( text = 'Active' placement = VALUE #( new_line = abap_true ) ) ).
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    mv_p_active = it_values[ name = 'P_ACTIVE' ]-value.
    mv_p_city = it_values[ name = 'P_CITY' ]-value.
    mv_p_count = it_values[ name = 'P_COUNT' ]-value.
    mv_p_name = it_values[ name = 'P_NAME' ]-value.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~get_settings.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~end_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page_during_line_sel.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_line_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_user_command.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_pf.
    RETURN.
  ENDMETHOD.

ENDCLASS.
