* Generated by open-abap-gui converter.
* Source object: ZGG_EX_070
* Source file: examples/zgg_ex_070.prog.abap
* Source SHA-256: d99973de176de59f891a95a75d901c487c685a756a1554f11248349cdf1d60a6
* Target class: ZCL_GG_EX_070
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_070 DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_transaction_v1.
    INTERFACES zif_gg_list_processing_v1.

  PRIVATE SECTION.
    DATA mv_p_all TYPE c LENGTH 1.
    DATA mv_p_allv TYPE c LENGTH 20.
    DATA mv_p_one TYPE c LENGTH 1.
    DATA mv_p_onev TYPE c LENGTH 20.
    DATA mv_p_req TYPE c LENGTH 20.

ENDCLASS.

CLASS zcl_gg_ex_070 IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZGG_EX_070' description = 'Radio-driven blocks and validation' program = 'ZGG_EX_070' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'Radio-driven blocks and validation' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    ro_list_processing = me.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    io_builder->add_radiobutton( VALUE #( name = 'P_ALL' text = 'All flights' radio_group = 'G1' default = abap_true ucomm = 'BRANCH' ) ).
    io_builder->add_radiobutton( VALUE #( name = 'P_ONE' text = 'One flight' radio_group = 'G1' ucomm = 'BRANCH' ) ).
    io_builder->begin_block( VALUE #( name = 'B_ALL' title = 'All flights' with_frame = abap_true ) ).
    io_builder->add_parameter( VALUE #( name = 'P_ALLV' text = 'All value' data_type = VALUE #( typ = 'C' length = 20 ) modif_id = 'ALL' ) ).
    io_builder->end_block( ).
    io_builder->begin_block( VALUE #( name = 'B_ONE' title = 'One flight' with_frame = abap_true ) ).
    io_builder->add_parameter( VALUE #( name = 'P_ONEV' text = 'One value' data_type = VALUE #( typ = 'C' length = 20 ) modif_id = 'ONE' ) ).
    io_builder->end_block( ).
    io_builder->add_parameter( VALUE #( name = 'P_REQ' text = 'Required value' data_type = VALUE #( typ = 'C' length = 20 ) obligatory = abap_true ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    mv_p_all = ct_values[ name = 'P_ALL' ]-value.
    mv_p_allv = ct_values[ name = 'P_ALLV' ]-value.
    mv_p_one = ct_values[ name = 'P_ONE' ]-value.
    mv_p_onev = ct_values[ name = 'P_ONEV' ]-value.
    mv_p_req = ct_values[ name = 'P_REQ' ]-value.
    IF ct_values[ name = 'P_ALL' ]-value <> mv_p_all.
      ct_values[ name = 'P_ALL' ]-value = |{ mv_p_all }|.
    ENDIF.
    IF ct_values[ name = 'P_ALLV' ]-value <> mv_p_allv.
      ct_values[ name = 'P_ALLV' ]-value = |{ mv_p_allv }|.
    ENDIF.
    IF ct_values[ name = 'P_ONE' ]-value <> mv_p_one.
      ct_values[ name = 'P_ONE' ]-value = |{ mv_p_one }|.
    ENDIF.
    IF ct_values[ name = 'P_ONEV' ]-value <> mv_p_onev.
      ct_values[ name = 'P_ONEV' ]-value = |{ mv_p_onev }|.
    ENDIF.
    IF ct_values[ name = 'P_REQ' ]-value <> mv_p_req.
      ct_values[ name = 'P_REQ' ]-value = |{ mv_p_req }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    mv_p_all = ct_values[ name = 'P_ALL' ]-value.
    mv_p_allv = ct_values[ name = 'P_ALLV' ]-value.
    mv_p_one = ct_values[ name = 'P_ONE' ]-value.
    mv_p_onev = ct_values[ name = 'P_ONEV' ]-value.
    mv_p_req = ct_values[ name = 'P_REQ' ]-value.
    LOOP AT ct_states ASSIGNING FIELD-SYMBOL(<ls_state>).
      CASE <ls_state>-modif_id.
        WHEN 'ALL'.
          <ls_state>-visible = xsdbool( mv_p_all = abap_true ).
* SCREEN state is already changed through <ls_state>.
        WHEN 'ONE'.
          <ls_state>-visible = xsdbool( mv_p_one = abap_true ).
* SCREEN state is already changed through <ls_state>.
      ENDCASE.
    ENDLOOP.
    IF ct_values[ name = 'P_ALL' ]-value <> mv_p_all.
      ct_values[ name = 'P_ALL' ]-value = |{ mv_p_all }|.
    ENDIF.
    IF ct_values[ name = 'P_ALLV' ]-value <> mv_p_allv.
      ct_values[ name = 'P_ALLV' ]-value = |{ mv_p_allv }|.
    ENDIF.
    IF ct_values[ name = 'P_ONE' ]-value <> mv_p_one.
      ct_values[ name = 'P_ONE' ]-value = |{ mv_p_one }|.
    ENDIF.
    IF ct_values[ name = 'P_ONEV' ]-value <> mv_p_onev.
      ct_values[ name = 'P_ONEV' ]-value = |{ mv_p_onev }|.
    ENDIF.
    IF ct_values[ name = 'P_REQ' ]-value <> mv_p_req.
      ct_values[ name = 'P_REQ' ]-value = |{ mv_p_req }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    mv_p_all = ct_values[ name = 'P_ALL' ]-value.
    mv_p_allv = ct_values[ name = 'P_ALLV' ]-value.
    mv_p_one = ct_values[ name = 'P_ONE' ]-value.
    mv_p_onev = ct_values[ name = 'P_ONEV' ]-value.
    mv_p_req = ct_values[ name = 'P_REQ' ]-value.
    IF ct_values[ name = 'P_ALL' ]-value <> mv_p_all.
      ct_values[ name = 'P_ALL' ]-value = |{ mv_p_all }|.
    ENDIF.
    IF ct_values[ name = 'P_ALLV' ]-value <> mv_p_allv.
      ct_values[ name = 'P_ALLV' ]-value = |{ mv_p_allv }|.
    ENDIF.
    IF ct_values[ name = 'P_ONE' ]-value <> mv_p_one.
      ct_values[ name = 'P_ONE' ]-value = |{ mv_p_one }|.
    ENDIF.
    IF ct_values[ name = 'P_ONEV' ]-value <> mv_p_onev.
      ct_values[ name = 'P_ONEV' ]-value = |{ mv_p_onev }|.
    ENDIF.
    IF ct_values[ name = 'P_REQ' ]-value <> mv_p_req.
      ct_values[ name = 'P_REQ' ]-value = |{ mv_p_req }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    mv_p_all = ct_values[ name = 'P_ALL' ]-value.
    mv_p_allv = ct_values[ name = 'P_ALLV' ]-value.
    mv_p_one = ct_values[ name = 'P_ONE' ]-value.
    mv_p_onev = ct_values[ name = 'P_ONEV' ]-value.
    mv_p_req = ct_values[ name = 'P_REQ' ]-value.
    IF ct_values[ name = 'P_ALL' ]-value <> mv_p_all.
      ct_values[ name = 'P_ALL' ]-value = |{ mv_p_all }|.
    ENDIF.
    IF ct_values[ name = 'P_ALLV' ]-value <> mv_p_allv.
      ct_values[ name = 'P_ALLV' ]-value = |{ mv_p_allv }|.
    ENDIF.
    IF ct_values[ name = 'P_ONE' ]-value <> mv_p_one.
      ct_values[ name = 'P_ONE' ]-value = |{ mv_p_one }|.
    ENDIF.
    IF ct_values[ name = 'P_ONEV' ]-value <> mv_p_onev.
      ct_values[ name = 'P_ONEV' ]-value = |{ mv_p_onev }|.
    ENDIF.
    IF ct_values[ name = 'P_REQ' ]-value <> mv_p_req.
      ct_values[ name = 'P_REQ' ]-value = |{ mv_p_req }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    mv_p_all = ct_values[ name = 'P_ALL' ]-value.
    mv_p_allv = ct_values[ name = 'P_ALLV' ]-value.
    mv_p_one = ct_values[ name = 'P_ONE' ]-value.
    mv_p_onev = ct_values[ name = 'P_ONEV' ]-value.
    mv_p_req = ct_values[ name = 'P_REQ' ]-value.
    IF ct_values[ name = 'P_ALL' ]-value <> mv_p_all.
      ct_values[ name = 'P_ALL' ]-value = |{ mv_p_all }|.
    ENDIF.
    IF ct_values[ name = 'P_ALLV' ]-value <> mv_p_allv.
      ct_values[ name = 'P_ALLV' ]-value = |{ mv_p_allv }|.
    ENDIF.
    IF ct_values[ name = 'P_ONE' ]-value <> mv_p_one.
      ct_values[ name = 'P_ONE' ]-value = |{ mv_p_one }|.
    ENDIF.
    IF ct_values[ name = 'P_ONEV' ]-value <> mv_p_onev.
      ct_values[ name = 'P_ONEV' ]-value = |{ mv_p_onev }|.
    ENDIF.
    IF ct_values[ name = 'P_REQ' ]-value <> mv_p_req.
      ct_values[ name = 'P_REQ' ]-value = |{ mv_p_req }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    IF iv_block = 'B_ALL'.
      mv_p_all = ct_values[ name = 'P_ALL' ]-value.
      mv_p_allv = ct_values[ name = 'P_ALLV' ]-value.
      mv_p_one = ct_values[ name = 'P_ONE' ]-value.
      mv_p_onev = ct_values[ name = 'P_ONEV' ]-value.
      mv_p_req = ct_values[ name = 'P_REQ' ]-value.
      IF mv_p_all = abap_true AND mv_p_allv IS INITIAL AND io_session->get_context( )-selection-ucomm = 'ONLI'.
        io_session->message( VALUE #( type = zif_gg_session_types_v1=>message_type_error text = 'Enter a value for all flights' ) ).
      ENDIF.
      IF ct_values[ name = 'P_ALL' ]-value <> mv_p_all.
        ct_values[ name = 'P_ALL' ]-value = |{ mv_p_all }|.
      ENDIF.
      IF ct_values[ name = 'P_ALLV' ]-value <> mv_p_allv.
        ct_values[ name = 'P_ALLV' ]-value = |{ mv_p_allv }|.
      ENDIF.
      IF ct_values[ name = 'P_ONE' ]-value <> mv_p_one.
        ct_values[ name = 'P_ONE' ]-value = |{ mv_p_one }|.
      ENDIF.
      IF ct_values[ name = 'P_ONEV' ]-value <> mv_p_onev.
        ct_values[ name = 'P_ONEV' ]-value = |{ mv_p_onev }|.
      ENDIF.
      IF ct_values[ name = 'P_REQ' ]-value <> mv_p_req.
        ct_values[ name = 'P_REQ' ]-value = |{ mv_p_req }|.
      ENDIF.
    ENDIF.
    IF iv_block = 'B_ONE'.
      mv_p_all = ct_values[ name = 'P_ALL' ]-value.
      mv_p_allv = ct_values[ name = 'P_ALLV' ]-value.
      mv_p_one = ct_values[ name = 'P_ONE' ]-value.
      mv_p_onev = ct_values[ name = 'P_ONEV' ]-value.
      mv_p_req = ct_values[ name = 'P_REQ' ]-value.
      IF mv_p_one = abap_true AND mv_p_onev IS INITIAL AND io_session->get_context( )-selection-ucomm = 'ONLI'.
        io_session->message( VALUE #( type = zif_gg_session_types_v1=>message_type_error text = 'Enter a value for one flight' ) ).
      ENDIF.
      IF ct_values[ name = 'P_ALL' ]-value <> mv_p_all.
        ct_values[ name = 'P_ALL' ]-value = |{ mv_p_all }|.
      ENDIF.
      IF ct_values[ name = 'P_ALLV' ]-value <> mv_p_allv.
        ct_values[ name = 'P_ALLV' ]-value = |{ mv_p_allv }|.
      ENDIF.
      IF ct_values[ name = 'P_ONE' ]-value <> mv_p_one.
        ct_values[ name = 'P_ONE' ]-value = |{ mv_p_one }|.
      ENDIF.
      IF ct_values[ name = 'P_ONEV' ]-value <> mv_p_onev.
        ct_values[ name = 'P_ONEV' ]-value = |{ mv_p_onev }|.
      ENDIF.
      IF ct_values[ name = 'P_REQ' ]-value <> mv_p_req.
        ct_values[ name = 'P_REQ' ]-value = |{ mv_p_req }|.
      ENDIF.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    mv_p_all = ct_values[ name = 'P_ALL' ]-value.
    mv_p_allv = ct_values[ name = 'P_ALLV' ]-value.
    mv_p_one = ct_values[ name = 'P_ONE' ]-value.
    mv_p_onev = ct_values[ name = 'P_ONEV' ]-value.
    mv_p_req = ct_values[ name = 'P_REQ' ]-value.
    IF ct_values[ name = 'P_ALL' ]-value <> mv_p_all.
      ct_values[ name = 'P_ALL' ]-value = |{ mv_p_all }|.
    ENDIF.
    IF ct_values[ name = 'P_ALLV' ]-value <> mv_p_allv.
      ct_values[ name = 'P_ALLV' ]-value = |{ mv_p_allv }|.
    ENDIF.
    IF ct_values[ name = 'P_ONE' ]-value <> mv_p_one.
      ct_values[ name = 'P_ONE' ]-value = |{ mv_p_one }|.
    ENDIF.
    IF ct_values[ name = 'P_ONEV' ]-value <> mv_p_onev.
      ct_values[ name = 'P_ONEV' ]-value = |{ mv_p_onev }|.
    ENDIF.
    IF ct_values[ name = 'P_REQ' ]-value <> mv_p_req.
      ct_values[ name = 'P_REQ' ]-value = |{ mv_p_req }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    mv_p_all = it_values[ name = 'P_ALL' ]-value.
    mv_p_allv = it_values[ name = 'P_ALLV' ]-value.
    mv_p_one = it_values[ name = 'P_ONE' ]-value.
    mv_p_onev = it_values[ name = 'P_ONEV' ]-value.
    mv_p_req = it_values[ name = 'P_REQ' ]-value.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'Radio-driven blocks and validation' ).
    DATA(lo_writer) = io_session->get_list( )->get_writer( ).
    mv_p_all = it_values[ name = 'P_ALL' ]-value.
    mv_p_allv = it_values[ name = 'P_ALLV' ]-value.
    mv_p_one = it_values[ name = 'P_ONE' ]-value.
    mv_p_onev = it_values[ name = 'P_ONEV' ]-value.
    mv_p_req = it_values[ name = 'P_REQ' ]-value.
    IF mv_p_one = abap_true.
      lo_writer->write_field( VALUE #( text = |{ mv_p_onev }| ) ).
    ELSE.
      lo_writer->write_field( VALUE #( text = |{ mv_p_allv }| ) ).
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    mv_p_all = it_values[ name = 'P_ALL' ]-value.
    mv_p_allv = it_values[ name = 'P_ALLV' ]-value.
    mv_p_one = it_values[ name = 'P_ONE' ]-value.
    mv_p_onev = it_values[ name = 'P_ONEV' ]-value.
    mv_p_req = it_values[ name = 'P_REQ' ]-value.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~get_settings.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~end_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page_during_line_sel.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_line_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_user_command.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_pf.
    RETURN.
  ENDMETHOD.

ENDCLASS.
