* Generated by open-abap-gui converter.
* Source object: ZGG_EX_012
* Source file: examples/zgg_ex_012.prog.abap
* Source SHA-256: 71d8676355d77554a4a58fb0c624f2ce170b1a7eb5cb4d8f5fc9726d25ef5bab
* Target class: ZCL_GG_EX_012
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_012 DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_transaction_v1.
    INTERFACES zif_gg_list_processing_v1.

  PRIVATE SECTION.
    DATA mv_p_date TYPE d.

ENDCLASS.

CLASS zcl_gg_ex_012 IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZGG_EX_012' description = 'INITIALIZATION' program = 'ZGG_EX_012' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'INITIALIZATION' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    ro_list_processing = me.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    io_builder->add_parameter( VALUE #( name = 'P_DATE' text = 'Date' data_type = VALUE #( typ = 'D' length = 8 ) ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    mv_p_date = ct_values[ name = 'P_DATE' ]-value.
    mv_p_date = '20260101'.
    IF ct_values[ name = 'P_DATE' ]-value <> mv_p_date.
      ct_values[ name = 'P_DATE' ]-value = |{ mv_p_date }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    mv_p_date = ct_values[ name = 'P_DATE' ]-value.
    IF ct_values[ name = 'P_DATE' ]-value <> mv_p_date.
      ct_values[ name = 'P_DATE' ]-value = |{ mv_p_date }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    mv_p_date = ct_values[ name = 'P_DATE' ]-value.
    IF ct_values[ name = 'P_DATE' ]-value <> mv_p_date.
      ct_values[ name = 'P_DATE' ]-value = |{ mv_p_date }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    mv_p_date = ct_values[ name = 'P_DATE' ]-value.
    IF ct_values[ name = 'P_DATE' ]-value <> mv_p_date.
      ct_values[ name = 'P_DATE' ]-value = |{ mv_p_date }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    mv_p_date = ct_values[ name = 'P_DATE' ]-value.
    IF ct_values[ name = 'P_DATE' ]-value <> mv_p_date.
      ct_values[ name = 'P_DATE' ]-value = |{ mv_p_date }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    mv_p_date = ct_values[ name = 'P_DATE' ]-value.
    IF ct_values[ name = 'P_DATE' ]-value <> mv_p_date.
      ct_values[ name = 'P_DATE' ]-value = |{ mv_p_date }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    mv_p_date = ct_values[ name = 'P_DATE' ]-value.
    IF ct_values[ name = 'P_DATE' ]-value <> mv_p_date.
      ct_values[ name = 'P_DATE' ]-value = |{ mv_p_date }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    mv_p_date = it_values[ name = 'P_DATE' ]-value.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'INITIALIZATION' ).
    DATA(lo_writer) = io_session->get_list( )->get_writer( ).
    mv_p_date = it_values[ name = 'P_DATE' ]-value.
    lo_writer->write_field( VALUE #( text = lo_writer->format_value( iv_value = mv_p_date ) ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    mv_p_date = it_values[ name = 'P_DATE' ]-value.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~get_settings.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~end_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page_during_line_sel.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_line_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_user_command.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_pf.
    RETURN.
  ENDMETHOD.

ENDCLASS.
