* Generated by open-abap-gui converter.
* Source object: ZGG_EX_099
* Source file: examples/zgg_ex_099.prog.abap
* Source SHA-256: 27f1dedba65a31cd9f873d31e66ca9d0b61aa0774190c569a11a2099731c50ab
* Target class: ZCL_GG_EX_099
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_099 DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_screen_provider_v1.
    INTERFACES zif_gg_transaction_v1.
    INTERFACES zif_gg_list_processing_v1.
    INTERFACES zif_gg_resumable_v1.

  PRIVATE SECTION.
    DATA gv_ok_code TYPE sy-ucomm.
    DATA gv_input TYPE c LENGTH 30 VALUE 'input'.
    DATA gv_output TYPE c LENGTH 40 VALUE 'output'.
    DATA gv_check TYPE c LENGTH 1 VALUE 'X'.
    DATA gv_alpha TYPE c LENGTH 1 VALUE 'X'.
    DATA gv_beta TYPE c LENGTH 1.
    DATA gv_list TYPE c LENGTH 10 VALUE 'A'.
    DATA gt_values TYPE vrm_values.
    METHODS output_modules
      IMPORTING
        is_context TYPE zif_gg_dynpro_types_v1=>ty_module_context
        io_session TYPE REF TO zif_gg_session_v1
      CHANGING
        ct_values  TYPE zif_gg_dynpro_types_v1=>ty_values
        ct_states  TYPE zif_gg_dynpro_types_v1=>ty_states.
    METHODS input_modules
      IMPORTING
        is_context TYPE zif_gg_dynpro_types_v1=>ty_module_context
        io_session TYPE REF TO zif_gg_session_v1
      CHANGING
        ct_values  TYPE zif_gg_dynpro_types_v1=>ty_values.

ENDCLASS.

CLASS zcl_gg_ex_099 IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZGG_EX_099' description = 'Basic dynpro controls' program = 'ZGG_EX_099' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'Basic dynpro controls' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    ro_list_processing = me.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'Basic dynpro controls' ).
    io_session->get_dialog( )->call_screen(
      is_call         = VALUE #( screen = '0100' )
      is_continuation = VALUE #( id = 'AFTER_0100' ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~get_initial_screen.
    rv_screen = '0100'.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~build_screens.
    io_builder->begin_screen( VALUE #( number = '0100' title = 'Basic dynpro controls' next_screen = '0100' ok_code = 'GV_OK_CODE' width = 800 height = 644 ) ).
    io_builder->add_box( VALUE #( control = VALUE #( name = 'FRAME_CONTROLS' position = VALUE #( row = 10 column = 5 width = 600 height = 260 ) ) text = 'All basic dynpro controls' ) ).
    io_builder->add_text( VALUE #( control = VALUE #( name = 'LBL_INPUT' position = VALUE #( row = 36 column = 25 width = 100 height = 26 ) ) text = 'Input' ) ).
    io_builder->add_input_field( VALUE #( control = VALUE #( name = 'GV_INPUT' position = VALUE #( row = 36 column = 145 width = 300 height = 26 ) ) data_type = VALUE #( typ = 'C' length = 30 ) ) ).
    io_builder->add_text( VALUE #( control = VALUE #( name = 'LBL_OUTPUT' position = VALUE #( row = 62 column = 25 width = 100 height = 26 ) ) text = 'Output' ) ).
    io_builder->add_output_field( VALUE #( control = VALUE #( name = 'GV_OUTPUT' position = VALUE #( row = 62 column = 145 width = 400 height = 26 ) ) data_type = VALUE #( typ = 'C' length = 40 ) ) ).
    io_builder->add_checkbox( VALUE #( control = VALUE #( name = 'GV_CHECK' position = VALUE #( row = 88 column = 25 width = 120 height = 26 ) ) text = 'Enabled' ) ).
    io_builder->add_radiobutton( VALUE #( control = VALUE #( name = 'GV_ALPHA' position = VALUE #( row = 114 column = 25 width = 100 height = 26 ) ) text = 'Alpha' group = 'G001' ) ).
    io_builder->add_radiobutton( VALUE #( control = VALUE #( name = 'GV_BETA' position = VALUE #( row = 140 column = 25 width = 100 height = 26 ) ) text = 'Beta' group = 'G001' ) ).
    io_builder->add_text( VALUE #( control = VALUE #( name = 'LBL_LIST' position = VALUE #( row = 166 column = 25 width = 100 height = 26 ) ) text = 'Choice' ) ).
    io_builder->add_listbox( VALUE #( control = VALUE #( name = 'GV_LIST' position = VALUE #( row = 166 column = 145 width = 150 height = 26 ) ) data_type = VALUE #( typ = 'C' length = 10 ) ) ).
    io_builder->add_pushbutton( VALUE #( control = VALUE #( name = 'BTN_APPLY' position = VALUE #( row = 218 column = 25 width = 100 height = 26 ) ) text = 'Apply' ucomm = 'APPLY' ) ).
    io_builder->end_screen( ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~build_flow_logic.
    io_builder->begin_screen( '0100' ).
    io_builder->begin_pbo( ).
    io_builder->add_module( VALUE #( name = 'STATUS_0100' ) ).
    io_builder->end_processing( ).
    io_builder->begin_pai( ).
    io_builder->add_module( VALUE #( name = 'EXIT_0100' on_input = abap_true at_exit_command = abap_true ) ).
    io_builder->add_module( VALUE #( name = 'USER_COMMAND_0100' on_input = abap_true ) ).
    io_builder->end_processing( ).
    io_builder->end_screen( ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~initialization.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_INPUT' ] ).
      ct_values[ name = 'GV_INPUT' ]-value = CONV string( gv_input ).
    ELSE.
      INSERT VALUE #( name = 'GV_INPUT' value = CONV string( gv_input ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_OUTPUT' ] ).
      ct_values[ name = 'GV_OUTPUT' ]-value = CONV string( gv_output ).
    ELSE.
      INSERT VALUE #( name = 'GV_OUTPUT' value = CONV string( gv_output ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_CHECK' ] ).
      ct_values[ name = 'GV_CHECK' ]-value = CONV string( gv_check ).
    ELSE.
      INSERT VALUE #( name = 'GV_CHECK' value = CONV string( gv_check ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_ALPHA' ] ).
      ct_values[ name = 'GV_ALPHA' ]-value = CONV string( gv_alpha ).
    ELSE.
      INSERT VALUE #( name = 'GV_ALPHA' value = CONV string( gv_alpha ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_BETA' ] ).
      ct_values[ name = 'GV_BETA' ]-value = CONV string( gv_beta ).
    ELSE.
      INSERT VALUE #( name = 'GV_BETA' value = CONV string( gv_beta ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_LIST' ] ).
      ct_values[ name = 'GV_LIST' ]-value = CONV string( gv_list ).
    ELSE.
      INSERT VALUE #( name = 'GV_LIST' value = CONV string( gv_list ) ) INTO TABLE ct_values.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_output_module.
    DATA lx_unwind TYPE REF TO zcx_gg_control_flow.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      gv_ok_code = CONV #( ct_values[ name = 'GV_OK_CODE' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_INPUT' ] ).
      gv_input = CONV #( ct_values[ name = 'GV_INPUT' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_OUTPUT' ] ).
      gv_output = CONV #( ct_values[ name = 'GV_OUTPUT' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_CHECK' ] ).
      gv_check = CONV #( ct_values[ name = 'GV_CHECK' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_ALPHA' ] ).
      gv_alpha = CONV #( ct_values[ name = 'GV_ALPHA' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_BETA' ] ).
      gv_beta = CONV #( ct_values[ name = 'GV_BETA' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_LIST' ] ).
      gv_list = CONV #( ct_values[ name = 'GV_LIST' ]-value ).
    ENDIF.
    IF is_context-screen = '0100'.
      io_session->get_dialog( )->set_status( VALUE #( status = 'MAIN' active_pf_keys = VALUE #(
        ( 3 )
        ( 15 )
        ( 12 ) ) pf_actions = VALUE #(
        ( number = 3 ucomm = 'BACK' )
        ( number = 15 ucomm = 'EXIT' )
        ( number = 12 ucomm = 'CANCEL' ) ) ) ).
    ENDIF.
    TRY.
        output_modules(
          EXPORTING
            is_context = is_context
            io_session = io_session
          CHANGING
            ct_values  = ct_values
            ct_states  = ct_states ).
      CATCH zcx_gg_control_flow INTO lx_unwind.
    ENDTRY.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_INPUT' ] ).
      ct_values[ name = 'GV_INPUT' ]-value = CONV string( gv_input ).
    ELSE.
      INSERT VALUE #( name = 'GV_INPUT' value = CONV string( gv_input ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_OUTPUT' ] ).
      ct_values[ name = 'GV_OUTPUT' ]-value = CONV string( gv_output ).
    ELSE.
      INSERT VALUE #( name = 'GV_OUTPUT' value = CONV string( gv_output ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_CHECK' ] ).
      ct_values[ name = 'GV_CHECK' ]-value = CONV string( gv_check ).
    ELSE.
      INSERT VALUE #( name = 'GV_CHECK' value = CONV string( gv_check ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_ALPHA' ] ).
      ct_values[ name = 'GV_ALPHA' ]-value = CONV string( gv_alpha ).
    ELSE.
      INSERT VALUE #( name = 'GV_ALPHA' value = CONV string( gv_alpha ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_BETA' ] ).
      ct_values[ name = 'GV_BETA' ]-value = CONV string( gv_beta ).
    ELSE.
      INSERT VALUE #( name = 'GV_BETA' value = CONV string( gv_beta ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_LIST' ] ).
      ct_values[ name = 'GV_LIST' ]-value = CONV string( gv_list ).
    ELSE.
      INSERT VALUE #( name = 'GV_LIST' value = CONV string( gv_list ) ) INTO TABLE ct_values.
    ENDIF.
    IF lx_unwind IS BOUND.
      RAISE EXCEPTION lx_unwind.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_input_module.
    DATA lx_unwind TYPE REF TO zcx_gg_control_flow.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      gv_ok_code = CONV #( ct_values[ name = 'GV_OK_CODE' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_INPUT' ] ).
      gv_input = CONV #( ct_values[ name = 'GV_INPUT' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_CHECK' ] ).
      gv_check = CONV #( ct_values[ name = 'GV_CHECK' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_ALPHA' ] ).
      gv_alpha = CONV #( ct_values[ name = 'GV_ALPHA' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_BETA' ] ).
      gv_beta = CONV #( ct_values[ name = 'GV_BETA' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_LIST' ] ).
      gv_list = CONV #( ct_values[ name = 'GV_LIST' ]-value ).
    ENDIF.
    TRY.
        input_modules(
          EXPORTING
            is_context = is_context
            io_session = io_session
          CHANGING
            ct_values  = ct_values ).
      CATCH zcx_gg_control_flow INTO lx_unwind.
    ENDTRY.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_INPUT' ] ).
      ct_values[ name = 'GV_INPUT' ]-value = CONV string( gv_input ).
    ELSE.
      INSERT VALUE #( name = 'GV_INPUT' value = CONV string( gv_input ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_OUTPUT' ] ).
      ct_values[ name = 'GV_OUTPUT' ]-value = CONV string( gv_output ).
    ELSE.
      INSERT VALUE #( name = 'GV_OUTPUT' value = CONV string( gv_output ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_CHECK' ] ).
      ct_values[ name = 'GV_CHECK' ]-value = CONV string( gv_check ).
    ELSE.
      INSERT VALUE #( name = 'GV_CHECK' value = CONV string( gv_check ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_ALPHA' ] ).
      ct_values[ name = 'GV_ALPHA' ]-value = CONV string( gv_alpha ).
    ELSE.
      INSERT VALUE #( name = 'GV_ALPHA' value = CONV string( gv_alpha ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_BETA' ] ).
      ct_values[ name = 'GV_BETA' ]-value = CONV string( gv_beta ).
    ELSE.
      INSERT VALUE #( name = 'GV_BETA' value = CONV string( gv_beta ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_LIST' ] ).
      ct_values[ name = 'GV_LIST' ]-value = CONV string( gv_list ).
    ELSE.
      INSERT VALUE #( name = 'GV_LIST' value = CONV string( gv_list ) ) INTO TABLE ct_values.
    ENDIF.
    IF lx_unwind IS BOUND.
      RAISE EXCEPTION lx_unwind.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_on_value_request.
    DATA ct_values TYPE zif_gg_dynpro_types_v1=>ty_values.
    ct_values = it_values.
    rt_values = io_session->get_compatibility( )->get_value_help_values( ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_on_help_request.
    DATA ct_values TYPE zif_gg_dynpro_types_v1=>ty_values.
    ct_values = it_values.
  ENDMETHOD.

  METHOD output_modules.
    CASE is_context-module.
      WHEN 'STATUS_0100'.
        io_session->get_dialog( )->set_status( VALUE #( status = 'MAIN' active_ucomm = VALUE #(
          ( 'BACK' )
          ( 'EXIT' )
          ( 'CANCEL' ) ) active_pf_keys = VALUE #(
          ( 3 )
          ( 15 )
          ( 12 ) ) exit_ucomm = VALUE #(
          ( 'BACK' )
          ( 'CANCEL' )
          ( 'EXIT' ) ) pf_actions = VALUE #(
          ( number = 3 ucomm = 'BACK' )
          ( number = 15 ucomm = 'EXIT' )
          ( number = 12 ucomm = 'CANCEL' ) ) ) ).
        gt_values = VALUE #(
          ( key = 'A' text = 'Alpha' )
          ( key = 'B' text = 'Beta' ) ).
        io_session->get_compatibility( )->set_selection_list_values(
          iv_id     = CONV string( 'GV_LIST' )
          it_values = gt_values ).
      WHEN OTHERS.
        RETURN.
    ENDCASE.
  ENDMETHOD.

  METHOD input_modules.
    CASE is_context-module.
      WHEN 'EXIT_0100'.
        CLEAR gv_ok_code.
        io_session->get_dialog( )->leave_to_screen( '0000' ).
      WHEN 'USER_COMMAND_0100'.
        IF gv_ok_code = 'APPLY'.
          gv_output = |{ gv_input }, { COND string( WHEN gv_check = 'X' THEN 'checked' ELSE 'unchecked' ) }, { COND string( WHEN gv_alpha = 'X' THEN 'Alpha' ELSE 'Beta' ) }, { gv_list }|.
        ENDIF.
        CLEAR gv_ok_code.
      WHEN OTHERS.
        RETURN.
    ENDCASE.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~get_settings.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~end_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page_during_line_sel.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_line_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_user_command.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_pf.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_resumable_v1~resume.
* Continuation states are explicit so unsupported suspension semantics remain visible.
    CASE is_resume-continuation-id.
      WHEN 'AFTER_0100'.
        RETURN.
      WHEN OTHERS.
        RETURN.
    ENDCASE.
  ENDMETHOD.

ENDCLASS.
