* Generated by open-abap-gui converter 0.1.0.
* Source object: ZGG_EX_029
* Source file: examples/zgg_ex_029.prog.abap
* Source SHA-256: 5cd47fe382e8655dbd777b1ab689548334dacadf4345834c99823e4afcbabb52
* Target class: ZCL_GG_EX_029
* Manifest schema: 1
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_029 DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_transaction_v1.

  PRIVATE SECTION.
    DATA mv_p_cnt TYPE i.

ENDCLASS.

CLASS zcl_gg_ex_029 IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZGG_EX_029' description = 'AT SELECTION-SCREEN OUTPUT writing a parameter' program = 'ZGG_EX_029' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'AT SELECTION-SCREEN OUTPUT writing a parameter' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    io_builder->add_parameter( VALUE #( name = 'P_CNT' text = 'Count' data_type = VALUE #( typ = 'I' ) ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    mv_p_cnt = ct_values[ name = 'P_CNT' ]-value.
    IF ct_values[ name = 'P_CNT' ]-value <> mv_p_cnt.
      ct_values[ name = 'P_CNT' ]-value = |{ mv_p_cnt }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    mv_p_cnt = ct_values[ name = 'P_CNT' ]-value.
    mv_p_cnt = mv_p_cnt + 1.
    IF ct_values[ name = 'P_CNT' ]-value <> mv_p_cnt.
      ct_values[ name = 'P_CNT' ]-value = |{ mv_p_cnt }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    mv_p_cnt = ct_values[ name = 'P_CNT' ]-value.
    IF ct_values[ name = 'P_CNT' ]-value <> mv_p_cnt.
      ct_values[ name = 'P_CNT' ]-value = |{ mv_p_cnt }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    mv_p_cnt = ct_values[ name = 'P_CNT' ]-value.
    IF ct_values[ name = 'P_CNT' ]-value <> mv_p_cnt.
      ct_values[ name = 'P_CNT' ]-value = |{ mv_p_cnt }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    mv_p_cnt = ct_values[ name = 'P_CNT' ]-value.
    IF ct_values[ name = 'P_CNT' ]-value <> mv_p_cnt.
      ct_values[ name = 'P_CNT' ]-value = |{ mv_p_cnt }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    mv_p_cnt = ct_values[ name = 'P_CNT' ]-value.
    IF ct_values[ name = 'P_CNT' ]-value <> mv_p_cnt.
      ct_values[ name = 'P_CNT' ]-value = |{ mv_p_cnt }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    mv_p_cnt = ct_values[ name = 'P_CNT' ]-value.
    IF ct_values[ name = 'P_CNT' ]-value <> mv_p_cnt.
      ct_values[ name = 'P_CNT' ]-value = |{ mv_p_cnt }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    mv_p_cnt = it_values[ name = 'P_CNT' ]-value.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'AT SELECTION-SCREEN OUTPUT writing a parameter' ).
    mv_p_cnt = it_values[ name = 'P_CNT' ]-value.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    mv_p_cnt = it_values[ name = 'P_CNT' ]-value.
  ENDMETHOD.

ENDCLASS.
