* Generated by open-abap-gui converter 0.1.0.
* Source object: ZGG_EX_128
* Source file: examples/zgg_ex_128.prog.abap
* Source SHA-256: 9da6b2bd0c03f9667e50bdcd22b21675609adc9c9a7bdd152f313e038e2d25e6
* Target class: ZCL_GG_EX_128_H1
* Manifest schema: 1
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_128_h1 DEFINITION PUBLIC CREATE PUBLIC.

  PUBLIC SECTION.
    METHODS constructor
      IMPORTING
        io_owner   TYPE REF TO zcl_gg_ex_128
        io_session TYPE REF TO zif_gg_session_v1.
    DATA mo_owner TYPE REF TO zcl_gg_ex_128.
    DATA mo_session TYPE REF TO zif_gg_session_v1.
    CLASS-DATA go_owner TYPE REF TO zcl_gg_ex_128.
    CLASS-DATA go_session TYPE REF TO zif_gg_session_v1.
    CLASS-METHODS on_sapevent FOR EVENT sapevent OF cl_gui_html_viewer IMPORTING action.

ENDCLASS.

CLASS zcl_gg_ex_128_h1 IMPLEMENTATION.
  METHOD constructor.
    mo_owner = io_owner.
    mo_session = io_session.
  ENDMETHOD.

  METHOD on_sapevent.
    go_owner->gv_state = |SAPEVENT { action }|.
  ENDMETHOD.
ENDCLASS.
