* Generated by open-abap-gui converter 0.1.0.
* Source object: ZGG_EX_111
* Source file: examples/zgg_ex_111.prog.abap
* Source SHA-256: 106918684af0226daa42b18ee9a02ce70b3a577f3f6f7d8314d9b6e4d75289a5
* Target class: ZCL_GG_EX_111
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_111 DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_screen_provider_v1.
    INTERFACES zif_gg_transaction_v1.
    INTERFACES zif_gg_list_processing_v1.
    INTERFACES zif_gg_resumable_v1.

  PRIVATE SECTION.
    DATA gv_ok_code TYPE sy-ucomm.
    DATA gv_trail TYPE c LENGTH 60 VALUE '100'.
    METHODS output_modules
      IMPORTING
        is_context TYPE zif_gg_dynpro_types_v1=>ty_module_context
        io_session TYPE REF TO zif_gg_session_v1
      CHANGING
        ct_values  TYPE zif_gg_dynpro_types_v1=>ty_values
        ct_states  TYPE zif_gg_dynpro_types_v1=>ty_states.
    METHODS input_modules
      IMPORTING
        is_context TYPE zif_gg_dynpro_types_v1=>ty_module_context
        io_session TYPE REF TO zif_gg_session_v1
      CHANGING
        ct_values  TYPE zif_gg_dynpro_types_v1=>ty_values.

ENDCLASS.

CLASS zcl_gg_ex_111 IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZGG_EX_111' description = 'Nested screen calls' program = 'ZGG_EX_111' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'Nested screen calls' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    ro_list_processing = me.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'Nested screen calls' ).
    io_session->get_dialog( )->call_screen(
      is_call         = VALUE #( screen = '0100' )
      is_continuation = VALUE #( id = 'AFTER_0100' ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~get_initial_screen.
    rv_screen = '0100'.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~build_screens.
    io_builder->begin_screen( VALUE #( number = '0100' title = 'Nested screen calls' next_screen = '0100' ok_code = 'GV_OK_CODE' width = 800 height = 644 ) ).
    io_builder->add_pushbutton( VALUE #( control = VALUE #( name = 'BTN_FIRST' position = VALUE #( row = 10 column = 5 width = 180 height = 26 ) ) text = 'Call screen 200' ucomm = 'CALL200' ) ).
    io_builder->add_text( VALUE #( control = VALUE #( name = 'LBL_TRAIL' position = VALUE #( row = 62 column = 5 width = 100 height = 26 ) ) text = 'Calls' ) ).
    io_builder->add_output_field( VALUE #( control = VALUE #( name = 'GV_TRAIL' position = VALUE #( row = 62 column = 115 width = 600 height = 26 ) ) data_type = VALUE #( typ = 'C' length = 60 ) ) ).
    io_builder->end_screen( ).
    io_builder->begin_screen( VALUE #( number = '0200' title = 'Screen 200' next_screen = '0200' ok_code = 'GV_OK_CODE' modal = abap_true width = 500 height = 124 ) ).
    io_builder->add_text( VALUE #( control = VALUE #( name = 'LBL_200' position = VALUE #( row = 10 column = 5 width = 250 height = 26 ) ) text = 'Called from screen 100' ) ).
    io_builder->add_pushbutton( VALUE #( control = VALUE #( name = 'BTN_SECOND' position = VALUE #( row = 62 column = 5 width = 180 height = 26 ) ) text = 'Call screen 300' ucomm = 'CALL300' ) ).
    io_builder->end_screen( ).
    io_builder->begin_screen( VALUE #( number = '0300' title = 'Screen 300' next_screen = '0300' ok_code = 'GV_OK_CODE' modal = abap_true width = 500 height = 98 ) ).
    io_builder->add_text( VALUE #( control = VALUE #( name = 'LBL_300' position = VALUE #( row = 10 column = 5 width = 250 height = 26 ) ) text = 'Called from screen 200' ) ).
    io_builder->end_screen( ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~build_flow_logic.
    io_builder->begin_screen( '0100' ).
    io_builder->begin_pbo( ).
    io_builder->add_module( VALUE #( name = 'STATUS_0100' ) ).
    io_builder->end_processing( ).
    io_builder->begin_pai( ).
    io_builder->add_module( VALUE #( name = 'EXIT_0100' on_input = abap_true at_exit_command = abap_true ) ).
    io_builder->add_module( VALUE #( name = 'USER_COMMAND_0100' on_input = abap_true ) ).
    io_builder->end_processing( ).
    io_builder->end_screen( ).
    io_builder->begin_screen( '0200' ).
    io_builder->begin_pbo( ).
    io_builder->add_module( VALUE #( name = 'STATUS_MODAL' ) ).
    io_builder->end_processing( ).
    io_builder->begin_pai( ).
    io_builder->add_module( VALUE #( name = 'EXIT_MODAL' on_input = abap_true at_exit_command = abap_true ) ).
    io_builder->add_module( VALUE #( name = 'USER_COMMAND_0200' on_input = abap_true ) ).
    io_builder->end_processing( ).
    io_builder->end_screen( ).
    io_builder->begin_screen( '0300' ).
    io_builder->begin_pbo( ).
    io_builder->add_module( VALUE #( name = 'STATUS_MODAL' ) ).
    io_builder->end_processing( ).
    io_builder->begin_pai( ).
    io_builder->add_module( VALUE #( name = 'EXIT_MODAL' on_input = abap_true at_exit_command = abap_true ) ).
    io_builder->end_processing( ).
    io_builder->end_screen( ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~initialization.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_TRAIL' ] ).
      ct_values[ name = 'GV_TRAIL' ]-value = CONV string( gv_trail ).
    ELSE.
      INSERT VALUE #( name = 'GV_TRAIL' value = CONV string( gv_trail ) ) INTO TABLE ct_values.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_output_module.
    DATA lx_unwind TYPE REF TO zcx_gg_control_flow.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      gv_ok_code = CONV #( ct_values[ name = 'GV_OK_CODE' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_TRAIL' ] ).
      gv_trail = CONV #( ct_values[ name = 'GV_TRAIL' ]-value ).
    ENDIF.
    TRY.
        output_modules(
          EXPORTING
            is_context = is_context
            io_session = io_session
          CHANGING
            ct_values  = ct_values
            ct_states  = ct_states ).
      CATCH zcx_gg_control_flow INTO lx_unwind.
    ENDTRY.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_TRAIL' ] ).
      ct_values[ name = 'GV_TRAIL' ]-value = CONV string( gv_trail ).
    ELSE.
      INSERT VALUE #( name = 'GV_TRAIL' value = CONV string( gv_trail ) ) INTO TABLE ct_values.
    ENDIF.
    IF lx_unwind IS BOUND.
      RAISE EXCEPTION lx_unwind.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_input_module.
    DATA lx_unwind TYPE REF TO zcx_gg_control_flow.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      gv_ok_code = CONV #( ct_values[ name = 'GV_OK_CODE' ]-value ).
    ENDIF.
    TRY.
        input_modules(
          EXPORTING
            is_context = is_context
            io_session = io_session
          CHANGING
            ct_values  = ct_values ).
      CATCH zcx_gg_control_flow INTO lx_unwind.
    ENDTRY.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_TRAIL' ] ).
      ct_values[ name = 'GV_TRAIL' ]-value = CONV string( gv_trail ).
    ELSE.
      INSERT VALUE #( name = 'GV_TRAIL' value = CONV string( gv_trail ) ) INTO TABLE ct_values.
    ENDIF.
    IF lx_unwind IS BOUND.
      RAISE EXCEPTION lx_unwind.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_on_value_request.
    DATA ct_values TYPE zif_gg_dynpro_types_v1=>ty_values.
    ct_values = it_values.
    rt_values = io_session->get_compatibility( )->get_value_help_values( ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_on_help_request.
    DATA ct_values TYPE zif_gg_dynpro_types_v1=>ty_values.
    ct_values = it_values.
    IF line_exists( ct_values[ name = 'GV_RESULT' ] ).
      rv_text = ct_values[ name = 'GV_RESULT' ]-value.
    ENDIF.
  ENDMETHOD.

  METHOD output_modules.
    CASE is_context-module.
      WHEN 'STATUS_0100'.
        io_session->get_dialog( )->set_status( VALUE #( status = 'MAIN' active_ucomm = VALUE #( ( 'BACK' ) ( 'EXIT' ) ( 'CANCEL' ) ) active_pf_keys = VALUE #( ( 3 ) ( 15 ) ( 12 ) ) exit_ucomm = VALUE #( ( 'BACK' ) ( 'CANCEL' ) ( 'EXIT' ) ) pf_actions = VALUE #( ( number = 3 ucomm = 'BACK' ) ( number = 15 ucomm = 'EXIT' ) ( number = 12 ucomm = 'CANCEL' ) ) ) ).
      WHEN 'STATUS_MODAL'.
        io_session->get_dialog( )->set_status( VALUE #( status = 'MODAL' active_ucomm = VALUE #( ( 'BACK' ) ( 'CANCEL' ) ) active_pf_keys = VALUE #( ( 3 ) ( 12 ) ) exit_ucomm = VALUE #( ( 'BACK' ) ( 'CANCEL' ) ) pf_actions = VALUE #( ( number = 3 ucomm = 'BACK' ) ( number = 12 ucomm = 'CANCEL' ) ) ) ).
      WHEN OTHERS.
        RETURN.
    ENDCASE.
  ENDMETHOD.

  METHOD input_modules.
    CASE is_context-module.
      WHEN 'EXIT_0100'.
        CLEAR gv_ok_code.
        io_session->get_dialog( )->leave_to_screen( '0000' ).
      WHEN 'USER_COMMAND_0100'.
* CALL SCREEN starts a screen sequence; LEAVE TO SCREEN 0 ends it and
* continues after the CALL SCREEN that started it.
        IF gv_ok_code = 'CALL200'.
          CLEAR gv_ok_code.
          gv_trail = |{ gv_trail } > 200|.
          io_session->get_dialog( )->call_screen(
            is_call         = VALUE #( screen = '0200' modal = VALUE #( start_row = 10 start_column = 4 ) )
            is_continuation = VALUE #( id = 'AFTER_0200' ) ).
          gv_trail = |{ gv_trail } > back in 100|.
        ENDIF.
        CLEAR gv_ok_code.
      WHEN 'EXIT_MODAL'.
        CLEAR gv_ok_code.
        io_session->get_dialog( )->leave_to_screen( '0000' ).
      WHEN 'USER_COMMAND_0200'.
        IF gv_ok_code = 'CALL300'.
          CLEAR gv_ok_code.
          gv_trail = |{ gv_trail } > 300|.
          io_session->get_dialog( )->call_screen(
            is_call         = VALUE #( screen = '0300' modal = VALUE #( start_row = 20 start_column = 8 ) )
            is_continuation = VALUE #( id = 'AFTER_0300' ) ).
          gv_trail = |{ gv_trail } > back in 200|.
        ENDIF.
        CLEAR gv_ok_code.
      WHEN OTHERS.
        RETURN.
    ENDCASE.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~get_settings.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~end_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page_during_line_sel.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_line_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_user_command.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_pf.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_resumable_v1~resume.
* Continuation states are explicit so unsupported suspension semantics remain visible.
    CASE is_resume-continuation-id.
      WHEN 'AFTER_0100'.
        RETURN.
      WHEN 'AFTER_0200'.
        gv_trail = |{ gv_trail } > back in 100|.
        CLEAR gv_ok_code.
      WHEN 'AFTER_0300'.
        gv_trail = |{ gv_trail } > back in 200|.
        CLEAR gv_ok_code.
      WHEN OTHERS.
        RETURN.
    ENDCASE.
  ENDMETHOD.

ENDCLASS.
