* Generated by open-abap-gui converter 0.1.0.
* Source object: ZGG_EX_126
* Source file: examples/zgg_ex_126.prog.abap
* Source SHA-256: 79d3ab7ff472a6e1b81f047a05a2df6d73b170070b07d394c55e2a47e9165a7c
* Target class: ZCL_GG_EX_126_H1
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_126_h1 DEFINITION PUBLIC CREATE PUBLIC.

  PUBLIC SECTION.
    METHODS constructor
      IMPORTING
        io_owner   TYPE REF TO zcl_gg_ex_126
        io_session TYPE REF TO zif_gg_session_v1.
    DATA mo_owner TYPE REF TO zcl_gg_ex_126.
    DATA mo_session TYPE REF TO zif_gg_session_v1.
    CLASS-DATA go_owner TYPE REF TO zcl_gg_ex_126.
    CLASS-DATA go_session TYPE REF TO zif_gg_session_v1.
    CLASS-METHODS on_date FOR EVENT date_selected OF cl_gui_calendar IMPORTING date_begin date_end.

ENDCLASS.

CLASS zcl_gg_ex_126_h1 IMPLEMENTATION.
  METHOD constructor.
    mo_owner = io_owner.
    mo_session = io_session.
  ENDMETHOD.

  METHOD on_date.
    go_owner->gv_state = |Selected { date_begin } to { date_end }|.
  ENDMETHOD.
ENDCLASS.
