* Generated by open-abap-gui converter.
* Source object: ZGG_EX_096
* Source file: examples/zgg_ex_096.prog.abap
* Source SHA-256: b54629820fa63c4b844679de18a97d57598fa3bb3664bd8d549f291ed1ea4c47
* Target class: ZCL_GG_EX_096
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_096 DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_transaction_v1.
    INTERFACES zif_gg_list_processing_v1.

ENDCLASS.

CLASS zcl_gg_ex_096 IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZGG_EX_096' description = 'Stacked list messages' program = 'ZGG_EX_096' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'Stacked list messages' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    ro_list_processing = me.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'Stacked list messages' ).
    DATA(lo_writer) = io_session->get_list( )->get_writer( ).
    io_session->get_list( )->set_status( VALUE #( status = 'LIST' active_ucomm = VALUE #( ( 'MESSAGES' ) ) active_pf_keys = VALUE #( ( 13 ) ) icon_bar = VALUE #( ( ucomm = 'MESSAGES' label = 'Messages' icon = 'ICON_INFORMATION' ) ) pf_actions = VALUE #( ( number = 13 ucomm = 'MESSAGES' ) ) ) ).
    lo_writer->write_field( VALUE #( text = 'message list' placement = VALUE #( new_line = abap_true ) ) ).
    io_session->message( VALUE #( type = zif_gg_session_types_v1=>message_type_success text = 'Saved successfully' ) ).
    io_session->message( VALUE #( type = zif_gg_session_types_v1=>message_type_success text = 'Review the selection' display_like = zif_gg_session_types_v1=>message_type_warning ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~get_settings.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~end_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page_during_line_sel.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_line_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_user_command.
    IF iv_ucomm = 'MESSAGES'.
      io_session->message( VALUE #( type = zif_gg_session_types_v1=>message_type_success text = 'Success message' ) ).
      io_session->message( VALUE #( type = zif_gg_session_types_v1=>message_type_success text = 'Warning message' display_like = zif_gg_session_types_v1=>message_type_warning ) ).
      io_session->message( VALUE #( type = zif_gg_session_types_v1=>message_type_success text = 'Error message' display_like = zif_gg_session_types_v1=>message_type_error ) ).
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_pf.
    RETURN.
  ENDMETHOD.

ENDCLASS.
