* Generated by open-abap-gui converter.
* Source object: ZGG_EX_154
* Source file: examples/zgg_ex_154.prog.abap
* Source SHA-256: b105682999752ea770b696fb1484c64111a2045c09cd4bd6f3a9586f5ecda3b9
* Target class: ZCL_GG_EX_154
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_154 DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_screen_provider_v1.
    INTERFACES zif_gg_transaction_v1.
    INTERFACES zif_gg_resumable_v1.

  PRIVATE SECTION.
    TYPES: BEGIN OF ty_flight, carrid TYPE c LENGTH 3, connid TYPE n LENGTH 4, cityfrom TYPE c LENGTH 20, cityto TYPE c LENGTH 20, END OF ty_flight.
    DATA gt_flights TYPE STANDARD TABLE OF ty_flight WITH DEFAULT KEY.
    DATA gt_lines TYPE STANDARD TABLE OF string WITH DEFAULT KEY.
    DATA gt_files TYPE filetable.
    DATA gs_file TYPE file_table.
    DATA gv_rc TYPE i.
    DATA gv_action TYPE i.
    DATA gv_filename TYPE string.
    DATA gv_path TYPE string.
    DATA gv_fullpath TYPE string.
    DATA gv_length TYPE i.
    DATA gv_ok_code TYPE sy-ucomm.
    DATA gv_state TYPE c LENGTH 60.
    DATA gv_first_line TYPE c LENGTH 60.
    METHODS input_modules
      IMPORTING
        is_context TYPE zif_gg_dynpro_types_v1=>ty_module_context
        io_session TYPE REF TO zif_gg_session_v1
      CHANGING
        ct_values  TYPE zif_gg_dynpro_types_v1=>ty_values.

ENDCLASS.

CLASS zcl_gg_ex_154 IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZGG_EX_154' description = 'File download and upload' program = 'ZGG_EX_154' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'File download and upload' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'File download and upload' ).
    gt_flights = VALUE #(
      ( carrid = 'LH' connid = '0400' cityfrom = 'Frankfurt' cityto = 'New York' )
      ( carrid = 'UA' connid = '0941' cityfrom = 'Frankfurt' cityto = 'San Francisco' )
      ( carrid = 'AF' connid = '0010' cityfrom = 'Paris' cityto = 'New York' ) ).
    io_session->get_dialog( )->call_screen(
      is_call         = VALUE #( screen = '0100' )
      is_continuation = VALUE #( id = 'AFTER_0100' ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~get_initial_screen.
    rv_screen = '0100'.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~build_screens.
    io_builder->begin_screen( VALUE #( number = '0100' title = 'File download and upload' next_screen = '0100' ok_code = 'GV_OK_CODE' width = 800 height = 644 ) ).
    io_builder->add_pushbutton( VALUE #( control = VALUE #( name = 'BTN_DOWNLOAD' position = VALUE #( row = 36 column = 5 width = 200 height = 26 ) ) text = 'Download flights' ucomm = 'DOWNLOAD' ) ).
    io_builder->add_pushbutton( VALUE #( control = VALUE #( name = 'BTN_UPLOAD' position = VALUE #( row = 36 column = 215 width = 160 height = 26 ) ) text = 'Upload file' ucomm = 'UPLOAD' ) ).
    io_builder->add_text( VALUE #( control = VALUE #( name = 'LBL_STATE' position = VALUE #( row = 88 column = 5 width = 110 height = 26 ) ) text = 'State' ) ).
    io_builder->add_output_field( VALUE #( control = VALUE #( name = 'GV_STATE' position = VALUE #( row = 88 column = 125 width = 600 height = 26 ) ) data_type = VALUE #( typ = 'C' length = 60 ) ) ).
    io_builder->add_text( VALUE #( control = VALUE #( name = 'LBL_FIRST_LINE' position = VALUE #( row = 114 column = 5 width = 110 height = 26 ) ) text = 'First line' ) ).
    io_builder->add_output_field( VALUE #( control = VALUE #( name = 'GV_FIRST_LINE' position = VALUE #( row = 114 column = 125 width = 600 height = 26 ) ) data_type = VALUE #( typ = 'C' length = 60 ) ) ).
    io_builder->end_screen( ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~build_flow_logic.
    io_builder->begin_screen( '0100' ).
    io_builder->begin_pbo( ).
    io_builder->end_processing( ).
    io_builder->begin_pai( ).
    io_builder->add_module( VALUE #( name = 'USER_COMMAND_0100' on_input = abap_true ) ).
    io_builder->end_processing( ).
    io_builder->end_screen( ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~initialization.
    IF line_exists( ct_values[ name = 'GV_RC' ] ).
      ct_values[ name = 'GV_RC' ]-value = CONV string( gv_rc ).
    ELSE.
      INSERT VALUE #( name = 'GV_RC' value = CONV string( gv_rc ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_ACTION' ] ).
      ct_values[ name = 'GV_ACTION' ]-value = CONV string( gv_action ).
    ELSE.
      INSERT VALUE #( name = 'GV_ACTION' value = CONV string( gv_action ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_FILENAME' ] ).
      ct_values[ name = 'GV_FILENAME' ]-value = gv_filename.
    ELSE.
      INSERT VALUE #( name = 'GV_FILENAME' value = gv_filename ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_PATH' ] ).
      ct_values[ name = 'GV_PATH' ]-value = gv_path.
    ELSE.
      INSERT VALUE #( name = 'GV_PATH' value = gv_path ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_FULLPATH' ] ).
      ct_values[ name = 'GV_FULLPATH' ]-value = gv_fullpath.
    ELSE.
      INSERT VALUE #( name = 'GV_FULLPATH' value = gv_fullpath ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_LENGTH' ] ).
      ct_values[ name = 'GV_LENGTH' ]-value = CONV string( gv_length ).
    ELSE.
      INSERT VALUE #( name = 'GV_LENGTH' value = CONV string( gv_length ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_STATE' ] ).
      ct_values[ name = 'GV_STATE' ]-value = CONV string( gv_state ).
    ELSE.
      INSERT VALUE #( name = 'GV_STATE' value = CONV string( gv_state ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_FIRST_LINE' ] ).
      ct_values[ name = 'GV_FIRST_LINE' ]-value = CONV string( gv_first_line ).
    ELSE.
      INSERT VALUE #( name = 'GV_FIRST_LINE' value = CONV string( gv_first_line ) ) INTO TABLE ct_values.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_output_module.
    IF line_exists( ct_values[ name = 'GV_RC' ] ).
      gv_rc = CONV #( ct_values[ name = 'GV_RC' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_ACTION' ] ).
      gv_action = CONV #( ct_values[ name = 'GV_ACTION' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_FILENAME' ] ).
      gv_filename = CONV #( ct_values[ name = 'GV_FILENAME' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_PATH' ] ).
      gv_path = CONV #( ct_values[ name = 'GV_PATH' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_FULLPATH' ] ).
      gv_fullpath = CONV #( ct_values[ name = 'GV_FULLPATH' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_LENGTH' ] ).
      gv_length = CONV #( ct_values[ name = 'GV_LENGTH' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      gv_ok_code = CONV #( ct_values[ name = 'GV_OK_CODE' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_STATE' ] ).
      gv_state = CONV #( ct_values[ name = 'GV_STATE' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_FIRST_LINE' ] ).
      gv_first_line = CONV #( ct_values[ name = 'GV_FIRST_LINE' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_RC' ] ).
      ct_values[ name = 'GV_RC' ]-value = CONV string( gv_rc ).
    ELSE.
      INSERT VALUE #( name = 'GV_RC' value = CONV string( gv_rc ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_ACTION' ] ).
      ct_values[ name = 'GV_ACTION' ]-value = CONV string( gv_action ).
    ELSE.
      INSERT VALUE #( name = 'GV_ACTION' value = CONV string( gv_action ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_FILENAME' ] ).
      ct_values[ name = 'GV_FILENAME' ]-value = gv_filename.
    ELSE.
      INSERT VALUE #( name = 'GV_FILENAME' value = gv_filename ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_PATH' ] ).
      ct_values[ name = 'GV_PATH' ]-value = gv_path.
    ELSE.
      INSERT VALUE #( name = 'GV_PATH' value = gv_path ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_FULLPATH' ] ).
      ct_values[ name = 'GV_FULLPATH' ]-value = gv_fullpath.
    ELSE.
      INSERT VALUE #( name = 'GV_FULLPATH' value = gv_fullpath ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_LENGTH' ] ).
      ct_values[ name = 'GV_LENGTH' ]-value = CONV string( gv_length ).
    ELSE.
      INSERT VALUE #( name = 'GV_LENGTH' value = CONV string( gv_length ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_STATE' ] ).
      ct_values[ name = 'GV_STATE' ]-value = CONV string( gv_state ).
    ELSE.
      INSERT VALUE #( name = 'GV_STATE' value = CONV string( gv_state ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_FIRST_LINE' ] ).
      ct_values[ name = 'GV_FIRST_LINE' ]-value = CONV string( gv_first_line ).
    ELSE.
      INSERT VALUE #( name = 'GV_FIRST_LINE' value = CONV string( gv_first_line ) ) INTO TABLE ct_values.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_input_module.
    DATA lx_unwind TYPE REF TO zcx_gg_control_flow.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      gv_ok_code = CONV #( ct_values[ name = 'GV_OK_CODE' ]-value ).
    ENDIF.
    TRY.
        input_modules(
          EXPORTING
            is_context = is_context
            io_session = io_session
          CHANGING
            ct_values  = ct_values ).
      CATCH zcx_gg_control_flow INTO lx_unwind.
    ENDTRY.
    IF line_exists( ct_values[ name = 'GV_RC' ] ).
      ct_values[ name = 'GV_RC' ]-value = CONV string( gv_rc ).
    ELSE.
      INSERT VALUE #( name = 'GV_RC' value = CONV string( gv_rc ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_ACTION' ] ).
      ct_values[ name = 'GV_ACTION' ]-value = CONV string( gv_action ).
    ELSE.
      INSERT VALUE #( name = 'GV_ACTION' value = CONV string( gv_action ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_FILENAME' ] ).
      ct_values[ name = 'GV_FILENAME' ]-value = gv_filename.
    ELSE.
      INSERT VALUE #( name = 'GV_FILENAME' value = gv_filename ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_PATH' ] ).
      ct_values[ name = 'GV_PATH' ]-value = gv_path.
    ELSE.
      INSERT VALUE #( name = 'GV_PATH' value = gv_path ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_FULLPATH' ] ).
      ct_values[ name = 'GV_FULLPATH' ]-value = gv_fullpath.
    ELSE.
      INSERT VALUE #( name = 'GV_FULLPATH' value = gv_fullpath ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_LENGTH' ] ).
      ct_values[ name = 'GV_LENGTH' ]-value = CONV string( gv_length ).
    ELSE.
      INSERT VALUE #( name = 'GV_LENGTH' value = CONV string( gv_length ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_STATE' ] ).
      ct_values[ name = 'GV_STATE' ]-value = CONV string( gv_state ).
    ELSE.
      INSERT VALUE #( name = 'GV_STATE' value = CONV string( gv_state ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_FIRST_LINE' ] ).
      ct_values[ name = 'GV_FIRST_LINE' ]-value = CONV string( gv_first_line ).
    ELSE.
      INSERT VALUE #( name = 'GV_FIRST_LINE' value = CONV string( gv_first_line ) ) INTO TABLE ct_values.
    ENDIF.
    IF lx_unwind IS BOUND.
      RAISE EXCEPTION lx_unwind.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_on_value_request.
    DATA ct_values TYPE zif_gg_dynpro_types_v1=>ty_values.
    ct_values = it_values.
    rt_values = io_session->get_compatibility( )->get_value_help_values( ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_on_help_request.
    DATA ct_values TYPE zif_gg_dynpro_types_v1=>ty_values.
    ct_values = it_values.
  ENDMETHOD.

  METHOD input_modules.
    CASE is_context-module.
      WHEN 'USER_COMMAND_0100'.
        CASE gv_ok_code.
          WHEN 'DOWNLOAD'.
            TRY.
                cl_gui_frontend_services=>file_save_dialog(
                  EXPORTING
                    window_title      = 'Download flights'
                    default_extension = 'txt'
                    default_file_name = 'flights.txt'
                  CHANGING
                    filename          = gv_filename
                    path              = gv_path
                    fullpath          = gv_fullpath
                    user_action       = gv_action
                  EXCEPTIONS OTHERS   = 1 ).
              CATCH zcx_gg_control_flow INTO DATA(lx_popup_c_4f586f7cdd).
                RAISE EXCEPTION NEW zcx_gg_control_flow( iv_kind         = lx_popup_c_4f586f7cdd->mv_kind
                                                         iv_operation    = lx_popup_c_4f586f7cdd->mv_operation
                                                         iv_continuation = 'C_4F586F7CDD' ).
            ENDTRY.
            IF sy-subrc <> 0 OR gv_action <> cl_gui_frontend_services=>action_ok.
              gv_state = 'Download cancelled'.
            ELSE.
              cl_gui_frontend_services=>gui_download(
                EXPORTING
                  filename              = gv_fullpath
                  write_field_separator = abap_true
                IMPORTING
                  filelength            = gv_length
                CHANGING
                  data_tab              = gt_flights
                EXCEPTIONS OTHERS       = 1 ).
              IF sy-subrc = 0.
                gv_state = |{ gv_filename }: { gv_length } bytes downloaded|.
              ELSE.
                gv_state = 'Download failed'.
              ENDIF.
            ENDIF.
          WHEN 'UPLOAD'.
            TRY.
                cl_gui_frontend_services=>file_open_dialog(
                  EXPORTING
                    window_title      = 'Upload text file'
                    default_extension = 'txt'
                  CHANGING
                    file_table        = gt_files
                    rc                = gv_rc
                    user_action       = gv_action
                  EXCEPTIONS OTHERS   = 1 ).
              CATCH zcx_gg_control_flow INTO DATA(lx_popup_c_5a948424ee).
                RAISE EXCEPTION NEW zcx_gg_control_flow( iv_kind         = lx_popup_c_5a948424ee->mv_kind
                                                         iv_operation    = lx_popup_c_5a948424ee->mv_operation
                                                         iv_continuation = 'C_5A948424EE' ).
            ENDTRY.
            IF sy-subrc <> 0 OR gv_action <> cl_gui_frontend_services=>action_ok OR gv_rc <> 1.
              gv_state = 'Upload cancelled'.
            ELSE.
              READ TABLE gt_files INTO gs_file INDEX 1.
              gv_filename = gs_file-filename.
              CLEAR gt_lines.
              cl_gui_frontend_services=>gui_upload(
                EXPORTING
                  filename        = gv_filename
                IMPORTING
                  filelength      = gv_length
                CHANGING
                  data_tab        = gt_lines
                EXCEPTIONS OTHERS = 1 ).
              IF sy-subrc = 0.
                gv_state = |{ gv_filename }: { lines( gt_lines ) } lines, { gv_length } bytes|.
                READ TABLE gt_lines INTO DATA(gv_line) INDEX 1.
                gv_first_line = gv_line.
              ELSE.
                gv_state = 'Upload failed'.
              ENDIF.
            ENDIF.
        ENDCASE.
        CLEAR gv_ok_code.
      WHEN OTHERS.
        RETURN.
    ENDCASE.
  ENDMETHOD.

  METHOD zif_gg_resumable_v1~resume.
* Continuation states are explicit so unsupported suspension semantics remain visible.
    CASE is_resume-continuation-id.
      WHEN 'AFTER_0100'.
        RETURN.
      WHEN 'C_4F586F7CDD'.
        TRY.
            cl_gui_frontend_services=>file_save_dialog(
              EXPORTING
                window_title      = 'Download flights'
                default_extension = 'txt'
                default_file_name = 'flights.txt'
              CHANGING
                filename          = gv_filename
                path              = gv_path
                fullpath          = gv_fullpath
                user_action       = gv_action
              EXCEPTIONS OTHERS   = 1 ).
          CATCH zcx_gg_control_flow INTO DATA(lx_popup_c_4f586f7cdd).
            RAISE EXCEPTION NEW zcx_gg_control_flow( iv_kind         = lx_popup_c_4f586f7cdd->mv_kind
                                                     iv_operation    = lx_popup_c_4f586f7cdd->mv_operation
                                                     iv_continuation = 'C_4F586F7CDD' ).
        ENDTRY.
        IF sy-subrc <> 0 OR gv_action <> cl_gui_frontend_services=>action_ok.
          gv_state = 'Download cancelled'.
        ELSE.
          cl_gui_frontend_services=>gui_download(
            EXPORTING
              filename              = gv_fullpath
              write_field_separator = abap_true
            IMPORTING
              filelength            = gv_length
            CHANGING
              data_tab              = gt_flights
            EXCEPTIONS OTHERS       = 1 ).
          IF sy-subrc = 0.
            gv_state = |{ gv_filename }: { gv_length } bytes downloaded|.
          ELSE.
            gv_state = 'Download failed'.
          ENDIF.
        ENDIF.
        CLEAR gv_ok_code.
      WHEN 'C_5A948424EE'.
        TRY.
            cl_gui_frontend_services=>file_open_dialog(
              EXPORTING
                window_title      = 'Upload text file'
                default_extension = 'txt'
              CHANGING
                file_table        = gt_files
                rc                = gv_rc
                user_action       = gv_action
              EXCEPTIONS OTHERS   = 1 ).
          CATCH zcx_gg_control_flow INTO DATA(lx_popup_c_5a948424ee).
            RAISE EXCEPTION NEW zcx_gg_control_flow( iv_kind         = lx_popup_c_5a948424ee->mv_kind
                                                     iv_operation    = lx_popup_c_5a948424ee->mv_operation
                                                     iv_continuation = 'C_5A948424EE' ).
        ENDTRY.
        IF sy-subrc <> 0 OR gv_action <> cl_gui_frontend_services=>action_ok OR gv_rc <> 1.
          gv_state = 'Upload cancelled'.
        ELSE.
          READ TABLE gt_files INTO gs_file INDEX 1.
          gv_filename = gs_file-filename.
          CLEAR gt_lines.
          cl_gui_frontend_services=>gui_upload(
            EXPORTING
              filename        = gv_filename
            IMPORTING
              filelength      = gv_length
            CHANGING
              data_tab        = gt_lines
            EXCEPTIONS OTHERS = 1 ).
          IF sy-subrc = 0.
            gv_state = |{ gv_filename }: { lines( gt_lines ) } lines, { gv_length } bytes|.
            READ TABLE gt_lines INTO DATA(gv_line) INDEX 1.
            gv_first_line = gv_line.
          ELSE.
            gv_state = 'Upload failed'.
          ENDIF.
        ENDIF.
        CLEAR gv_ok_code.
      WHEN OTHERS.
        RETURN.
    ENDCASE.
  ENDMETHOD.

ENDCLASS.
