* Generated by open-abap-gui converter.
* Source object: ZGG_EX_155
* Source file: examples/zgg_ex_155.prog.abap
* Source SHA-256: 91390dc228f79640465154eadc42c28f10929e0f60c156f18e197a1a43341109
* Target class: ZCL_GG_EX_155_H1
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_155_h1 DEFINITION PUBLIC CREATE PUBLIC.

  PUBLIC SECTION.
    METHODS constructor
      IMPORTING
        io_owner   TYPE REF TO zcl_gg_ex_155
        io_session TYPE REF TO zif_gg_session_v1.
    DATA mo_owner TYPE REF TO zcl_gg_ex_155.
    DATA mo_session TYPE REF TO zif_gg_session_v1.
    CLASS-DATA go_owner TYPE REF TO zcl_gg_ex_155.
    CLASS-DATA go_session TYPE REF TO zif_gg_session_v1.
    CLASS-METHODS on_close FOR EVENT close OF cl_gui_dialogbox_container IMPORTING sender.

ENDCLASS.

CLASS zcl_gg_ex_155_h1 IMPLEMENTATION.
  METHOD constructor.
    mo_owner = io_owner.
    mo_session = io_session.
  ENDMETHOD.

  METHOD on_close.
    sender->free( ).
    CLEAR go_owner->go_dialog.
    CLEAR go_owner->go_editor.
  ENDMETHOD.
ENDCLASS.
