* Generated by open-abap-gui converter.
* Source object: ZGG_EX_036
* Source file: examples/zgg_ex_036.prog.abap
* Source SHA-256: c24b0141c7a5b2a5121f1416ae77342146561cfa7cbe39976d40e49cb4da167e
* Target class: ZCL_GG_EX_036
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_036 DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_transaction_v1.
    INTERFACES zif_gg_list_processing_v1.

  PRIVATE SECTION.
    DATA mv_p_carr TYPE c LENGTH 3.

ENDCLASS.

CLASS zcl_gg_ex_036 IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZGG_EX_036' description = 'AT SELECTION-SCREEN ON HELP-REQUEST' program = 'ZGG_EX_036' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'AT SELECTION-SCREEN ON HELP-REQUEST' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    ro_list_processing = me.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    io_builder->add_parameter( VALUE #( name = 'P_CARR' text = 'Carrier' data_type = VALUE #( typ = 'C' length = 3 ) ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    IF ct_values[ name = 'P_CARR' ]-value <> mv_p_carr.
      ct_values[ name = 'P_CARR' ]-value = |{ mv_p_carr }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    IF ct_values[ name = 'P_CARR' ]-value <> mv_p_carr.
      ct_values[ name = 'P_CARR' ]-value = |{ mv_p_carr }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    IF ct_values[ name = 'P_CARR' ]-value <> mv_p_carr.
      ct_values[ name = 'P_CARR' ]-value = |{ mv_p_carr }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    IF ct_values[ name = 'P_CARR' ]-value <> mv_p_carr.
      ct_values[ name = 'P_CARR' ]-value = |{ mv_p_carr }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    IF ct_values[ name = 'P_CARR' ]-value <> mv_p_carr.
      ct_values[ name = 'P_CARR' ]-value = |{ mv_p_carr }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    IF ct_values[ name = 'P_CARR' ]-value <> mv_p_carr.
      ct_values[ name = 'P_CARR' ]-value = |{ mv_p_carr }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    IF ct_values[ name = 'P_CARR' ]-value <> mv_p_carr.
      ct_values[ name = 'P_CARR' ]-value = |{ mv_p_carr }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    IF iv_name = 'P_CARR'.
      rv_text = 'Two character IATA code'.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    mv_p_carr = it_values[ name = 'P_CARR' ]-value.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'AT SELECTION-SCREEN ON HELP-REQUEST' ).
    mv_p_carr = it_values[ name = 'P_CARR' ]-value.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    mv_p_carr = it_values[ name = 'P_CARR' ]-value.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~get_settings.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~end_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page_during_line_sel.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_line_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_user_command.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_pf.
    RETURN.
  ENDMETHOD.

ENDCLASS.
