* Generated by open-abap-gui converter 0.1.0.
* Source object: ZGG_EX_019
* Source file: examples/zgg_ex_019.prog.abap
* Source SHA-256: 630d4b4f62dbaa42705366ccd380a09dc08667c89ec78c6b24d7526420fb90d7
* Target class: ZCL_GG_EX_019
* Manifest schema: 1
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_019 DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_transaction_v1.
    INTERFACES zif_gg_list_processing_v1.

  PRIVATE SECTION.
    DATA mv_p_mode TYPE zgg_mode.

ENDCLASS.

CLASS zcl_gg_ex_019 IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZGG_EX_019' description = 'Listbox from domain values' program = 'ZGG_EX_019' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'Listbox from domain values' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    ro_list_processing = me.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    io_builder->add_listbox( VALUE #( name = 'P_MODE' text = 'Mode' data_type = VALUE #( rollname = 'ZGG_MODE' typ = 'C' length = 1 visible_length = 10 ) default = 'A' ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    mv_p_mode = ct_values[ name = 'P_MODE' ]-value.
    IF ct_values[ name = 'P_MODE' ]-value <> mv_p_mode.
      ct_values[ name = 'P_MODE' ]-value = |{ mv_p_mode }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    mv_p_mode = ct_values[ name = 'P_MODE' ]-value.
    IF ct_values[ name = 'P_MODE' ]-value <> mv_p_mode.
      ct_values[ name = 'P_MODE' ]-value = |{ mv_p_mode }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    mv_p_mode = ct_values[ name = 'P_MODE' ]-value.
    IF ct_values[ name = 'P_MODE' ]-value <> mv_p_mode.
      ct_values[ name = 'P_MODE' ]-value = |{ mv_p_mode }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    mv_p_mode = ct_values[ name = 'P_MODE' ]-value.
    IF ct_values[ name = 'P_MODE' ]-value <> mv_p_mode.
      ct_values[ name = 'P_MODE' ]-value = |{ mv_p_mode }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    mv_p_mode = ct_values[ name = 'P_MODE' ]-value.
    IF ct_values[ name = 'P_MODE' ]-value <> mv_p_mode.
      ct_values[ name = 'P_MODE' ]-value = |{ mv_p_mode }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    mv_p_mode = ct_values[ name = 'P_MODE' ]-value.
    IF ct_values[ name = 'P_MODE' ]-value <> mv_p_mode.
      ct_values[ name = 'P_MODE' ]-value = |{ mv_p_mode }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    mv_p_mode = ct_values[ name = 'P_MODE' ]-value.
    IF ct_values[ name = 'P_MODE' ]-value <> mv_p_mode.
      ct_values[ name = 'P_MODE' ]-value = |{ mv_p_mode }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    mv_p_mode = it_values[ name = 'P_MODE' ]-value.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'Listbox from domain values' ).
    mv_p_mode = it_values[ name = 'P_MODE' ]-value.
* The listbox offers the fixed values of the domain ZGG_MODE, the domain of
* the parameter's data element, with their texts.
    io_session->get_list( )->set_title( 'Listbox from domain values' ).
    DATA(lo_writer) = io_session->get_list( )->get_writer( ).
    mv_p_mode = it_values[ name = 'P_MODE' ]-value.
    CASE mv_p_mode.
      WHEN 'A'.
        lo_writer->write_field( VALUE #( text = 'Mode A: the rows are added' placement = VALUE #( new_line = abap_true ) ) ).
      WHEN 'D'.
        lo_writer->write_field( VALUE #( text = 'Mode D: the rows are deleted' placement = VALUE #( new_line = abap_true ) ) ).
    ENDCASE.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    mv_p_mode = it_values[ name = 'P_MODE' ]-value.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~get_settings.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~end_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page_during_line_sel.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_line_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_user_command.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_pf.
    RETURN.
  ENDMETHOD.

ENDCLASS.
