* Generated by open-abap-gui converter 0.1.0.
* Source object: ZGG_EX_092
* Source file: examples/zgg_ex_092.prog.abap
* Source SHA-256: 65b9d0088cb28c148a190f0de14966f5c54d7d8656869250eefd2f1344d490e3
* Target class: ZCL_GG_EX_092
* Manifest schema: 1
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_092 DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_transaction_v1.
    INTERFACES zif_gg_list_processing_v1.

  PRIVATE SECTION.
    TYPES: BEGIN OF ty_flight, carrid TYPE c LENGTH 3, connid TYPE n LENGTH 4, cityfrom TYPE c LENGTH 20, cityto TYPE c LENGTH 20, END OF ty_flight.
    DATA gt_flights TYPE STANDARD TABLE OF ty_flight WITH DEFAULT KEY.
    DATA gs_flight TYPE ty_flight.
    DATA gt_cities TYPE STANDARD TABLE OF string WITH DEFAULT KEY.

ENDCLASS.

CLASS zcl_gg_ex_092 IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZGG_EX_092' description = 'Page through a long list' program = 'ZGG_EX_092' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'Page through a long list' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    ro_list_processing = me.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'Page through a long list' ).
* A list longer than the window. The list processor pages through it with
* First page, Previous page, Next page and Last page; the program writes the
* list once and is not called again.
    io_session->get_list( )->set_title( 'Page through a long list' ).
    DATA(lo_writer) = io_session->get_list( )->get_writer( ).
    gt_cities = VALUE #( ( `Frankfurt` ) ( `New York` ) ( `Singapore` ) ( `Tokyo` ) ( `Rome` ) ( `San Francisco` ) ).
    DO 80 TIMES.
      gs_flight-carrid = COND #( WHEN sy-index MOD 2 = 0 THEN 'LH' ELSE 'UA' ).
      gs_flight-connid = 400 + sy-index.
      gs_flight-cityfrom = gt_cities[ sy-index MOD 6 + 1 ].
      gs_flight-cityto = gt_cities[ ( sy-index + 2 ) MOD 6 + 1 ].
      APPEND gs_flight TO gt_flights.
    ENDDO.
    LOOP AT gt_flights INTO gs_flight.
      lo_writer->write_field( VALUE #( text = |{ gs_flight-carrid }| placement = VALUE #( new_line = abap_true ) ) ).
      lo_writer->write_field( VALUE #( text = |{ gs_flight-connid }| placement = VALUE #( position = 10 ) ) ).
      lo_writer->write_field( VALUE #( text = |{ gs_flight-cityfrom }| placement = VALUE #( position = 18 ) ) ).
      lo_writer->write_field( VALUE #( text = |{ gs_flight-cityto }| placement = VALUE #( position = 40 ) ) ).
    ENDLOOP.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~get_settings.
    rs_settings = VALUE #( line_size = 60 line_count = 20 footer_lines = 1 ).
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page.
    DATA(lo_writer) = io_session->get_list( )->get_writer( ).
    lo_writer->write_field( VALUE #( text = 'Airline' placement = VALUE #( new_line = abap_true ) ) ).
    lo_writer->write_field( VALUE #( text = 'Flight' placement = VALUE #( position = 10 ) ) ).
    lo_writer->write_field( VALUE #( text = 'From' placement = VALUE #( position = 18 ) ) ).
    lo_writer->write_field( VALUE #( text = 'To' placement = VALUE #( position = 40 ) ) ).
    lo_writer->uline( VALUE #( ) ).
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~end_of_page.
    DATA(lo_writer) = io_session->get_list( )->get_writer( ).
    lo_writer->write_field( VALUE #( text = |Page { io_session->get_list( )->get_context( )-page }| placement = VALUE #( new_line = abap_true ) ) ).
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page_during_line_sel.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_line_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_user_command.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_pf.
    RETURN.
  ENDMETHOD.

ENDCLASS.
