* Generated by open-abap-gui converter.
* Source object: ZGG_EX_171
* Source file: examples/zgg_ex_171.prog.abap
* Source SHA-256: 952e61442214baa7a6703542f031f828dc46277562915ad92aab1915393c849c
* Target class: ZCL_GG_EX_171
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_171 DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_transaction_v1.

  PRIVATE SECTION.
    TYPES: BEGIN OF ty_entry, msgno TYPE n LENGTH 3, text TYPE c LENGTH 40, END OF ty_entry.
    DATA gt_log TYPE STANDARD TABLE OF ty_entry WITH DEFAULT KEY.
    DATA gs_entry TYPE ty_entry.
    DATA go_alv TYPE REF TO cl_salv_table.
    DATA gx_msg TYPE REF TO cx_salv_msg.
    DATA gv_text TYPE string.
    DATA mv_p_count TYPE i.
    DATA mv_p_like TYPE c LENGTH 1.
    DATA mv_p_long TYPE c LENGTH 1.
    DATA mv_p_quiet TYPE c LENGTH 1.

ENDCLASS.

CLASS zcl_gg_ex_171 IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZGG_EX_171' description = 'Log with entry count' program = 'ZGG_EX_171' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'Log with entry count' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    io_builder->add_parameter( VALUE #( name = 'P_COUNT' text = 'Entries' data_type = VALUE #( typ = 'I' ) default = '3' ) ).
    io_builder->add_parameter( VALUE #( name = 'P_LIKE' text = 'Display like' data_type = VALUE #( typ = 'C' length = 1 ) default = 'S' ) ).
    io_builder->add_checkbox( VALUE #( name = 'P_LONG' text = 'Long message' ) ).
    io_builder->add_checkbox( VALUE #( name = 'P_QUIET' text = 'No message' ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    mv_p_count = ct_values[ name = 'P_COUNT' ]-value.
    mv_p_like = ct_values[ name = 'P_LIKE' ]-value.
    mv_p_long = ct_values[ name = 'P_LONG' ]-value.
    mv_p_quiet = ct_values[ name = 'P_QUIET' ]-value.
    IF ct_values[ name = 'P_COUNT' ]-value <> mv_p_count.
      ct_values[ name = 'P_COUNT' ]-value = |{ mv_p_count }|.
    ENDIF.
    IF ct_values[ name = 'P_LIKE' ]-value <> mv_p_like.
      ct_values[ name = 'P_LIKE' ]-value = |{ mv_p_like }|.
    ENDIF.
    IF ct_values[ name = 'P_LONG' ]-value <> mv_p_long.
      ct_values[ name = 'P_LONG' ]-value = |{ mv_p_long }|.
    ENDIF.
    IF ct_values[ name = 'P_QUIET' ]-value <> mv_p_quiet.
      ct_values[ name = 'P_QUIET' ]-value = |{ mv_p_quiet }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    mv_p_count = ct_values[ name = 'P_COUNT' ]-value.
    mv_p_like = ct_values[ name = 'P_LIKE' ]-value.
    mv_p_long = ct_values[ name = 'P_LONG' ]-value.
    mv_p_quiet = ct_values[ name = 'P_QUIET' ]-value.
    IF ct_values[ name = 'P_COUNT' ]-value <> mv_p_count.
      ct_values[ name = 'P_COUNT' ]-value = |{ mv_p_count }|.
    ENDIF.
    IF ct_values[ name = 'P_LIKE' ]-value <> mv_p_like.
      ct_values[ name = 'P_LIKE' ]-value = |{ mv_p_like }|.
    ENDIF.
    IF ct_values[ name = 'P_LONG' ]-value <> mv_p_long.
      ct_values[ name = 'P_LONG' ]-value = |{ mv_p_long }|.
    ENDIF.
    IF ct_values[ name = 'P_QUIET' ]-value <> mv_p_quiet.
      ct_values[ name = 'P_QUIET' ]-value = |{ mv_p_quiet }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    mv_p_count = ct_values[ name = 'P_COUNT' ]-value.
    mv_p_like = ct_values[ name = 'P_LIKE' ]-value.
    mv_p_long = ct_values[ name = 'P_LONG' ]-value.
    mv_p_quiet = ct_values[ name = 'P_QUIET' ]-value.
    IF ct_values[ name = 'P_COUNT' ]-value <> mv_p_count.
      ct_values[ name = 'P_COUNT' ]-value = |{ mv_p_count }|.
    ENDIF.
    IF ct_values[ name = 'P_LIKE' ]-value <> mv_p_like.
      ct_values[ name = 'P_LIKE' ]-value = |{ mv_p_like }|.
    ENDIF.
    IF ct_values[ name = 'P_LONG' ]-value <> mv_p_long.
      ct_values[ name = 'P_LONG' ]-value = |{ mv_p_long }|.
    ENDIF.
    IF ct_values[ name = 'P_QUIET' ]-value <> mv_p_quiet.
      ct_values[ name = 'P_QUIET' ]-value = |{ mv_p_quiet }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    mv_p_count = ct_values[ name = 'P_COUNT' ]-value.
    mv_p_like = ct_values[ name = 'P_LIKE' ]-value.
    mv_p_long = ct_values[ name = 'P_LONG' ]-value.
    mv_p_quiet = ct_values[ name = 'P_QUIET' ]-value.
    IF ct_values[ name = 'P_COUNT' ]-value <> mv_p_count.
      ct_values[ name = 'P_COUNT' ]-value = |{ mv_p_count }|.
    ENDIF.
    IF ct_values[ name = 'P_LIKE' ]-value <> mv_p_like.
      ct_values[ name = 'P_LIKE' ]-value = |{ mv_p_like }|.
    ENDIF.
    IF ct_values[ name = 'P_LONG' ]-value <> mv_p_long.
      ct_values[ name = 'P_LONG' ]-value = |{ mv_p_long }|.
    ENDIF.
    IF ct_values[ name = 'P_QUIET' ]-value <> mv_p_quiet.
      ct_values[ name = 'P_QUIET' ]-value = |{ mv_p_quiet }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    mv_p_count = ct_values[ name = 'P_COUNT' ]-value.
    mv_p_like = ct_values[ name = 'P_LIKE' ]-value.
    mv_p_long = ct_values[ name = 'P_LONG' ]-value.
    mv_p_quiet = ct_values[ name = 'P_QUIET' ]-value.
    IF ct_values[ name = 'P_COUNT' ]-value <> mv_p_count.
      ct_values[ name = 'P_COUNT' ]-value = |{ mv_p_count }|.
    ENDIF.
    IF ct_values[ name = 'P_LIKE' ]-value <> mv_p_like.
      ct_values[ name = 'P_LIKE' ]-value = |{ mv_p_like }|.
    ENDIF.
    IF ct_values[ name = 'P_LONG' ]-value <> mv_p_long.
      ct_values[ name = 'P_LONG' ]-value = |{ mv_p_long }|.
    ENDIF.
    IF ct_values[ name = 'P_QUIET' ]-value <> mv_p_quiet.
      ct_values[ name = 'P_QUIET' ]-value = |{ mv_p_quiet }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    mv_p_count = ct_values[ name = 'P_COUNT' ]-value.
    mv_p_like = ct_values[ name = 'P_LIKE' ]-value.
    mv_p_long = ct_values[ name = 'P_LONG' ]-value.
    mv_p_quiet = ct_values[ name = 'P_QUIET' ]-value.
    IF ct_values[ name = 'P_COUNT' ]-value <> mv_p_count.
      ct_values[ name = 'P_COUNT' ]-value = |{ mv_p_count }|.
    ENDIF.
    IF ct_values[ name = 'P_LIKE' ]-value <> mv_p_like.
      ct_values[ name = 'P_LIKE' ]-value = |{ mv_p_like }|.
    ENDIF.
    IF ct_values[ name = 'P_LONG' ]-value <> mv_p_long.
      ct_values[ name = 'P_LONG' ]-value = |{ mv_p_long }|.
    ENDIF.
    IF ct_values[ name = 'P_QUIET' ]-value <> mv_p_quiet.
      ct_values[ name = 'P_QUIET' ]-value = |{ mv_p_quiet }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    mv_p_count = ct_values[ name = 'P_COUNT' ]-value.
    mv_p_like = ct_values[ name = 'P_LIKE' ]-value.
    mv_p_long = ct_values[ name = 'P_LONG' ]-value.
    mv_p_quiet = ct_values[ name = 'P_QUIET' ]-value.
    IF ct_values[ name = 'P_COUNT' ]-value <> mv_p_count.
      ct_values[ name = 'P_COUNT' ]-value = |{ mv_p_count }|.
    ENDIF.
    IF ct_values[ name = 'P_LIKE' ]-value <> mv_p_like.
      ct_values[ name = 'P_LIKE' ]-value = |{ mv_p_like }|.
    ENDIF.
    IF ct_values[ name = 'P_LONG' ]-value <> mv_p_long.
      ct_values[ name = 'P_LONG' ]-value = |{ mv_p_long }|.
    ENDIF.
    IF ct_values[ name = 'P_QUIET' ]-value <> mv_p_quiet.
      ct_values[ name = 'P_QUIET' ]-value = |{ mv_p_quiet }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    mv_p_count = it_values[ name = 'P_COUNT' ]-value.
    mv_p_like = it_values[ name = 'P_LIKE' ]-value.
    mv_p_long = it_values[ name = 'P_LONG' ]-value.
    mv_p_quiet = it_values[ name = 'P_QUIET' ]-value.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'Log with entry count' ).
    mv_p_count = it_values[ name = 'P_COUNT' ]-value.
    mv_p_like = it_values[ name = 'P_LIKE' ]-value.
    mv_p_long = it_values[ name = 'P_LONG' ]-value.
    mv_p_quiet = it_values[ name = 'P_QUIET' ]-value.
* A log display: the entries in an ALV list and their count as a status
* message, as an application log reports "n entries listed". The message can
* be displayed like another type, be made long, or be left out.
    io_session->get_list( )->set_title( 'Log with entry count' ).
    mv_p_count = it_values[ name = 'P_COUNT' ]-value.
    mv_p_like = it_values[ name = 'P_LIKE' ]-value.
    mv_p_long = it_values[ name = 'P_LONG' ]-value.
    mv_p_quiet = it_values[ name = 'P_QUIET' ]-value.
    DO mv_p_count TIMES.
      gs_entry-msgno = sy-index.
      gs_entry-text = |Log entry { sy-index }|.
      APPEND gs_entry TO gt_log.
    ENDDO.
    TRY.
        cl_salv_table=>factory( IMPORTING r_salv_table = go_alv CHANGING t_table = gt_log ).
      CATCH cx_salv_msg INTO gx_msg.
        io_session->message(
          is_message = VALUE #( type = zif_gg_session_types_v1=>message_type_error )
          ia_text    = gx_msg ).
    ENDTRY.
    gv_text = |{ lines( gt_log ) } entries listed|.
    IF mv_p_long = abap_true.
      gv_text = |{ gv_text }; the log holds every message the run wrote, from its start to its end, with the object, the subobject, the external number and the user who started it|.
    ENDIF.
    IF mv_p_quiet = abap_false.
      CASE mv_p_like.
        WHEN 'I'.
          io_session->message(
            is_message = VALUE #( type = zif_gg_session_types_v1=>message_type_success display_like = zif_gg_session_types_v1=>message_type_info )
            ia_text    = gv_text ).
        WHEN 'W'.
          io_session->message(
            is_message = VALUE #( type = zif_gg_session_types_v1=>message_type_success display_like = zif_gg_session_types_v1=>message_type_warning )
            ia_text    = gv_text ).
        WHEN 'E'.
          io_session->message(
            is_message = VALUE #( type = zif_gg_session_types_v1=>message_type_success display_like = zif_gg_session_types_v1=>message_type_error )
            ia_text    = gv_text ).
        WHEN OTHERS.
          io_session->message(
            is_message = VALUE #( type = zif_gg_session_types_v1=>message_type_success )
            ia_text    = gv_text ).
      ENDCASE.
    ENDIF.
    go_alv->display( ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    mv_p_count = it_values[ name = 'P_COUNT' ]-value.
    mv_p_like = it_values[ name = 'P_LIKE' ]-value.
    mv_p_long = it_values[ name = 'P_LONG' ]-value.
    mv_p_quiet = it_values[ name = 'P_QUIET' ]-value.
  ENDMETHOD.

ENDCLASS.
