* Generated by open-abap-gui converter 0.1.0.
* Source object: ZGG_EX_142
* Source file: examples/zgg_ex_142.prog.abap
* Source SHA-256: 6d59379baaad4d305d5f765746313de2680bcc7fd98da8630941d8d338048458
* Target class: ZCL_GG_EX_142
* Manifest schema: 1
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_142 DEFINITION PUBLIC FINAL CREATE PUBLIC FRIENDS zcl_gg_ex_142_h1.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_screen_provider_v1.
    INTERFACES zif_gg_transaction_v1.
    INTERFACES zif_gg_resumable_v1.

  PRIVATE SECTION.
    TYPES ty_nodes TYPE STANDARD TABLE OF mtreesnode WITH DEFAULT KEY.
    DATA go_container TYPE REF TO cl_gui_custom_container.
    DATA go_tree TYPE REF TO cl_gui_simple_tree.
    DATA gt_nodes TYPE ty_nodes.
    DATA gt_events TYPE cntl_simple_events.
    DATA gv_ok_code TYPE sy-ucomm.
    DATA gv_state TYPE c LENGTH 60.
    DATA gv_selected TYPE tv_nodekey.
    DATA gv_return_code TYPE i.

ENDCLASS.

CLASS zcl_gg_ex_142 IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZGG_EX_142' description = 'Tree events' program = 'ZGG_EX_142' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'Tree events' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'Tree events' ).
* selection_changed is a system event: its handler runs without PAI and asks
* for PAI by setting an OK code. node_double_click is an application event: PAI
* runs and dispatches it with cl_gui_cfw=>dispatch.
    io_session->get_list( )->set_title( 'Tree events' ).
    io_session->get_dialog( )->call_screen(
      is_call         = VALUE #( screen = '0100' )
      is_continuation = VALUE #( id = 'AFTER_0100' ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~get_initial_screen.
    rv_screen = '0100'.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~build_screens.
    io_builder->begin_screen( VALUE #( number = '0100' title = 'Tree events' next_screen = '0100' ok_code = 'GV_OK_CODE' width = 800 height = 644 ) ).
    io_builder->add_custom_control( VALUE #( control = VALUE #( name = 'CC_MAIN' position = VALUE #( row = 10 column = 5 width = 780 height = 364 ) ) resizing = VALUE #( vertical = abap_true min_height = 130 horizontal = abap_true min_width = 200 ) ) ).
    io_builder->add_text( VALUE #( control = VALUE #( name = 'LBL_STATE' position = VALUE #( row = 400 column = 5 width = 60 height = 26 ) ) text = 'State' ) ).
    io_builder->add_output_field( VALUE #( control = VALUE #( name = 'GV_STATE' position = VALUE #( row = 400 column = 75 width = 600 height = 26 ) ) data_type = VALUE #( typ = 'C' length = 60 ) ) ).
    io_builder->end_screen( ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~build_flow_logic.
    io_builder->begin_screen( '0100' ).
    io_builder->begin_pbo( ).
    io_builder->add_module( VALUE #( name = 'STATUS_0100' ) ).
    io_builder->end_processing( ).
    io_builder->begin_pai( ).
    io_builder->add_module( VALUE #( name = 'USER_COMMAND_0100' on_input = abap_true ) ).
    io_builder->end_processing( ).
    io_builder->end_screen( ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~initialization.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_STATE' ] ).
      ct_values[ name = 'GV_STATE' ]-value = CONV string( gv_state ).
    ELSE.
      INSERT VALUE #( name = 'GV_STATE' value = CONV string( gv_state ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_RETURN_CODE' ] ).
      ct_values[ name = 'GV_RETURN_CODE' ]-value = CONV string( gv_return_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_RETURN_CODE' value = CONV string( gv_return_code ) ) INTO TABLE ct_values.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_output_module.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      gv_ok_code = CONV #( ct_values[ name = 'GV_OK_CODE' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_STATE' ] ).
      gv_state = CONV #( ct_values[ name = 'GV_STATE' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_RETURN_CODE' ] ).
      gv_return_code = CONV #( ct_values[ name = 'GV_RETURN_CODE' ]-value ).
    ENDIF.
    CASE is_context-module.
      WHEN 'STATUS_0100'.
        IF go_container IS INITIAL.
          CREATE OBJECT go_container EXPORTING container_name = 'CC_MAIN'.
          CREATE OBJECT go_tree EXPORTING parent              = go_container
                                          node_selection_mode = cl_gui_simple_tree=>node_sel_mode_single.
          gt_events = VALUE #( ( eventid = cl_gui_simple_tree=>eventid_selection_changed appl_event = abap_false ) ( eventid = cl_gui_simple_tree=>eventid_node_double_click appl_event = abap_true ) ).
          go_tree->set_registered_events( gt_events ).
          zcl_gg_ex_142_h1=>go_owner = me.
          zcl_gg_ex_142_h1=>go_session = io_session.
          SET HANDLER zcl_gg_ex_142_h1=>on_selection_changed FOR go_tree.
          zcl_gg_ex_142_h1=>go_owner = me.
          zcl_gg_ex_142_h1=>go_session = io_session.
          SET HANDLER zcl_gg_ex_142_h1=>on_node_double_click FOR go_tree.
          gt_nodes = VALUE #( ( node_key = 'ROOT' isfolder = abap_true text = 'Flights' ) ( node_key = 'LH0400' relatkey = 'ROOT' relatship = cl_gui_simple_tree=>relat_last_child text = 'LH 0400' ) ( node_key = 'UA0941' relatkey = 'ROOT' relatship = cl_gui_simple_tree=>relat_last_child text = 'UA 0941' ) ).
          go_tree->add_nodes( table_structure_name = 'MTREESNODE'
                              node_table           = gt_nodes ).
          go_tree->expand_node( 'ROOT' ).
        ENDIF.
      WHEN OTHERS.
        RETURN.
    ENDCASE.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_STATE' ] ).
      ct_values[ name = 'GV_STATE' ]-value = CONV string( gv_state ).
    ELSE.
      INSERT VALUE #( name = 'GV_STATE' value = CONV string( gv_state ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_RETURN_CODE' ] ).
      ct_values[ name = 'GV_RETURN_CODE' ]-value = CONV string( gv_return_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_RETURN_CODE' value = CONV string( gv_return_code ) ) INTO TABLE ct_values.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_input_module.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      gv_ok_code = CONV #( ct_values[ name = 'GV_OK_CODE' ]-value ).
    ENDIF.
    CASE is_context-module.
      WHEN 'USER_COMMAND_0100'.
        cl_gui_cfw=>dispatch( IMPORTING return_code = gv_return_code ).
        IF gv_ok_code = 'SELECTED'.
          gv_state = |Node { gv_selected } selected|.
        ENDIF.
        CLEAR gv_ok_code.
      WHEN OTHERS.
        RETURN.
    ENDCASE.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_STATE' ] ).
      ct_values[ name = 'GV_STATE' ]-value = CONV string( gv_state ).
    ELSE.
      INSERT VALUE #( name = 'GV_STATE' value = CONV string( gv_state ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_RETURN_CODE' ] ).
      ct_values[ name = 'GV_RETURN_CODE' ]-value = CONV string( gv_return_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_RETURN_CODE' value = CONV string( gv_return_code ) ) INTO TABLE ct_values.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_on_value_request.
    DATA ct_values TYPE zif_gg_dynpro_types_v1=>ty_values.
    ct_values = it_values.
    rt_values = io_session->get_compatibility( )->get_value_help_values( ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_on_help_request.
    DATA ct_values TYPE zif_gg_dynpro_types_v1=>ty_values.
    ct_values = it_values.
    IF line_exists( ct_values[ name = 'GV_RESULT' ] ).
      rv_text = ct_values[ name = 'GV_RESULT' ]-value.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_resumable_v1~resume.
* Continuation states are explicit so unsupported suspension semantics remain visible.
    CASE is_resume-continuation-id.
      WHEN 'AFTER_0100'.
        RETURN.
      WHEN OTHERS.
        RETURN.
    ENDCASE.
  ENDMETHOD.

ENDCLASS.
