* Generated by open-abap-gui converter.
* Source object: ZGG_EX_147
* Source file: examples/zgg_ex_147.prog.abap
* Source SHA-256: b16013a4428b60aeb4cdc8f7df9dc3bbc0a32dc7564e4283f76d6c9caa97d45a
* Target class: ZCL_GG_EX_147_H1
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_147_h1 DEFINITION PUBLIC CREATE PUBLIC.

  PUBLIC SECTION.
    METHODS constructor
      IMPORTING
        io_owner   TYPE REF TO zcl_gg_ex_147
        io_session TYPE REF TO zif_gg_session_v1.
    DATA mo_owner TYPE REF TO zcl_gg_ex_147.
    DATA mo_session TYPE REF TO zif_gg_session_v1.
    CLASS-DATA go_owner TYPE REF TO zcl_gg_ex_147.
    CLASS-DATA go_session TYPE REF TO zif_gg_session_v1.
    CLASS-METHODS on_double_click FOR EVENT double_click OF cl_salv_events_table IMPORTING row column.
    CLASS-METHODS on_link_click FOR EVENT link_click OF cl_salv_events_table IMPORTING row.

ENDCLASS.

CLASS zcl_gg_ex_147_h1 IMPLEMENTATION.
  METHOD constructor.
    mo_owner = io_owner.
    mo_session = io_session.
  ENDMETHOD.

  METHOD on_double_click.
    READ TABLE go_owner->gt_flights INTO DATA(ls_flight) INDEX row.
    go_owner->gv_state = |Double click on { ls_flight-carrid } { ls_flight-connid }, column { column }|.
    cl_gui_cfw=>set_new_ok_code( 'EVENT' ).
  ENDMETHOD.

  METHOD on_link_click.
    READ TABLE go_owner->gt_flights INTO DATA(ls_flight) INDEX row.
    go_owner->gv_state = |Airline { ls_flight-carrid } chosen|.
    cl_gui_cfw=>set_new_ok_code( 'EVENT' ).
  ENDMETHOD.
ENDCLASS.
