* Generated by open-abap-gui converter 0.1.0.
* Source object: ZGG_EX_139
* Source file: examples/zgg_ex_139.prog.abap
* Source SHA-256: fc36b0c875a2f0ce22f9a14524d114659a95b399178ee74612fec4213a88334c
* Target class: ZCL_GG_EX_139
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_139 DEFINITION PUBLIC FINAL CREATE PUBLIC FRIENDS zcl_gg_ex_139_h1.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_screen_provider_v1.
    INTERFACES zif_gg_transaction_v1.
    INTERFACES zif_gg_resumable_v1.

  PRIVATE SECTION.
    TYPES: BEGIN OF ty_flight, carrid TYPE c LENGTH 3, connid TYPE n LENGTH 4, seatsocc TYPE i, END OF ty_flight.
    DATA gt_flights TYPE STANDARD TABLE OF ty_flight WITH DEFAULT KEY.
    DATA gt_fieldcat TYPE lvc_t_fcat.
    DATA go_container TYPE REF TO cl_gui_custom_container.
    DATA go_grid TYPE REF TO cl_gui_alv_grid.
    DATA gv_ok_code TYPE sy-ucomm.
    DATA gv_state TYPE c LENGTH 60.
    METHODS output_modules
      IMPORTING
        is_context TYPE zif_gg_dynpro_types_v1=>ty_module_context
        io_session TYPE REF TO zif_gg_session_v1
      CHANGING
        ct_values  TYPE zif_gg_dynpro_types_v1=>ty_values
        ct_states  TYPE zif_gg_dynpro_types_v1=>ty_states.
    METHODS input_modules
      IMPORTING
        is_context TYPE zif_gg_dynpro_types_v1=>ty_module_context
        io_session TYPE REF TO zif_gg_session_v1
      CHANGING
        ct_values  TYPE zif_gg_dynpro_types_v1=>ty_values.

ENDCLASS.

CLASS zcl_gg_ex_139 IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZGG_EX_139' description = 'ALV toolbar events' program = 'ZGG_EX_139' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'ALV toolbar events' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'ALV toolbar events' ).
    gt_flights = VALUE #( ( carrid = 'LH' connid = '0400' seatsocc = 180 ) ( carrid = 'UA' connid = '0941' seatsocc = 210 ) ( carrid = 'AF' connid = '0010' seatsocc = 160 ) ).
    io_session->get_dialog( )->call_screen(
      is_call         = VALUE #( screen = '0100' )
      is_continuation = VALUE #( id = 'AFTER_0100' ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~get_initial_screen.
    rv_screen = '0100'.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~build_screens.
    io_builder->begin_screen( VALUE #( number = '0100' title = 'ALV toolbar events' next_screen = '0100' ok_code = 'GV_OK_CODE' width = 800 height = 644 ) ).
    io_builder->add_custom_control( VALUE #( control = VALUE #( name = 'CC_MAIN' position = VALUE #( row = 10 column = 5 width = 780 height = 364 ) ) resizing = VALUE #( vertical = abap_true min_height = 130 horizontal = abap_true min_width = 200 ) ) ).
    io_builder->add_text( VALUE #( control = VALUE #( name = 'LBL_STATE' position = VALUE #( row = 400 column = 5 width = 60 height = 26 ) ) text = 'State' ) ).
    io_builder->add_output_field( VALUE #( control = VALUE #( name = 'GV_STATE' position = VALUE #( row = 400 column = 75 width = 600 height = 26 ) ) data_type = VALUE #( typ = 'C' length = 60 ) ) ).
    io_builder->end_screen( ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~build_flow_logic.
    io_builder->begin_screen( '0100' ).
    io_builder->begin_pbo( ).
    io_builder->add_module( VALUE #( name = 'STATUS_0100' ) ).
    io_builder->end_processing( ).
    io_builder->begin_pai( ).
    io_builder->add_module( VALUE #( name = 'USER_COMMAND_0100' on_input = abap_true ) ).
    io_builder->end_processing( ).
    io_builder->end_screen( ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~initialization.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_STATE' ] ).
      ct_values[ name = 'GV_STATE' ]-value = CONV string( gv_state ).
    ELSE.
      INSERT VALUE #( name = 'GV_STATE' value = CONV string( gv_state ) ) INTO TABLE ct_values.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_output_module.
    DATA lx_unwind TYPE REF TO zcx_gg_control_flow.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      gv_ok_code = CONV #( ct_values[ name = 'GV_OK_CODE' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_STATE' ] ).
      gv_state = CONV #( ct_values[ name = 'GV_STATE' ]-value ).
    ENDIF.
    TRY.
        output_modules(
          EXPORTING
            is_context = is_context
            io_session = io_session
          CHANGING
            ct_values  = ct_values
            ct_states  = ct_states ).
      CATCH zcx_gg_control_flow INTO lx_unwind.
    ENDTRY.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_STATE' ] ).
      ct_values[ name = 'GV_STATE' ]-value = CONV string( gv_state ).
    ELSE.
      INSERT VALUE #( name = 'GV_STATE' value = CONV string( gv_state ) ) INTO TABLE ct_values.
    ENDIF.
    IF lx_unwind IS BOUND.
      RAISE EXCEPTION lx_unwind.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_input_module.
    DATA lx_unwind TYPE REF TO zcx_gg_control_flow.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      gv_ok_code = CONV #( ct_values[ name = 'GV_OK_CODE' ]-value ).
    ENDIF.
    TRY.
        input_modules(
          EXPORTING
            is_context = is_context
            io_session = io_session
          CHANGING
            ct_values  = ct_values ).
      CATCH zcx_gg_control_flow INTO lx_unwind.
    ENDTRY.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_STATE' ] ).
      ct_values[ name = 'GV_STATE' ]-value = CONV string( gv_state ).
    ELSE.
      INSERT VALUE #( name = 'GV_STATE' value = CONV string( gv_state ) ) INTO TABLE ct_values.
    ENDIF.
    IF lx_unwind IS BOUND.
      RAISE EXCEPTION lx_unwind.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_on_value_request.
    DATA ct_values TYPE zif_gg_dynpro_types_v1=>ty_values.
    ct_values = it_values.
    rt_values = io_session->get_compatibility( )->get_value_help_values( ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_on_help_request.
    DATA ct_values TYPE zif_gg_dynpro_types_v1=>ty_values.
    ct_values = it_values.
    IF line_exists( ct_values[ name = 'GV_RESULT' ] ).
      rv_text = ct_values[ name = 'GV_RESULT' ]-value.
    ENDIF.
  ENDMETHOD.

  METHOD output_modules.
    CASE is_context-module.
      WHEN 'STATUS_0100'.
        IF go_container IS INITIAL.
          CREATE OBJECT go_container EXPORTING container_name = 'CC_MAIN'.
          CREATE OBJECT go_grid EXPORTING i_parent      = go_container
                                          i_appl_events = abap_true.
          gt_fieldcat = VALUE #( ( fieldname = 'CARRID' coltext = 'Airline' hotspot = abap_true outputlen = 7 ) ( fieldname = 'CONNID' coltext = 'Flight' outputlen = 6 ) ( fieldname = 'SEATSOCC' coltext = 'Occupied' outputlen = 8 ) ).
          zcl_gg_ex_139_h1=>go_owner = me.
          zcl_gg_ex_139_h1=>go_session = io_session.
          SET HANDLER zcl_gg_ex_139_h1=>on_toolbar FOR go_grid.
          zcl_gg_ex_139_h1=>go_owner = me.
          zcl_gg_ex_139_h1=>go_session = io_session.
          SET HANDLER zcl_gg_ex_139_h1=>on_user_command FOR go_grid.
          zcl_gg_ex_139_h1=>go_owner = me.
          zcl_gg_ex_139_h1=>go_session = io_session.
          SET HANDLER zcl_gg_ex_139_h1=>on_double_click FOR go_grid.
          zcl_gg_ex_139_h1=>go_owner = me.
          zcl_gg_ex_139_h1=>go_session = io_session.
          SET HANDLER zcl_gg_ex_139_h1=>on_hotspot_click FOR go_grid.
          go_grid->set_table_for_first_display( CHANGING it_outtab = gt_flights it_fieldcatalog = gt_fieldcat ).
          gv_state = 'Use the Details button, a hotspot or a double click'.
        ENDIF.
      WHEN OTHERS.
        RETURN.
    ENDCASE.
  ENDMETHOD.

  METHOD input_modules.
    CASE is_context-module.
      WHEN 'USER_COMMAND_0100'.
        CLEAR gv_ok_code.
      WHEN OTHERS.
        RETURN.
    ENDCASE.
  ENDMETHOD.

  METHOD zif_gg_resumable_v1~resume.
* Continuation states are explicit so unsupported suspension semantics remain visible.
    CASE is_resume-continuation-id.
      WHEN 'AFTER_0100'.
        RETURN.
      WHEN OTHERS.
        RETURN.
    ENDCASE.
  ENDMETHOD.

ENDCLASS.
