* Generated by open-abap-gui converter 0.1.0.
* Source object: ZGG_EX_152
* Source file: examples/zgg_ex_152.prog.abap
* Source SHA-256: 32a316f57b74fbaa74cdbf50006f06479d478b986cefa225a4b140365f1d0bfd
* Target class: ZCL_GG_EX_152_H1
* Manifest schema: 1
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_152_h1 DEFINITION PUBLIC CREATE PUBLIC.

  PUBLIC SECTION.
    METHODS constructor
      IMPORTING
        io_owner   TYPE REF TO zcl_gg_ex_152
        io_session TYPE REF TO zif_gg_session_v1.
    DATA mo_owner TYPE REF TO zcl_gg_ex_152.
    DATA mo_session TYPE REF TO zif_gg_session_v1.
    CLASS-DATA go_owner TYPE REF TO zcl_gg_ex_152.
    CLASS-DATA go_session TYPE REF TO zif_gg_session_v1.
    CLASS-METHODS on_finished FOR EVENT finished OF cl_gui_timer.

ENDCLASS.

CLASS zcl_gg_ex_152_h1 IMPLEMENTATION.
  METHOD constructor.
    mo_owner = io_owner.
    mo_session = io_session.
  ENDMETHOD.

  METHOD on_finished.
    go_owner->gv_seconds = go_owner->gv_seconds + 1.
    go_owner->go_timer->run( ).
    cl_gui_cfw=>set_new_ok_code( 'TICK' ).
  ENDMETHOD.
ENDCLASS.
