* Generated by open-abap-gui converter 0.1.0.
* Source object: ZGG_EX_121
* Source file: examples/zgg_ex_121.prog.abap
* Source SHA-256: ce0fc5f87e3e6beadc3ea4091e4daef61cb575527681c863e84d97022c5198a6
* Target class: ZCL_GG_EX_121_H1
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_121_h1 DEFINITION PUBLIC CREATE PUBLIC.

  PUBLIC SECTION.
    METHODS constructor
      IMPORTING
        io_owner   TYPE REF TO zcl_gg_ex_121
        io_session TYPE REF TO zif_gg_session_v1.
    DATA mo_owner TYPE REF TO zcl_gg_ex_121.
    DATA mo_session TYPE REF TO zif_gg_session_v1.
    CLASS-DATA go_owner TYPE REF TO zcl_gg_ex_121.
    CLASS-DATA go_session TYPE REF TO zif_gg_session_v1.
    CLASS-METHODS on_close FOR EVENT close OF cl_gui_dialogbox_container IMPORTING sender.

ENDCLASS.

CLASS zcl_gg_ex_121_h1 IMPLEMENTATION.
  METHOD constructor.
    mo_owner = io_owner.
    mo_session = io_session.
  ENDMETHOD.

  METHOD on_close.
    sender->free( ).
    CLEAR go_owner->go_dialog.
    CLEAR go_owner->go_editor.
    go_owner->gv_state = 'Dialog box closed'.
  ENDMETHOD.
ENDCLASS.
