* Generated by open-abap-gui converter 0.1.0.
* Source object: ZGG_EX_068
* Source file: examples/zgg_ex_068.prog.abap
* Source SHA-256: b29fe7fb7305ec5d494cb02cacd4cbb1dfc2898b4baa1a30010f0c5b8f811099
* Target class: ZCL_GG_EX_068
* Manifest schema: 1
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_068 DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_transaction_v1.
    INTERFACES zif_gg_list_processing_v1.

  PRIVATE SECTION.
    DATA mv_p_detail TYPE c LENGTH 20.
    DATA mv_p_req TYPE c LENGTH 20.
    DATA mv_p_show TYPE c LENGTH 1.

ENDCLASS.

CLASS zcl_gg_ex_068 IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZGG_EX_068' description = 'Dynamic visible input and required state' program = 'ZGG_EX_068' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'Dynamic visible input and required state' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    ro_list_processing = me.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    io_builder->add_checkbox( VALUE #( name = 'P_SHOW' text = 'Show detail' ucomm = 'TOGGLE' ) ).
    io_builder->add_parameter( VALUE #( name = 'P_DETAIL' text = 'Detail' data_type = VALUE #( typ = 'C' length = 20 ) modif_id = 'DET' ) ).
    io_builder->add_parameter( VALUE #( name = 'P_REQ' text = 'Required value' data_type = VALUE #( typ = 'C' length = 20 ) obligatory = abap_true ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    mv_p_detail = ct_values[ name = 'P_DETAIL' ]-value.
    mv_p_req = ct_values[ name = 'P_REQ' ]-value.
    mv_p_show = ct_values[ name = 'P_SHOW' ]-value.
    IF ct_values[ name = 'P_DETAIL' ]-value <> mv_p_detail.
      ct_values[ name = 'P_DETAIL' ]-value = |{ mv_p_detail }|.
    ENDIF.
    IF ct_values[ name = 'P_REQ' ]-value <> mv_p_req.
      ct_values[ name = 'P_REQ' ]-value = |{ mv_p_req }|.
    ENDIF.
    IF ct_values[ name = 'P_SHOW' ]-value <> mv_p_show.
      ct_values[ name = 'P_SHOW' ]-value = |{ mv_p_show }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    mv_p_detail = ct_values[ name = 'P_DETAIL' ]-value.
    mv_p_req = ct_values[ name = 'P_REQ' ]-value.
    mv_p_show = ct_values[ name = 'P_SHOW' ]-value.
    LOOP AT ct_states ASSIGNING FIELD-SYMBOL(<ls_state>).
      IF <ls_state>-modif_id = 'DET'.
        IF mv_p_show = abap_true.
          <ls_state>-visible = abap_true.
          <ls_state>-obligatory = abap_true.
        ELSE.
          <ls_state>-visible = abap_false.
        ENDIF.
* SCREEN state is already changed through <ls_state>.
      ENDIF.
    ENDLOOP.
    IF ct_values[ name = 'P_DETAIL' ]-value <> mv_p_detail.
      ct_values[ name = 'P_DETAIL' ]-value = |{ mv_p_detail }|.
    ENDIF.
    IF ct_values[ name = 'P_REQ' ]-value <> mv_p_req.
      ct_values[ name = 'P_REQ' ]-value = |{ mv_p_req }|.
    ENDIF.
    IF ct_values[ name = 'P_SHOW' ]-value <> mv_p_show.
      ct_values[ name = 'P_SHOW' ]-value = |{ mv_p_show }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    mv_p_detail = ct_values[ name = 'P_DETAIL' ]-value.
    mv_p_req = ct_values[ name = 'P_REQ' ]-value.
    mv_p_show = ct_values[ name = 'P_SHOW' ]-value.
    IF ct_values[ name = 'P_DETAIL' ]-value <> mv_p_detail.
      ct_values[ name = 'P_DETAIL' ]-value = |{ mv_p_detail }|.
    ENDIF.
    IF ct_values[ name = 'P_REQ' ]-value <> mv_p_req.
      ct_values[ name = 'P_REQ' ]-value = |{ mv_p_req }|.
    ENDIF.
    IF ct_values[ name = 'P_SHOW' ]-value <> mv_p_show.
      ct_values[ name = 'P_SHOW' ]-value = |{ mv_p_show }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    mv_p_detail = ct_values[ name = 'P_DETAIL' ]-value.
    mv_p_req = ct_values[ name = 'P_REQ' ]-value.
    mv_p_show = ct_values[ name = 'P_SHOW' ]-value.
    IF ct_values[ name = 'P_DETAIL' ]-value <> mv_p_detail.
      ct_values[ name = 'P_DETAIL' ]-value = |{ mv_p_detail }|.
    ENDIF.
    IF ct_values[ name = 'P_REQ' ]-value <> mv_p_req.
      ct_values[ name = 'P_REQ' ]-value = |{ mv_p_req }|.
    ENDIF.
    IF ct_values[ name = 'P_SHOW' ]-value <> mv_p_show.
      ct_values[ name = 'P_SHOW' ]-value = |{ mv_p_show }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    mv_p_detail = ct_values[ name = 'P_DETAIL' ]-value.
    mv_p_req = ct_values[ name = 'P_REQ' ]-value.
    mv_p_show = ct_values[ name = 'P_SHOW' ]-value.
    IF ct_values[ name = 'P_DETAIL' ]-value <> mv_p_detail.
      ct_values[ name = 'P_DETAIL' ]-value = |{ mv_p_detail }|.
    ENDIF.
    IF ct_values[ name = 'P_REQ' ]-value <> mv_p_req.
      ct_values[ name = 'P_REQ' ]-value = |{ mv_p_req }|.
    ENDIF.
    IF ct_values[ name = 'P_SHOW' ]-value <> mv_p_show.
      ct_values[ name = 'P_SHOW' ]-value = |{ mv_p_show }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    mv_p_detail = ct_values[ name = 'P_DETAIL' ]-value.
    mv_p_req = ct_values[ name = 'P_REQ' ]-value.
    mv_p_show = ct_values[ name = 'P_SHOW' ]-value.
    IF ct_values[ name = 'P_DETAIL' ]-value <> mv_p_detail.
      ct_values[ name = 'P_DETAIL' ]-value = |{ mv_p_detail }|.
    ENDIF.
    IF ct_values[ name = 'P_REQ' ]-value <> mv_p_req.
      ct_values[ name = 'P_REQ' ]-value = |{ mv_p_req }|.
    ENDIF.
    IF ct_values[ name = 'P_SHOW' ]-value <> mv_p_show.
      ct_values[ name = 'P_SHOW' ]-value = |{ mv_p_show }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    mv_p_detail = ct_values[ name = 'P_DETAIL' ]-value.
    mv_p_req = ct_values[ name = 'P_REQ' ]-value.
    mv_p_show = ct_values[ name = 'P_SHOW' ]-value.
    IF ct_values[ name = 'P_DETAIL' ]-value <> mv_p_detail.
      ct_values[ name = 'P_DETAIL' ]-value = |{ mv_p_detail }|.
    ENDIF.
    IF ct_values[ name = 'P_REQ' ]-value <> mv_p_req.
      ct_values[ name = 'P_REQ' ]-value = |{ mv_p_req }|.
    ENDIF.
    IF ct_values[ name = 'P_SHOW' ]-value <> mv_p_show.
      ct_values[ name = 'P_SHOW' ]-value = |{ mv_p_show }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    mv_p_detail = it_values[ name = 'P_DETAIL' ]-value.
    mv_p_req = it_values[ name = 'P_REQ' ]-value.
    mv_p_show = it_values[ name = 'P_SHOW' ]-value.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'Dynamic visible input and required state' ).
    DATA(lo_writer) = io_session->get_list( )->get_writer( ).
    mv_p_detail = it_values[ name = 'P_DETAIL' ]-value.
    mv_p_req = it_values[ name = 'P_REQ' ]-value.
    mv_p_show = it_values[ name = 'P_SHOW' ]-value.
    lo_writer->write_field( VALUE #( text = |{ mv_p_req }| ) ).
    lo_writer->write_field( VALUE #( text = |{ mv_p_detail }| placement = VALUE #( new_line = abap_true ) ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    mv_p_detail = it_values[ name = 'P_DETAIL' ]-value.
    mv_p_req = it_values[ name = 'P_REQ' ]-value.
    mv_p_show = it_values[ name = 'P_SHOW' ]-value.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~get_settings.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~end_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page_during_line_sel.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_line_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_user_command.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_pf.
    RETURN.
  ENDMETHOD.

ENDCLASS.
