* Generated by open-abap-gui converter 0.1.0.
* Source object: ZGG_EX_027
* Source file: examples/zgg_ex_027.prog.abap
* Source SHA-256: 49713c88a59eee68ba6d3a44d4522447c6296bdb96a2f6eb75a2095226e0705d
* Target class: ZCL_GG_EX_027
* Manifest schema: 1
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_027 DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_transaction_v1.

  PRIVATE SECTION.
    DATA text TYPE string.
    DATA mv_p_b TYPE c LENGTH 1.

ENDCLASS.

CLASS zcl_gg_ex_027 IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZGG_EX_027' description = 'Selection-screen BEGIN OF SCREEN' program = 'ZGG_EX_027' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'Selection-screen BEGIN OF SCREEN' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    io_builder->begin_screen( VALUE #( number = '0500' as_window = abap_true ) ).
    io_builder->add_parameter( VALUE #( name = 'P_B' text = 'B' data_type = VALUE #( typ = 'C' length = 1 ) ) ).
    io_builder->end_screen( ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    mv_p_b = ct_values[ name = 'P_B' ]-value.
    IF ct_values[ name = 'P_B' ]-value <> mv_p_b.
      ct_values[ name = 'P_B' ]-value = |{ mv_p_b }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    mv_p_b = ct_values[ name = 'P_B' ]-value.
    IF ct_values[ name = 'P_B' ]-value <> mv_p_b.
      ct_values[ name = 'P_B' ]-value = |{ mv_p_b }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    mv_p_b = ct_values[ name = 'P_B' ]-value.
    IF ct_values[ name = 'P_B' ]-value <> mv_p_b.
      ct_values[ name = 'P_B' ]-value = |{ mv_p_b }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    mv_p_b = ct_values[ name = 'P_B' ]-value.
    IF ct_values[ name = 'P_B' ]-value <> mv_p_b.
      ct_values[ name = 'P_B' ]-value = |{ mv_p_b }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    mv_p_b = ct_values[ name = 'P_B' ]-value.
    IF ct_values[ name = 'P_B' ]-value <> mv_p_b.
      ct_values[ name = 'P_B' ]-value = |{ mv_p_b }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    mv_p_b = ct_values[ name = 'P_B' ]-value.
    IF ct_values[ name = 'P_B' ]-value <> mv_p_b.
      ct_values[ name = 'P_B' ]-value = |{ mv_p_b }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    mv_p_b = ct_values[ name = 'P_B' ]-value.
    IF ct_values[ name = 'P_B' ]-value <> mv_p_b.
      ct_values[ name = 'P_B' ]-value = |{ mv_p_b }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    mv_p_b = it_values[ name = 'P_B' ]-value.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'Selection-screen BEGIN OF SCREEN' ).
    mv_p_b = it_values[ name = 'P_B' ]-value.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    mv_p_b = it_values[ name = 'P_B' ]-value.
  ENDMETHOD.

ENDCLASS.
