* Generated by open-abap-gui converter 0.1.0.
* Source object: ZGG_EX_080
* Source file: examples/zgg_ex_080.prog.abap
* Source SHA-256: 468ebcf9a62aa9dd005fa2cffd082420bad1dbe28ee92c42bbf1e084c22103c3
* Target class: ZCL_GG_EX_080
* Manifest schema: 1
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_080 DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_transaction_v1.
    INTERFACES zif_gg_list_processing_v1.

  PRIVATE SECTION.
    DATA zsflight TYPE zsflight.
    DATA gv_order TYPE string.
    DATA validation TYPE string.
    DATA mv_p_fld TYPE c LENGTH 20.
    DATA mv_p_rad1 TYPE c LENGTH 1.
    DATA mv_p_rad2 TYPE c LENGTH 1.
    DATA mv_p_req TYPE c LENGTH 20.
    DATA mv_s_end LIKE RANGE OF zsflight-carrid.
    METHODS form_record
      IMPORTING
        io_session TYPE REF TO zif_gg_session_v1
        iv_step    TYPE csequence.

ENDCLASS.

CLASS zcl_gg_ex_080 IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZGG_EX_080' description = 'Selection validation order' program = 'ZGG_EX_080' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'Selection validation order' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    ro_list_processing = me.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    io_builder->add_parameter( VALUE #( name = 'P_FLD' text = 'Field' data_type = VALUE #( typ = 'C' length = 20 ) ) ).
    io_builder->begin_block( VALUE #( name = 'B_VAL' title = 'Validation' with_frame = abap_true ) ).
    io_builder->add_radiobutton( VALUE #( name = 'P_RAD1' text = 'First option' radio_group = 'VG1' default = abap_true ) ).
    io_builder->add_radiobutton( VALUE #( name = 'P_RAD2' text = 'Second option' radio_group = 'VG1' ) ).
    io_builder->end_block( ).
    io_builder->add_select_option( VALUE #( name = 'S_END' text = 'End range' data_type = VALUE #( typ = 'C' length = 3 ) default = VALUE #( sign = 'I' option = 'EQ' low = 'AA' ) ) ).
    io_builder->add_parameter( VALUE #( name = 'P_REQ' text = 'Required value' data_type = VALUE #( typ = 'C' length = 20 ) obligatory = abap_true ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    mv_p_fld = ct_values[ name = 'P_FLD' ]-value.
    mv_p_rad1 = ct_values[ name = 'P_RAD1' ]-value.
    mv_p_rad2 = ct_values[ name = 'P_RAD2' ]-value.
    mv_p_req = ct_values[ name = 'P_REQ' ]-value.
    mv_s_end = CORRESPONDING #( ct_values[ name = 'S_END' ]-ranges ).
    IF ct_values[ name = 'P_FLD' ]-value <> mv_p_fld.
      ct_values[ name = 'P_FLD' ]-value = |{ mv_p_fld }|.
    ENDIF.
    IF ct_values[ name = 'P_RAD1' ]-value <> mv_p_rad1.
      ct_values[ name = 'P_RAD1' ]-value = |{ mv_p_rad1 }|.
    ENDIF.
    IF ct_values[ name = 'P_RAD2' ]-value <> mv_p_rad2.
      ct_values[ name = 'P_RAD2' ]-value = |{ mv_p_rad2 }|.
    ENDIF.
    IF ct_values[ name = 'P_REQ' ]-value <> mv_p_req.
      ct_values[ name = 'P_REQ' ]-value = |{ mv_p_req }|.
    ENDIF.
    DATA(lt_ggconv_s_end) = mv_s_end.
    lt_ggconv_s_end = CORRESPONDING #( ct_values[ name = 'S_END' ]-ranges ).
    IF lt_ggconv_s_end <> mv_s_end.
      ct_values[ name = 'S_END' ]-ranges = CORRESPONDING #( mv_s_end ).
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    mv_p_fld = ct_values[ name = 'P_FLD' ]-value.
    mv_p_rad1 = ct_values[ name = 'P_RAD1' ]-value.
    mv_p_rad2 = ct_values[ name = 'P_RAD2' ]-value.
    mv_p_req = ct_values[ name = 'P_REQ' ]-value.
    mv_s_end = CORRESPONDING #( ct_values[ name = 'S_END' ]-ranges ).
    CLEAR gv_order.
    IF ct_values[ name = 'P_FLD' ]-value <> mv_p_fld.
      ct_values[ name = 'P_FLD' ]-value = |{ mv_p_fld }|.
    ENDIF.
    IF ct_values[ name = 'P_RAD1' ]-value <> mv_p_rad1.
      ct_values[ name = 'P_RAD1' ]-value = |{ mv_p_rad1 }|.
    ENDIF.
    IF ct_values[ name = 'P_RAD2' ]-value <> mv_p_rad2.
      ct_values[ name = 'P_RAD2' ]-value = |{ mv_p_rad2 }|.
    ENDIF.
    IF ct_values[ name = 'P_REQ' ]-value <> mv_p_req.
      ct_values[ name = 'P_REQ' ]-value = |{ mv_p_req }|.
    ENDIF.
    DATA(lt_ggconv_s_end) = mv_s_end.
    lt_ggconv_s_end = CORRESPONDING #( ct_values[ name = 'S_END' ]-ranges ).
    IF lt_ggconv_s_end <> mv_s_end.
      ct_values[ name = 'S_END' ]-ranges = CORRESPONDING #( mv_s_end ).
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    mv_p_fld = ct_values[ name = 'P_FLD' ]-value.
    mv_p_rad1 = ct_values[ name = 'P_RAD1' ]-value.
    mv_p_rad2 = ct_values[ name = 'P_RAD2' ]-value.
    mv_p_req = ct_values[ name = 'P_REQ' ]-value.
    mv_s_end = CORRESPONDING #( ct_values[ name = 'S_END' ]-ranges ).
    form_record(
      io_session = io_session
      iv_step    = 'SCREEN' ).
    IF ct_values[ name = 'P_FLD' ]-value <> mv_p_fld.
      ct_values[ name = 'P_FLD' ]-value = |{ mv_p_fld }|.
    ENDIF.
    IF ct_values[ name = 'P_RAD1' ]-value <> mv_p_rad1.
      ct_values[ name = 'P_RAD1' ]-value = |{ mv_p_rad1 }|.
    ENDIF.
    IF ct_values[ name = 'P_RAD2' ]-value <> mv_p_rad2.
      ct_values[ name = 'P_RAD2' ]-value = |{ mv_p_rad2 }|.
    ENDIF.
    IF ct_values[ name = 'P_REQ' ]-value <> mv_p_req.
      ct_values[ name = 'P_REQ' ]-value = |{ mv_p_req }|.
    ENDIF.
    DATA(lt_ggconv_s_end) = mv_s_end.
    lt_ggconv_s_end = CORRESPONDING #( ct_values[ name = 'S_END' ]-ranges ).
    IF lt_ggconv_s_end <> mv_s_end.
      ct_values[ name = 'S_END' ]-ranges = CORRESPONDING #( mv_s_end ).
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    DATA(lt_ggconv_s_end) = mv_s_end.
    lt_ggconv_s_end = CORRESPONDING #( ct_values[ name = 'S_END' ]-ranges ).
    IF lt_ggconv_s_end <> mv_s_end.
      ct_values[ name = 'S_END' ]-ranges = CORRESPONDING #( mv_s_end ).
    ENDIF.
    IF iv_name = 'P_FLD'.
      mv_p_fld = ct_values[ name = 'P_FLD' ]-value.
      mv_p_rad1 = ct_values[ name = 'P_RAD1' ]-value.
      mv_p_rad2 = ct_values[ name = 'P_RAD2' ]-value.
      mv_p_req = ct_values[ name = 'P_REQ' ]-value.
      mv_s_end = CORRESPONDING #( ct_values[ name = 'S_END' ]-ranges ).
      form_record(
        io_session = io_session
        iv_step    = 'FIELD' ).
      IF mv_p_fld = 'bad'.
        io_session->message( VALUE #( type = zif_gg_session_types_v1=>message_type_error text = 'Field validation failed' field = iv_name ) ).
      ENDIF.
      IF ct_values[ name = 'P_FLD' ]-value <> mv_p_fld.
        ct_values[ name = 'P_FLD' ]-value = |{ mv_p_fld }|.
      ENDIF.
      IF ct_values[ name = 'P_RAD1' ]-value <> mv_p_rad1.
        ct_values[ name = 'P_RAD1' ]-value = |{ mv_p_rad1 }|.
      ENDIF.
      IF ct_values[ name = 'P_RAD2' ]-value <> mv_p_rad2.
        ct_values[ name = 'P_RAD2' ]-value = |{ mv_p_rad2 }|.
      ENDIF.
      IF ct_values[ name = 'P_REQ' ]-value <> mv_p_req.
        ct_values[ name = 'P_REQ' ]-value = |{ mv_p_req }|.
      ENDIF.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    mv_p_fld = ct_values[ name = 'P_FLD' ]-value.
    mv_p_rad1 = ct_values[ name = 'P_RAD1' ]-value.
    mv_p_rad2 = ct_values[ name = 'P_RAD2' ]-value.
    mv_p_req = ct_values[ name = 'P_REQ' ]-value.
    mv_s_end = CORRESPONDING #( ct_values[ name = 'S_END' ]-ranges ).
    form_record(
      io_session = io_session
      iv_step    = 'END' ).
    IF ct_values[ name = 'P_FLD' ]-value <> mv_p_fld.
      ct_values[ name = 'P_FLD' ]-value = |{ mv_p_fld }|.
    ENDIF.
    IF ct_values[ name = 'P_RAD1' ]-value <> mv_p_rad1.
      ct_values[ name = 'P_RAD1' ]-value = |{ mv_p_rad1 }|.
    ENDIF.
    IF ct_values[ name = 'P_RAD2' ]-value <> mv_p_rad2.
      ct_values[ name = 'P_RAD2' ]-value = |{ mv_p_rad2 }|.
    ENDIF.
    IF ct_values[ name = 'P_REQ' ]-value <> mv_p_req.
      ct_values[ name = 'P_REQ' ]-value = |{ mv_p_req }|.
    ENDIF.
    DATA(lt_ggconv_s_end) = mv_s_end.
    lt_ggconv_s_end = CORRESPONDING #( ct_values[ name = 'S_END' ]-ranges ).
    IF lt_ggconv_s_end <> mv_s_end.
      ct_values[ name = 'S_END' ]-ranges = CORRESPONDING #( mv_s_end ).
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    DATA(lt_ggconv_s_end) = mv_s_end.
    lt_ggconv_s_end = CORRESPONDING #( ct_values[ name = 'S_END' ]-ranges ).
    IF lt_ggconv_s_end <> mv_s_end.
      ct_values[ name = 'S_END' ]-ranges = CORRESPONDING #( mv_s_end ).
    ENDIF.
    IF iv_block = 'B_VAL'.
      mv_p_fld = ct_values[ name = 'P_FLD' ]-value.
      mv_p_rad1 = ct_values[ name = 'P_RAD1' ]-value.
      mv_p_rad2 = ct_values[ name = 'P_RAD2' ]-value.
      mv_p_req = ct_values[ name = 'P_REQ' ]-value.
      mv_s_end = CORRESPONDING #( ct_values[ name = 'S_END' ]-ranges ).
      form_record(
        io_session = io_session
        iv_step    = 'BLOCK' ).
      IF ct_values[ name = 'P_FLD' ]-value <> mv_p_fld.
        ct_values[ name = 'P_FLD' ]-value = |{ mv_p_fld }|.
      ENDIF.
      IF ct_values[ name = 'P_RAD1' ]-value <> mv_p_rad1.
        ct_values[ name = 'P_RAD1' ]-value = |{ mv_p_rad1 }|.
      ENDIF.
      IF ct_values[ name = 'P_RAD2' ]-value <> mv_p_rad2.
        ct_values[ name = 'P_RAD2' ]-value = |{ mv_p_rad2 }|.
      ENDIF.
      IF ct_values[ name = 'P_REQ' ]-value <> mv_p_req.
        ct_values[ name = 'P_REQ' ]-value = |{ mv_p_req }|.
      ENDIF.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    DATA(lt_ggconv_s_end) = mv_s_end.
    lt_ggconv_s_end = CORRESPONDING #( ct_values[ name = 'S_END' ]-ranges ).
    IF lt_ggconv_s_end <> mv_s_end.
      ct_values[ name = 'S_END' ]-ranges = CORRESPONDING #( mv_s_end ).
    ENDIF.
    IF iv_group = 'VG1'.
      mv_p_fld = ct_values[ name = 'P_FLD' ]-value.
      mv_p_rad1 = ct_values[ name = 'P_RAD1' ]-value.
      mv_p_rad2 = ct_values[ name = 'P_RAD2' ]-value.
      mv_p_req = ct_values[ name = 'P_REQ' ]-value.
      mv_s_end = CORRESPONDING #( ct_values[ name = 'S_END' ]-ranges ).
      form_record(
        io_session = io_session
        iv_step    = 'RADIO' ).
      IF ct_values[ name = 'P_FLD' ]-value <> mv_p_fld.
        ct_values[ name = 'P_FLD' ]-value = |{ mv_p_fld }|.
      ENDIF.
      IF ct_values[ name = 'P_RAD1' ]-value <> mv_p_rad1.
        ct_values[ name = 'P_RAD1' ]-value = |{ mv_p_rad1 }|.
      ENDIF.
      IF ct_values[ name = 'P_RAD2' ]-value <> mv_p_rad2.
        ct_values[ name = 'P_RAD2' ]-value = |{ mv_p_rad2 }|.
      ENDIF.
      IF ct_values[ name = 'P_REQ' ]-value <> mv_p_req.
        ct_values[ name = 'P_REQ' ]-value = |{ mv_p_req }|.
      ENDIF.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    mv_p_fld = it_values[ name = 'P_FLD' ]-value.
    mv_p_rad1 = it_values[ name = 'P_RAD1' ]-value.
    mv_p_rad2 = it_values[ name = 'P_RAD2' ]-value.
    mv_p_req = it_values[ name = 'P_REQ' ]-value.
    mv_s_end = CORRESPONDING #( it_values[ name = 'S_END' ]-ranges ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    mv_p_fld = it_values[ name = 'P_FLD' ]-value.
    mv_p_rad1 = it_values[ name = 'P_RAD1' ]-value.
    mv_p_rad2 = it_values[ name = 'P_RAD2' ]-value.
    mv_p_req = it_values[ name = 'P_REQ' ]-value.
    mv_s_end = CORRESPONDING #( it_values[ name = 'S_END' ]-ranges ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    mv_p_fld = it_values[ name = 'P_FLD' ]-value.
    mv_p_rad1 = it_values[ name = 'P_RAD1' ]-value.
    mv_p_rad2 = it_values[ name = 'P_RAD2' ]-value.
    mv_p_req = it_values[ name = 'P_REQ' ]-value.
    mv_s_end = CORRESPONDING #( it_values[ name = 'S_END' ]-ranges ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'Selection validation order' ).
    DATA(lo_writer) = io_session->get_list( )->get_writer( ).
    mv_p_fld = it_values[ name = 'P_FLD' ]-value.
    mv_p_rad1 = it_values[ name = 'P_RAD1' ]-value.
    mv_p_rad2 = it_values[ name = 'P_RAD2' ]-value.
    mv_p_req = it_values[ name = 'P_REQ' ]-value.
    mv_s_end = CORRESPONDING #( it_values[ name = 'S_END' ]-ranges ).
    lo_writer->write_field( VALUE #( text = |{ gv_order }| ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    mv_p_fld = it_values[ name = 'P_FLD' ]-value.
    mv_p_rad1 = it_values[ name = 'P_RAD1' ]-value.
    mv_p_rad2 = it_values[ name = 'P_RAD2' ]-value.
    mv_p_req = it_values[ name = 'P_REQ' ]-value.
    mv_s_end = CORRESPONDING #( it_values[ name = 'S_END' ]-ranges ).
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~get_settings.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~end_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page_during_line_sel.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_line_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_user_command.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_pf.
    RETURN.
  ENDMETHOD.

  METHOD form_record.
    IF gv_order IS INITIAL.
      gv_order = iv_step.
    ELSE.
      gv_order = |{ gv_order }>{ iv_step }|.
    ENDIF.
  ENDMETHOD.

ENDCLASS.
