* Generated by open-abap-gui converter 0.1.0.
* Source object: ZGG_EX_016
* Source file: examples/zgg_ex_016.prog.abap
* Source SHA-256: 9adfba034a9c524a7998b5f9950f211a61c61b3d9e9cf976d7af2e5af5791246
* Target class: ZCL_GG_EX_016
* Manifest schema: 1
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_016 DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_transaction_v1.
    INTERFACES zif_gg_list_processing_v1.

  PRIVATE SECTION.
    DATA mv_p_name TYPE c LENGTH 20.

ENDCLASS.

CLASS zcl_gg_ex_016 IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZGG_EX_016' description = 'PARAMETERS attribute additions' program = 'ZGG_EX_016' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'PARAMETERS attribute additions' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    ro_list_processing = me.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    io_builder->add_parameter( VALUE #( name = 'P_NAME' text = 'Name' data_type = VALUE #( typ = 'C' length = 20 ) modif_id = 'ABC' memory_id = 'ZGG' search_help = 'ZGG_SH' value_help = abap_true obligatory = abap_true lower_case = abap_true ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    mv_p_name = ct_values[ name = 'P_NAME' ]-value.
    IF ct_values[ name = 'P_NAME' ]-value <> mv_p_name.
      ct_values[ name = 'P_NAME' ]-value = |{ mv_p_name }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    mv_p_name = ct_values[ name = 'P_NAME' ]-value.
    IF ct_values[ name = 'P_NAME' ]-value <> mv_p_name.
      ct_values[ name = 'P_NAME' ]-value = |{ mv_p_name }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    mv_p_name = ct_values[ name = 'P_NAME' ]-value.
    IF ct_values[ name = 'P_NAME' ]-value <> mv_p_name.
      ct_values[ name = 'P_NAME' ]-value = |{ mv_p_name }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    mv_p_name = ct_values[ name = 'P_NAME' ]-value.
    IF ct_values[ name = 'P_NAME' ]-value <> mv_p_name.
      ct_values[ name = 'P_NAME' ]-value = |{ mv_p_name }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    mv_p_name = ct_values[ name = 'P_NAME' ]-value.
    IF ct_values[ name = 'P_NAME' ]-value <> mv_p_name.
      ct_values[ name = 'P_NAME' ]-value = |{ mv_p_name }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    mv_p_name = ct_values[ name = 'P_NAME' ]-value.
    IF ct_values[ name = 'P_NAME' ]-value <> mv_p_name.
      ct_values[ name = 'P_NAME' ]-value = |{ mv_p_name }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    mv_p_name = ct_values[ name = 'P_NAME' ]-value.
    IF ct_values[ name = 'P_NAME' ]-value <> mv_p_name.
      ct_values[ name = 'P_NAME' ]-value = |{ mv_p_name }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    mv_p_name = it_values[ name = 'P_NAME' ]-value.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'PARAMETERS attribute additions' ).
    DATA(lo_writer) = io_session->get_list( )->get_writer( ).
    mv_p_name = it_values[ name = 'P_NAME' ]-value.
    lo_writer->write_field( VALUE #( text = |{ mv_p_name }| ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    mv_p_name = it_values[ name = 'P_NAME' ]-value.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~get_settings.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~end_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page_during_line_sel.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_line_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_user_command.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_pf.
    RETURN.
  ENDMETHOD.

ENDCLASS.
