* Generated by open-abap-gui converter.
* Source object: ZGG_EX_125
* Source file: examples/zgg_ex_125.prog.abap
* Source SHA-256: 356d6d40c2855bf970fbf2329e80724183c38629e5923d89df03e3f29792a82b
* Target class: ZCL_GG_EX_125_H1
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_125_h1 DEFINITION PUBLIC CREATE PUBLIC.

  PUBLIC SECTION.
    METHODS constructor
      IMPORTING
        io_owner   TYPE REF TO zcl_gg_ex_125
        io_session TYPE REF TO zif_gg_session_v1.
    DATA mo_owner TYPE REF TO zcl_gg_ex_125.
    DATA mo_session TYPE REF TO zif_gg_session_v1.
    CLASS-DATA go_owner TYPE REF TO zcl_gg_ex_125.
    CLASS-DATA go_session TYPE REF TO zif_gg_session_v1.
    CLASS-METHODS on_function FOR EVENT function_selected OF cl_gui_toolbar IMPORTING fcode.

ENDCLASS.

CLASS zcl_gg_ex_125_h1 IMPLEMENTATION.
  METHOD constructor.
    mo_owner = io_owner.
    mo_session = io_session.
  ENDMETHOD.

  METHOD on_function.
    go_owner->gv_state = |Toolbar function { fcode }|.
  ENDMETHOD.
ENDCLASS.
