* Generated by open-abap-gui converter.
* Source object: ZGG_EX_165
* Source file: examples/zgg_ex_165.prog.abap
* Source SHA-256: a6d89a024c77cec94fe65d0725811f9987f71d6f0c2f75e9a27cc270e13fd8e6
* Target class: ZCL_GG_EX_165
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_165 DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_transaction_v1.
    INTERFACES zif_gg_list_processing_v1.

  PRIVATE SECTION.
    DATA gv_line TYPE string.
    DATA mv_p_file TYPE string.

ENDCLASS.

CLASS zcl_gg_ex_165 IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZGG_EX_165' description = 'Read a text file with READ DATASET' program = 'ZGG_EX_165' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'Read a text file with READ DATASET' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    ro_list_processing = me.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    io_builder->add_parameter( VALUE #( name = 'P_FILE' text = 'File' data_type = VALUE #( typ = 'STRING' ) default = '/tmp/zgg_ex_165.txt' lower_case = abap_true ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    mv_p_file = ct_values[ name = 'P_FILE' ]-value.
    IF ct_values[ name = 'P_FILE' ]-value <> mv_p_file.
      ct_values[ name = 'P_FILE' ]-value = |{ mv_p_file }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    mv_p_file = ct_values[ name = 'P_FILE' ]-value.
    IF ct_values[ name = 'P_FILE' ]-value <> mv_p_file.
      ct_values[ name = 'P_FILE' ]-value = |{ mv_p_file }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    mv_p_file = ct_values[ name = 'P_FILE' ]-value.
    IF ct_values[ name = 'P_FILE' ]-value <> mv_p_file.
      ct_values[ name = 'P_FILE' ]-value = |{ mv_p_file }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    mv_p_file = ct_values[ name = 'P_FILE' ]-value.
    IF ct_values[ name = 'P_FILE' ]-value <> mv_p_file.
      ct_values[ name = 'P_FILE' ]-value = |{ mv_p_file }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    mv_p_file = ct_values[ name = 'P_FILE' ]-value.
    IF ct_values[ name = 'P_FILE' ]-value <> mv_p_file.
      ct_values[ name = 'P_FILE' ]-value = |{ mv_p_file }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    mv_p_file = ct_values[ name = 'P_FILE' ]-value.
    IF ct_values[ name = 'P_FILE' ]-value <> mv_p_file.
      ct_values[ name = 'P_FILE' ]-value = |{ mv_p_file }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    mv_p_file = ct_values[ name = 'P_FILE' ]-value.
    IF ct_values[ name = 'P_FILE' ]-value <> mv_p_file.
      ct_values[ name = 'P_FILE' ]-value = |{ mv_p_file }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    mv_p_file = it_values[ name = 'P_FILE' ]-value.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'Read a text file with READ DATASET' ).
    DATA(lo_writer) = io_session->get_list( )->get_writer( ).
    mv_p_file = it_values[ name = 'P_FILE' ]-value.
    OPEN DATASET mv_p_file FOR INPUT IN TEXT MODE ENCODING DEFAULT.
    IF sy-subrc <> 0.
      lo_writer->write_field( VALUE #( text = 'File could not be opened' placement = VALUE #( new_line = abap_true ) ) ).
      RETURN.
    ENDIF.
    DO.
      READ DATASET mv_p_file INTO gv_line.
      IF sy-subrc <> 0.
        EXIT.
      ENDIF.
      lo_writer->write_field( VALUE #( text = |{ gv_line }| placement = VALUE #( new_line = abap_true ) ) ).
    ENDDO.
    CLOSE DATASET mv_p_file.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    mv_p_file = it_values[ name = 'P_FILE' ]-value.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~get_settings.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~end_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page_during_line_sel.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_line_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_user_command.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_pf.
    RETURN.
  ENDMETHOD.

ENDCLASS.
