* Generated by open-abap-gui converter.
* Source object: ZGG_EX_149
* Source file: examples/zgg_ex_149.prog.abap
* Source SHA-256: 7b439efefb4090ee7ffeb19b309bf615c9d2caf4cf6fad2e4bc545e5eec64e6d
* Target class: ZCL_GG_EX_149
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_149 DEFINITION PUBLIC FINAL CREATE PUBLIC FRIENDS zcl_gg_ex_149_h1.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_screen_provider_v1.
    INTERFACES zif_gg_transaction_v1.
    INTERFACES zif_gg_resumable_v1.

  PRIVATE SECTION.
    TYPES: BEGIN OF ty_month, month TYPE c LENGTH 10, seatsmax TYPE i, seatsocc TYPE i, END OF ty_month.
    DATA gt_months TYPE STANDARD TABLE OF ty_month WITH DEFAULT KEY.
    DATA go_container TYPE REF TO cl_gui_custom_container.
    DATA go_chart TYPE REF TO cl_gui_chart_engine.
    DATA gv_chart_type TYPE string VALUE 'Lines'.
    DATA gv_ok_code TYPE sy-ucomm.
    DATA gv_state TYPE c LENGTH 60.
    METHODS output_modules
      IMPORTING
        is_context TYPE zif_gg_dynpro_types_v1=>ty_module_context
        io_session TYPE REF TO zif_gg_session_v1
      CHANGING
        ct_values  TYPE zif_gg_dynpro_types_v1=>ty_values
        ct_states  TYPE zif_gg_dynpro_types_v1=>ty_states.
    METHODS input_modules
      IMPORTING
        is_context TYPE zif_gg_dynpro_types_v1=>ty_module_context
        io_session TYPE REF TO zif_gg_session_v1
      CHANGING
        ct_values  TYPE zif_gg_dynpro_types_v1=>ty_values.

ENDCLASS.

CLASS zcl_gg_ex_149 IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZGG_EX_149' description = 'Chart engine' program = 'ZGG_EX_149' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'Chart engine' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'Chart engine' ).
    gt_months = VALUE #(
      ( month = 'June' seatsmax = 800 seatsocc = 610 )
      ( month = 'July' seatsmax = 800 seatsocc = 720 )
      ( month = 'August' seatsmax = 840 seatsocc = 690 )
      ( month = 'September' seatsmax = 840 seatsocc = 640 ) ).
    io_session->get_dialog( )->call_screen(
      is_call         = VALUE #( screen = '0100' )
      is_continuation = VALUE #( id = 'AFTER_0100' ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~get_initial_screen.
    rv_screen = '0100'.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~build_screens.
    io_builder->begin_screen( VALUE #( number = '0100' title = 'Chart engine' next_screen = '0100' ok_code = 'GV_OK_CODE' width = 800 height = 644 ) ).
    io_builder->add_custom_control( VALUE #( control = VALUE #( name = 'CC_MAIN' position = VALUE #( row = 10 column = 5 width = 780 height = 416 ) ) resizing = VALUE #( vertical = abap_true min_height = 130 horizontal = abap_true min_width = 200 ) ) ).
    io_builder->add_pushbutton( VALUE #( control = VALUE #( name = 'BTN_LINES' position = VALUE #( row = 452 column = 5 width = 100 height = 26 ) ) text = 'Lines' ucomm = 'LINES' ) ).
    io_builder->add_pushbutton( VALUE #( control = VALUE #( name = 'BTN_COLUMNS' position = VALUE #( row = 452 column = 125 width = 100 height = 26 ) ) text = 'Columns' ucomm = 'COLUMNS' ) ).
    io_builder->add_text( VALUE #( control = VALUE #( name = 'LBL_STATE' position = VALUE #( row = 504 column = 5 width = 60 height = 26 ) ) text = 'State' ) ).
    io_builder->add_output_field( VALUE #( control = VALUE #( name = 'GV_STATE' position = VALUE #( row = 504 column = 75 width = 600 height = 26 ) ) data_type = VALUE #( typ = 'C' length = 60 ) ) ).
    io_builder->end_screen( ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~build_flow_logic.
    io_builder->begin_screen( '0100' ).
    io_builder->begin_pbo( ).
    io_builder->add_module( VALUE #( name = 'STATUS_0100' ) ).
    io_builder->end_processing( ).
    io_builder->begin_pai( ).
    io_builder->add_module( VALUE #( name = 'USER_COMMAND_0100' on_input = abap_true ) ).
    io_builder->end_processing( ).
    io_builder->end_screen( ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~initialization.
    IF line_exists( ct_values[ name = 'GV_CHART_TYPE' ] ).
      ct_values[ name = 'GV_CHART_TYPE' ]-value = gv_chart_type.
    ELSE.
      INSERT VALUE #( name = 'GV_CHART_TYPE' value = gv_chart_type ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_STATE' ] ).
      ct_values[ name = 'GV_STATE' ]-value = CONV string( gv_state ).
    ELSE.
      INSERT VALUE #( name = 'GV_STATE' value = CONV string( gv_state ) ) INTO TABLE ct_values.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_output_module.
    DATA lx_unwind TYPE REF TO zcx_gg_control_flow.
    IF line_exists( ct_values[ name = 'GV_CHART_TYPE' ] ).
      gv_chart_type = CONV #( ct_values[ name = 'GV_CHART_TYPE' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      gv_ok_code = CONV #( ct_values[ name = 'GV_OK_CODE' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_STATE' ] ).
      gv_state = CONV #( ct_values[ name = 'GV_STATE' ]-value ).
    ENDIF.
    TRY.
        output_modules(
          EXPORTING
            is_context = is_context
            io_session = io_session
          CHANGING
            ct_values  = ct_values
            ct_states  = ct_states ).
      CATCH zcx_gg_control_flow INTO lx_unwind.
    ENDTRY.
    IF line_exists( ct_values[ name = 'GV_CHART_TYPE' ] ).
      ct_values[ name = 'GV_CHART_TYPE' ]-value = gv_chart_type.
    ELSE.
      INSERT VALUE #( name = 'GV_CHART_TYPE' value = gv_chart_type ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_STATE' ] ).
      ct_values[ name = 'GV_STATE' ]-value = CONV string( gv_state ).
    ELSE.
      INSERT VALUE #( name = 'GV_STATE' value = CONV string( gv_state ) ) INTO TABLE ct_values.
    ENDIF.
    IF lx_unwind IS BOUND.
      RAISE EXCEPTION lx_unwind.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_input_module.
    DATA lx_unwind TYPE REF TO zcx_gg_control_flow.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      gv_ok_code = CONV #( ct_values[ name = 'GV_OK_CODE' ]-value ).
    ENDIF.
    TRY.
        input_modules(
          EXPORTING
            is_context = is_context
            io_session = io_session
          CHANGING
            ct_values  = ct_values ).
      CATCH zcx_gg_control_flow INTO lx_unwind.
    ENDTRY.
    IF line_exists( ct_values[ name = 'GV_CHART_TYPE' ] ).
      ct_values[ name = 'GV_CHART_TYPE' ]-value = gv_chart_type.
    ELSE.
      INSERT VALUE #( name = 'GV_CHART_TYPE' value = gv_chart_type ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_STATE' ] ).
      ct_values[ name = 'GV_STATE' ]-value = CONV string( gv_state ).
    ELSE.
      INSERT VALUE #( name = 'GV_STATE' value = CONV string( gv_state ) ) INTO TABLE ct_values.
    ENDIF.
    IF lx_unwind IS BOUND.
      RAISE EXCEPTION lx_unwind.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_on_value_request.
    DATA ct_values TYPE zif_gg_dynpro_types_v1=>ty_values.
    ct_values = it_values.
    rt_values = io_session->get_compatibility( )->get_value_help_values( ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_on_help_request.
    DATA ct_values TYPE zif_gg_dynpro_types_v1=>ty_values.
    ct_values = it_values.
  ENDMETHOD.

  METHOD output_modules.
    CASE is_context-module.
      WHEN 'STATUS_0100'.
        IF go_container IS INITIAL.
          CREATE OBJECT go_container
            EXPORTING container_name = 'CC_MAIN'.
          CREATE OBJECT go_chart
            EXPORTING parent = go_container.
          go_chart->set_data( data = zcl_gg_ex_149_h1=>data_xml( io_owner = me io_session = io_session ) ).
        ENDIF.
        go_chart->set_customizing( data = |<SAPChartCustomizing version="1.1"><GlobalSettings><Defaults><ChartType>{ gv_chart_type }</ChartType></Defaults></GlobalSettings><Elements><ChartElements><Title><Caption>Seats per month</Caption></Title></ChartElements></Elements></SAPChartCustomizing>| ).
        go_chart->render( ).
        gv_state = |{ lines( gt_months ) } months, chart type { gv_chart_type }|.
      WHEN OTHERS.
        RETURN.
    ENDCASE.
  ENDMETHOD.

  METHOD input_modules.
    CASE is_context-module.
      WHEN 'USER_COMMAND_0100'.
        CASE gv_ok_code.
          WHEN 'LINES'.
            gv_chart_type = 'Lines'.
          WHEN 'COLUMNS'.
            gv_chart_type = 'Columns'.
        ENDCASE.
        CLEAR gv_ok_code.
      WHEN OTHERS.
        RETURN.
    ENDCASE.
  ENDMETHOD.

  METHOD zif_gg_resumable_v1~resume.
* Continuation states are explicit so unsupported suspension semantics remain visible.
    CASE is_resume-continuation-id.
      WHEN 'AFTER_0100'.
        RETURN.
      WHEN OTHERS.
        RETURN.
    ENDCASE.
  ENDMETHOD.

ENDCLASS.
