* Generated by open-abap-gui converter.
* Source object: ZGG_EX_153
* Source file: examples/zgg_ex_153.prog.abap
* Source SHA-256: f7d958e86708ba20b7edc2e69d87e0324de64db6f6761e73afcb55464348dfbf
* Target class: ZCL_GG_EX_153_H1
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_153_h1 DEFINITION PUBLIC CREATE PUBLIC.

  PUBLIC SECTION.
    METHODS constructor
      IMPORTING
        io_owner   TYPE REF TO zcl_gg_ex_153
        io_session TYPE REF TO zif_gg_session_v1.
    DATA mo_owner TYPE REF TO zcl_gg_ex_153.
    DATA mo_session TYPE REF TO zif_gg_session_v1.
    DATA node_key TYPE tv_nodekey.

ENDCLASS.

CLASS zcl_gg_ex_153_h1 IMPLEMENTATION.
  METHOD constructor.
    mo_owner = io_owner.
    mo_session = io_session.
  ENDMETHOD.
ENDCLASS.
