* Generated by open-abap-gui converter.
* Source object: ZGG_EX_087
* Source file: examples/zgg_ex_087.prog.abap
* Source SHA-256: 8b887ed8545ecb7abd99e67a8dc4b7331bef2a9bffb57202615bfd0d75101527
* Target class: ZCL_GG_EX_087
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_087 DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_transaction_v1.
    INTERFACES zif_gg_list_processing_v1.

ENDCLASS.

CLASS zcl_gg_ex_087 IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZGG_EX_087' description = 'Fragment-level colors and emphasis' program = 'ZGG_EX_087' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'Fragment-level colors and emphasis' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    ro_list_processing = me.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'Fragment-level colors and emphasis' ).
    DATA(lo_writer) = io_session->get_list( )->get_writer( ).
    lo_writer->set_format( VALUE #( color = zif_gg_list_processing_types_v1=>color_heading intensified = abap_true ) ).
    lo_writer->write_field( VALUE #( text = 'heading' format = VALUE #( quickinfo = 'Heading & <safe>' ) placement = VALUE #( new_line = abap_true ) ) ).
    lo_writer->set_format( VALUE #( color = zif_gg_list_processing_types_v1=>color_positive intensified = abap_false hotspot = abap_true ) ).
    lo_writer->write_field( VALUE #( text = 'positive' format = VALUE #( quickinfo = 'Positive' ) ) ).
    lo_writer->set_format( VALUE #( color = zif_gg_list_processing_types_v1=>color_negative inverse = abap_true hotspot = abap_false ) ).
    lo_writer->write_field( VALUE #( text = 'negative' format = VALUE #( quickinfo = 'Negative' ) ) ).
    lo_writer->reset_format( ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~get_settings.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~end_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page_during_line_sel.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_line_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_user_command.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_pf.
    RETURN.
  ENDMETHOD.

ENDCLASS.
