* Generated by open-abap-gui converter.
* Source object: ZGG_EX_150
* Source file: examples/zgg_ex_150.prog.abap
* Source SHA-256: eabaf413d9960d8ee20a0e195b55000c77c291d0f75b5e2469eabe5edcf0ea77
* Target class: ZCL_GG_EX_150
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_150 DEFINITION PUBLIC FINAL CREATE PUBLIC FRIENDS zcl_gg_ex_150_h1.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_screen_provider_v1.
    INTERFACES zif_gg_transaction_v1.
    INTERFACES zif_gg_resumable_v1.

  PRIVATE SECTION.
    TYPES: BEGIN OF ty_flight, carrid TYPE c LENGTH 3, connid TYPE n LENGTH 4, fldate TYPE d, seatsmax TYPE i, seatsocc TYPE i, END OF ty_flight.
    DATA gt_all TYPE STANDARD TABLE OF ty_flight WITH DEFAULT KEY.
    DATA gt_flights TYPE STANDARD TABLE OF ty_flight WITH DEFAULT KEY.
    DATA gt_fieldcat TYPE lvc_t_fcat.
    DATA go_container TYPE REF TO cl_gui_custom_container.
    DATA go_splitter TYPE REF TO cl_gui_splitter_container.
    DATA go_grid TYPE REF TO cl_gui_alv_grid.
    DATA go_chart TYPE REF TO cl_gui_chart_engine.
    DATA gv_ok_code TYPE sy-ucomm.
    DATA gv_state TYPE c LENGTH 60.
    DATA mv_p_carr TYPE c LENGTH 3.
    DATA mv_p_date TYPE d.
    METHODS output_modules
      IMPORTING
        is_context TYPE zif_gg_dynpro_types_v1=>ty_module_context
        io_session TYPE REF TO zif_gg_session_v1
      CHANGING
        ct_values  TYPE zif_gg_dynpro_types_v1=>ty_values
        ct_states  TYPE zif_gg_dynpro_types_v1=>ty_states.
    METHODS input_modules
      IMPORTING
        is_context TYPE zif_gg_dynpro_types_v1=>ty_module_context
        io_session TYPE REF TO zif_gg_session_v1
      CHANGING
        ct_values  TYPE zif_gg_dynpro_types_v1=>ty_values.

ENDCLASS.

CLASS zcl_gg_ex_150 IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZGG_EX_150' description = 'Analytics cockpit' program = 'ZGG_EX_150' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'Analytics cockpit' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    io_builder->add_parameter( VALUE #( name = 'P_CARR' text = 'Airline' data_type = VALUE #( typ = 'C' length = 3 ) default = 'LH' obligatory = abap_true ) ).
    io_builder->add_parameter( VALUE #( name = 'P_DATE' text = 'Flights from' data_type = VALUE #( typ = 'D' length = 8 ) default = '20260801' ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    mv_p_date = ct_values[ name = 'P_DATE' ]-value.
    IF ct_values[ name = 'P_CARR' ]-value <> mv_p_carr.
      ct_values[ name = 'P_CARR' ]-value = |{ mv_p_carr }|.
    ENDIF.
    IF ct_values[ name = 'P_DATE' ]-value <> mv_p_date.
      ct_values[ name = 'P_DATE' ]-value = |{ mv_p_date }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    mv_p_date = ct_values[ name = 'P_DATE' ]-value.
    IF ct_values[ name = 'P_CARR' ]-value <> mv_p_carr.
      ct_values[ name = 'P_CARR' ]-value = |{ mv_p_carr }|.
    ENDIF.
    IF ct_values[ name = 'P_DATE' ]-value <> mv_p_date.
      ct_values[ name = 'P_DATE' ]-value = |{ mv_p_date }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    mv_p_date = ct_values[ name = 'P_DATE' ]-value.
    IF ct_values[ name = 'P_CARR' ]-value <> mv_p_carr.
      ct_values[ name = 'P_CARR' ]-value = |{ mv_p_carr }|.
    ENDIF.
    IF ct_values[ name = 'P_DATE' ]-value <> mv_p_date.
      ct_values[ name = 'P_DATE' ]-value = |{ mv_p_date }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    mv_p_date = ct_values[ name = 'P_DATE' ]-value.
    IF ct_values[ name = 'P_CARR' ]-value <> mv_p_carr.
      ct_values[ name = 'P_CARR' ]-value = |{ mv_p_carr }|.
    ENDIF.
    IF ct_values[ name = 'P_DATE' ]-value <> mv_p_date.
      ct_values[ name = 'P_DATE' ]-value = |{ mv_p_date }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    mv_p_date = ct_values[ name = 'P_DATE' ]-value.
    IF ct_values[ name = 'P_CARR' ]-value <> mv_p_carr.
      ct_values[ name = 'P_CARR' ]-value = |{ mv_p_carr }|.
    ENDIF.
    IF ct_values[ name = 'P_DATE' ]-value <> mv_p_date.
      ct_values[ name = 'P_DATE' ]-value = |{ mv_p_date }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    mv_p_date = ct_values[ name = 'P_DATE' ]-value.
    IF ct_values[ name = 'P_CARR' ]-value <> mv_p_carr.
      ct_values[ name = 'P_CARR' ]-value = |{ mv_p_carr }|.
    ENDIF.
    IF ct_values[ name = 'P_DATE' ]-value <> mv_p_date.
      ct_values[ name = 'P_DATE' ]-value = |{ mv_p_date }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    mv_p_date = ct_values[ name = 'P_DATE' ]-value.
    IF ct_values[ name = 'P_CARR' ]-value <> mv_p_carr.
      ct_values[ name = 'P_CARR' ]-value = |{ mv_p_carr }|.
    ENDIF.
    IF ct_values[ name = 'P_DATE' ]-value <> mv_p_date.
      ct_values[ name = 'P_DATE' ]-value = |{ mv_p_date }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    mv_p_carr = it_values[ name = 'P_CARR' ]-value.
    mv_p_date = it_values[ name = 'P_DATE' ]-value.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'Analytics cockpit' ).
    mv_p_carr = it_values[ name = 'P_CARR' ]-value.
    mv_p_date = it_values[ name = 'P_DATE' ]-value.
    zcl_gg_ex_150_h1=>select_flights( io_owner   = me
                                      io_session = io_session ).
    IF gt_flights IS INITIAL.
      io_session->message( VALUE #( type = zif_gg_session_types_v1=>message_type_success text = 'No flights for this selection' display_like = zif_gg_session_types_v1=>message_type_error ) ).
      RETURN.
    ENDIF.
    io_session->get_dialog( )->call_screen(
      is_call         = VALUE #( screen = '0100' )
      is_continuation = VALUE #( id = 'AFTER_0100' ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    mv_p_carr = it_values[ name = 'P_CARR' ]-value.
    mv_p_date = it_values[ name = 'P_DATE' ]-value.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~get_initial_screen.
    rv_screen = '0100'.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~build_screens.
    io_builder->begin_screen( VALUE #( number = '0100' title = 'Analytics cockpit' next_screen = '0100' ok_code = 'GV_OK_CODE' width = 800 height = 644 ) ).
    io_builder->add_custom_control( VALUE #( control = VALUE #( name = 'CC_MAIN' position = VALUE #( row = 10 column = 5 width = 780 height = 416 ) ) resizing = VALUE #( vertical = abap_true min_height = 130 horizontal = abap_true min_width = 200 ) ) ).
    io_builder->add_text( VALUE #( control = VALUE #( name = 'LBL_STATE' position = VALUE #( row = 452 column = 5 width = 60 height = 26 ) ) text = 'State' ) ).
    io_builder->add_output_field( VALUE #( control = VALUE #( name = 'GV_STATE' position = VALUE #( row = 452 column = 75 width = 600 height = 26 ) ) data_type = VALUE #( typ = 'C' length = 60 ) ) ).
    io_builder->end_screen( ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~build_flow_logic.
    io_builder->begin_screen( '0100' ).
    io_builder->begin_pbo( ).
    io_builder->add_module( VALUE #( name = 'STATUS_0100' ) ).
    io_builder->end_processing( ).
    io_builder->begin_pai( ).
    io_builder->add_module( VALUE #( name = 'USER_COMMAND_0100' on_input = abap_true ) ).
    io_builder->end_processing( ).
    io_builder->end_screen( ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~initialization.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_STATE' ] ).
      ct_values[ name = 'GV_STATE' ]-value = CONV string( gv_state ).
    ELSE.
      INSERT VALUE #( name = 'GV_STATE' value = CONV string( gv_state ) ) INTO TABLE ct_values.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_output_module.
    DATA lx_unwind TYPE REF TO zcx_gg_control_flow.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      gv_ok_code = CONV #( ct_values[ name = 'GV_OK_CODE' ]-value ).
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_STATE' ] ).
      gv_state = CONV #( ct_values[ name = 'GV_STATE' ]-value ).
    ENDIF.
    TRY.
        output_modules(
          EXPORTING
            is_context = is_context
            io_session = io_session
          CHANGING
            ct_values  = ct_values
            ct_states  = ct_states ).
      CATCH zcx_gg_control_flow INTO lx_unwind.
    ENDTRY.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_STATE' ] ).
      ct_values[ name = 'GV_STATE' ]-value = CONV string( gv_state ).
    ELSE.
      INSERT VALUE #( name = 'GV_STATE' value = CONV string( gv_state ) ) INTO TABLE ct_values.
    ENDIF.
    IF lx_unwind IS BOUND.
      RAISE EXCEPTION lx_unwind.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_input_module.
    DATA lx_unwind TYPE REF TO zcx_gg_control_flow.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      gv_ok_code = CONV #( ct_values[ name = 'GV_OK_CODE' ]-value ).
    ENDIF.
    TRY.
        input_modules(
          EXPORTING
            is_context = is_context
            io_session = io_session
          CHANGING
            ct_values  = ct_values ).
      CATCH zcx_gg_control_flow INTO lx_unwind.
    ENDTRY.
    IF line_exists( ct_values[ name = 'GV_OK_CODE' ] ).
      ct_values[ name = 'GV_OK_CODE' ]-value = CONV string( gv_ok_code ).
    ELSE.
      INSERT VALUE #( name = 'GV_OK_CODE' value = CONV string( gv_ok_code ) ) INTO TABLE ct_values.
    ENDIF.
    IF line_exists( ct_values[ name = 'GV_STATE' ] ).
      ct_values[ name = 'GV_STATE' ]-value = CONV string( gv_state ).
    ELSE.
      INSERT VALUE #( name = 'GV_STATE' value = CONV string( gv_state ) ) INTO TABLE ct_values.
    ENDIF.
    IF lx_unwind IS BOUND.
      RAISE EXCEPTION lx_unwind.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_on_value_request.
    DATA ct_values TYPE zif_gg_dynpro_types_v1=>ty_values.
    ct_values = it_values.
    rt_values = io_session->get_compatibility( )->get_value_help_values( ).
  ENDMETHOD.

  METHOD zif_gg_screen_provider_v1~process_on_help_request.
    DATA ct_values TYPE zif_gg_dynpro_types_v1=>ty_values.
    ct_values = it_values.
  ENDMETHOD.

  METHOD output_modules.
    CASE is_context-module.
      WHEN 'STATUS_0100'.
        IF go_container IS INITIAL.
          zcl_gg_ex_150_h1=>create_controls( io_owner   = me
                                             io_session = io_session ).
          gv_state = |{ lines( gt_flights ) } flight(s) of { mv_p_carr } from { mv_p_date DATE = ISO }|.
        ENDIF.
      WHEN OTHERS.
        RETURN.
    ENDCASE.
  ENDMETHOD.

  METHOD input_modules.
    CASE is_context-module.
      WHEN 'USER_COMMAND_0100'.
        CLEAR gv_ok_code.
      WHEN OTHERS.
        RETURN.
    ENDCASE.
  ENDMETHOD.

  METHOD zif_gg_resumable_v1~resume.
* Continuation states are explicit so unsupported suspension semantics remain visible.
    CASE is_resume-continuation-id.
      WHEN 'AFTER_0100'.
        RETURN.
      WHEN OTHERS.
        RETURN.
    ENDCASE.
  ENDMETHOD.

ENDCLASS.
