* Generated by open-abap-gui converter.
* Source object: ZGG_EX_030
* Source file: examples/zgg_ex_030.prog.abap
* Source SHA-256: e02bc50991f3c6e885c23f52bb58657552cacb607fc23e26559c148b55cdf97e
* Target class: ZCL_GG_EX_030
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_030 DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_transaction_v1.

  PRIVATE SECTION.
    DATA mv_p_n TYPE i.

ENDCLASS.

CLASS zcl_gg_ex_030 IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZGG_EX_030' description = 'AT SELECTION-SCREEN' program = 'ZGG_EX_030' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'AT SELECTION-SCREEN' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    io_builder->add_parameter( VALUE #( name = 'P_N' text = 'Number' data_type = VALUE #( typ = 'I' ) ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    mv_p_n = ct_values[ name = 'P_N' ]-value.
    IF ct_values[ name = 'P_N' ]-value <> mv_p_n.
      ct_values[ name = 'P_N' ]-value = |{ mv_p_n }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    mv_p_n = ct_values[ name = 'P_N' ]-value.
    IF ct_values[ name = 'P_N' ]-value <> mv_p_n.
      ct_values[ name = 'P_N' ]-value = |{ mv_p_n }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    mv_p_n = ct_values[ name = 'P_N' ]-value.
    IF mv_p_n < 0.
      io_session->message( VALUE #( type = zif_gg_session_types_v1=>message_type_error text = 'must not be negative' ) ).
    ENDIF.
    IF ct_values[ name = 'P_N' ]-value <> mv_p_n.
      ct_values[ name = 'P_N' ]-value = |{ mv_p_n }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    mv_p_n = ct_values[ name = 'P_N' ]-value.
    IF ct_values[ name = 'P_N' ]-value <> mv_p_n.
      ct_values[ name = 'P_N' ]-value = |{ mv_p_n }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    mv_p_n = ct_values[ name = 'P_N' ]-value.
    IF ct_values[ name = 'P_N' ]-value <> mv_p_n.
      ct_values[ name = 'P_N' ]-value = |{ mv_p_n }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    mv_p_n = ct_values[ name = 'P_N' ]-value.
    IF ct_values[ name = 'P_N' ]-value <> mv_p_n.
      ct_values[ name = 'P_N' ]-value = |{ mv_p_n }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    mv_p_n = ct_values[ name = 'P_N' ]-value.
    IF ct_values[ name = 'P_N' ]-value <> mv_p_n.
      ct_values[ name = 'P_N' ]-value = |{ mv_p_n }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    mv_p_n = it_values[ name = 'P_N' ]-value.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'AT SELECTION-SCREEN' ).
    mv_p_n = it_values[ name = 'P_N' ]-value.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    mv_p_n = it_values[ name = 'P_N' ]-value.
  ENDMETHOD.

ENDCLASS.
