* Generated by open-abap-gui converter.
* Source object: ZGG_EX_082
* Source file: examples/zgg_ex_082.prog.abap
* Source SHA-256: b9d4fc0406d77707adc21207c924c38b6b9ed68768c0b24500f3bb7fcfaa0878
* Target class: ZCL_GG_EX_082
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_gg_ex_082 DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_transaction_v1.
    INTERFACES zif_gg_list_processing_v1.

  PRIVATE SECTION.
    DATA sscrfields TYPE sscrfields.
    DATA gt_contents TYPE STANDARD TABLE OF rsparams WITH DEFAULT KEY.
    DATA gt_text TYPE STANDARD TABLE OF varit WITH DEFAULT KEY.
    DATA gs_variant TYPE varid.
    DATA delete TYPE string.
    DATA load TYPE string.
    DATA save TYPE string.
    DATA mv_p_name TYPE c LENGTH 14.
    DATA mv_p_value TYPE c LENGTH 30.

ENDCLASS.

CLASS zcl_gg_ex_082 IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZGG_EX_082' description = 'Variant manager selection screen' program = 'ZGG_EX_082' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'Variant manager selection screen' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    ro_list_processing = me.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    io_builder->add_parameter( VALUE #( name = 'P_NAME' text = 'Variant name' data_type = VALUE #( typ = 'C' length = 14 ) obligatory = abap_true ) ).
    io_builder->add_parameter( VALUE #( name = 'P_VALUE' text = 'Variant value' data_type = VALUE #( typ = 'C' length = 30 ) ) ).
    io_builder->add_pushbutton( VALUE #( name = 'PB_VAR_SAVE' text = 'Save' position = 1 length = 12 ucomm = 'VAR_SAVE' ) ).
    io_builder->add_pushbutton( VALUE #( name = 'PB_VAR_LOAD' text = 'Load' position = 15 length = 12 ucomm = 'VAR_LOAD' ) ).
    io_builder->add_pushbutton( VALUE #( name = 'PB_VAR_DELETE' text = 'Delete' position = 29 length = 12 ucomm = 'VAR_DELETE' ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    mv_p_name = ct_values[ name = 'P_NAME' ]-value.
    mv_p_value = ct_values[ name = 'P_VALUE' ]-value.
    IF ct_values[ name = 'P_NAME' ]-value <> mv_p_name.
      ct_values[ name = 'P_NAME' ]-value = |{ mv_p_name }|.
    ENDIF.
    IF ct_values[ name = 'P_VALUE' ]-value <> mv_p_value.
      ct_values[ name = 'P_VALUE' ]-value = |{ mv_p_value }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    mv_p_name = ct_values[ name = 'P_NAME' ]-value.
    mv_p_value = ct_values[ name = 'P_VALUE' ]-value.
    IF ct_values[ name = 'P_NAME' ]-value <> mv_p_name.
      ct_values[ name = 'P_NAME' ]-value = |{ mv_p_name }|.
    ENDIF.
    IF ct_values[ name = 'P_VALUE' ]-value <> mv_p_value.
      ct_values[ name = 'P_VALUE' ]-value = |{ mv_p_value }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    mv_p_name = ct_values[ name = 'P_NAME' ]-value.
    mv_p_value = ct_values[ name = 'P_VALUE' ]-value.
    CASE iv_ucomm.
      WHEN 'VAR_SAVE'.
        io_session->get_compatibility( )->variant_refresh(
          EXPORTING
            is_request   = VALUE #( report = io_session->get_context( )-program-program )
          CHANGING
            ct_selection = gt_contents ).
        gs_variant-report = io_session->get_context( )-program-program.
        gs_variant-variant = mv_p_name.
        io_session->get_compatibility( )->variant_create(
          EXPORTING
            is_request  = VALUE #( report = io_session->get_context( )-program-program variant = mv_p_name )
          CHANGING
            ct_contents = gt_contents
            ct_text     = gt_text ).
        IF sy-subrc <> 0.
          io_session->get_compatibility( )->variant_change(
            EXPORTING
              is_request  = VALUE #( report = io_session->get_context( )-program-program variant = mv_p_name )
            CHANGING
              ct_contents = gt_contents
              ct_text     = gt_text ).
        ENDIF.
        io_session->message( VALUE #( type = zif_gg_session_types_v1=>message_type_success text = 'Variant saved' ) ).
      WHEN 'VAR_LOAD'.
        io_session->get_compatibility( )->variant_contents(
          EXPORTING
            is_request  = VALUE #( report = io_session->get_context( )-program-program variant = mv_p_name )
          CHANGING
            ct_contents = gt_contents ).
        IF sy-subrc <> 0.
          io_session->message( VALUE #( type = zif_gg_session_types_v1=>message_type_warning text = 'Variant not found' ) ).
        ELSE.
          LOOP AT gt_contents INTO DATA(ls_content) WHERE selname = 'P_VALUE'.
            mv_p_value = ls_content-low.
          ENDLOOP.
          io_session->message( VALUE #( type = zif_gg_session_types_v1=>message_type_success text = 'Variant loaded' ) ).
        ENDIF.
      WHEN 'VAR_DELETE'.
        io_session->get_compatibility( )->variant_delete( is_request = VALUE #( report = io_session->get_context( )-program-program variant = mv_p_name ) ).
        io_session->message( VALUE #( type = zif_gg_session_types_v1=>message_type_success text = 'Variant deleted' ) ).
    ENDCASE.
    IF ct_values[ name = 'P_NAME' ]-value <> mv_p_name.
      ct_values[ name = 'P_NAME' ]-value = |{ mv_p_name }|.
    ENDIF.
    IF ct_values[ name = 'P_VALUE' ]-value <> mv_p_value.
      ct_values[ name = 'P_VALUE' ]-value = |{ mv_p_value }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    mv_p_name = ct_values[ name = 'P_NAME' ]-value.
    mv_p_value = ct_values[ name = 'P_VALUE' ]-value.
    IF ct_values[ name = 'P_NAME' ]-value <> mv_p_name.
      ct_values[ name = 'P_NAME' ]-value = |{ mv_p_name }|.
    ENDIF.
    IF ct_values[ name = 'P_VALUE' ]-value <> mv_p_value.
      ct_values[ name = 'P_VALUE' ]-value = |{ mv_p_value }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    mv_p_name = ct_values[ name = 'P_NAME' ]-value.
    mv_p_value = ct_values[ name = 'P_VALUE' ]-value.
    IF ct_values[ name = 'P_NAME' ]-value <> mv_p_name.
      ct_values[ name = 'P_NAME' ]-value = |{ mv_p_name }|.
    ENDIF.
    IF ct_values[ name = 'P_VALUE' ]-value <> mv_p_value.
      ct_values[ name = 'P_VALUE' ]-value = |{ mv_p_value }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    mv_p_name = ct_values[ name = 'P_NAME' ]-value.
    mv_p_value = ct_values[ name = 'P_VALUE' ]-value.
    IF ct_values[ name = 'P_NAME' ]-value <> mv_p_name.
      ct_values[ name = 'P_NAME' ]-value = |{ mv_p_name }|.
    ENDIF.
    IF ct_values[ name = 'P_VALUE' ]-value <> mv_p_value.
      ct_values[ name = 'P_VALUE' ]-value = |{ mv_p_value }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    mv_p_name = ct_values[ name = 'P_NAME' ]-value.
    mv_p_value = ct_values[ name = 'P_VALUE' ]-value.
    IF ct_values[ name = 'P_NAME' ]-value <> mv_p_name.
      ct_values[ name = 'P_NAME' ]-value = |{ mv_p_name }|.
    ENDIF.
    IF ct_values[ name = 'P_VALUE' ]-value <> mv_p_value.
      ct_values[ name = 'P_VALUE' ]-value = |{ mv_p_value }|.
    ENDIF.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    mv_p_name = it_values[ name = 'P_NAME' ]-value.
    mv_p_value = it_values[ name = 'P_VALUE' ]-value.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'Variant manager selection screen' ).
    DATA(lo_writer) = io_session->get_list( )->get_writer( ).
    mv_p_name = it_values[ name = 'P_NAME' ]-value.
    mv_p_value = it_values[ name = 'P_VALUE' ]-value.
    lo_writer->write_field( VALUE #( text = |{ mv_p_name }={ mv_p_value }| ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    mv_p_name = it_values[ name = 'P_NAME' ]-value.
    mv_p_value = it_values[ name = 'P_VALUE' ]-value.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~get_settings.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~end_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page_during_line_sel.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_line_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_user_command.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_pf.
    RETURN.
  ENDMETHOD.

ENDCLASS.
