REPORT zgg_ex_033.

SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME.
PARAMETERS p_a TYPE c LENGTH 1.
PARAMETERS p_b TYPE c LENGTH 1.
SELECTION-SCREEN END OF BLOCK b1.

AT SELECTION-SCREEN ON BLOCK b1.
  IF p_a IS INITIAL AND p_b IS INITIAL.
    MESSAGE 'fill one of the two' TYPE 'E'.
  ENDIF.
