PROCESS BEFORE OUTPUT.
  MODULE status_0100.
  CALL SUBSCREEN sub_detail INCLUDING sy-repid gv_dynnr.

PROCESS AFTER INPUT.
  MODULE exit_0100 AT EXIT-COMMAND.
  CALL SUBSCREEN sub_detail.
  MODULE user_command_0100.
