REPORT zgg_ex_169.

SELECTION-SCREEN BEGIN OF SCREEN 101 AS SUBSCREEN.
PARAMETERS p_carr TYPE c LENGTH 3 DEFAULT 'LH'.
SELECTION-SCREEN END OF SCREEN 101.

SELECTION-SCREEN BEGIN OF SCREEN 102 AS SUBSCREEN.
PARAMETERS p_max TYPE i DEFAULT 10.
SELECTION-SCREEN END OF SCREEN 102.

SELECTION-SCREEN BEGIN OF SCREEN 103 AS SUBSCREEN.
PARAMETERS p_log AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN END OF SCREEN 103.

SELECTION-SCREEN BEGIN OF TABBED BLOCK g_tabs FOR 4 LINES.
SELECTION-SCREEN TAB (30) tab1 USER-COMMAND ucomm1 DEFAULT SCREEN 101.
SELECTION-SCREEN TAB (30) tab2 USER-COMMAND ucomm2 DEFAULT SCREEN 102.
SELECTION-SCREEN TAB (30) tab3 USER-COMMAND ucomm3 DEFAULT SCREEN 103.
SELECTION-SCREEN END OF BLOCK g_tabs.

INITIALIZATION.
  WRITE icon_position AS ICON TO tab1.
  tab1+5 = 'Connection'.
  CONCATENATE icon_settings 'Output' INTO tab2 SEPARATED BY space.
  tab3 = '@DR\QError log@Log'.

START-OF-SELECTION.
  WRITE: / 'Carrier:', p_carr.
  WRITE: / 'Maximum rows:', p_max.
  IF p_log = abap_true.
    WRITE / 'Log requested'.
  ENDIF.
