REPORT zgg_ex_026.

SELECTION-SCREEN BEGIN OF SCREEN 100 AS SUBSCREEN.
PARAMETERS p_name TYPE c LENGTH 20 DEFAULT 'Ada Lovelace'.
PARAMETERS p_city TYPE c LENGTH 20 DEFAULT 'London'.
SELECTION-SCREEN END OF SCREEN 100.

SELECTION-SCREEN BEGIN OF SCREEN 200 AS SUBSCREEN.
PARAMETERS p_count TYPE i DEFAULT 3.
PARAMETERS p_active AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN END OF SCREEN 200.

SELECTION-SCREEN BEGIN OF TABBED BLOCK tb FOR 10 LINES.
SELECTION-SCREEN TAB (20) tab1 USER-COMMAND ut1 DEFAULT SCREEN 100.
SELECTION-SCREEN TAB (20) tab2 USER-COMMAND ut2 DEFAULT SCREEN 200.
SELECTION-SCREEN END OF BLOCK tb.

INITIALIZATION.
  tab1 = 'General'.
  tab2 = 'Details'.

START-OF-SELECTION.
  WRITE: / 'Name:', p_name.
  WRITE: / 'City:', p_city.
  WRITE: / 'Count:', p_count.
  IF p_active = abap_true.
    WRITE / 'Active'.
  ENDIF.
