REPORT zgg_ex_160.

SELECTION-SCREEN BEGIN OF BLOCK block1 WITH FRAME TITLE TEXT-t01.
PARAMETERS p_maxrun TYPE i OBLIGATORY DEFAULT 20.
SELECTION-SCREEN END OF BLOCK block1.

SELECTION-SCREEN BEGIN OF BLOCK block2 WITH FRAME TITLE TEXT-t02.
PARAMETERS p_bkdef  TYPE i DEFAULT 4.
SELECTION-SCREEN END OF BLOCK block2.

START-OF-SELECTION.
  WRITE / p_maxrun.
  WRITE / p_bkdef.
