PROCESS BEFORE OUTPUT.
  MODULE status_0100.

PROCESS AFTER INPUT.
  MODULE exit_0100 AT EXIT-COMMAND.
  FIELD gv_carrid MODULE check_carrid.
  MODULE user_command_0100.

PROCESS ON VALUE-REQUEST.
  FIELD gv_carrid MODULE f4_carrid.
