REPORT zgg_ex_086.

DATA gv_row TYPE i.

START-OF-SELECTION.
  gv_row = 1.
  FORMAT COLOR COL_HEADING INTENSIFIED ON.
  WRITE / 'Row one'.
  FORMAT COLOR COL_KEY INTENSIFIED OFF.
  WRITE AT 16 'fragment A'.
  HIDE gv_row.
  gv_row = 2.
  FORMAT RESET.
  WRITE / 'Row two'.
  FORMAT COLOR COL_POSITIVE.
  WRITE AT 16 'fragment B'.
  HIDE gv_row.
  FORMAT RESET.

AT LINE-SELECTION.
  MODIFY LINE 1 LINE FORMAT COLOR COL_POSITIVE INTENSIFIED ON.
  MODIFY LINE 2 LINE FORMAT COLOR COL_NEGATIVE INVERSE.
