REPORT zgg_ex_070.

PARAMETERS p_all RADIOBUTTON GROUP g1 DEFAULT 'X'.
PARAMETERS p_one RADIOBUTTON GROUP g1.
PARAMETERS p_allv TYPE c LENGTH 20.
PARAMETERS p_onev TYPE c LENGTH 20.
PARAMETERS p_req TYPE c LENGTH 20 OBLIGATORY.

START-OF-SELECTION.
  IF p_one = 'X'.
    WRITE p_onev.
  ELSE.
    WRITE p_allv.
  ENDIF.
