REPORT zgg_ex_087.

START-OF-SELECTION.
  FORMAT COLOR COL_HEADING INTENSIFIED ON.
  WRITE / 'heading' QUICKINFO 'Heading & <safe>'.
  FORMAT COLOR COL_POSITIVE INTENSIFIED OFF HOTSPOT ON.
  WRITE 'positive' QUICKINFO 'Positive'.
  FORMAT COLOR COL_NEGATIVE HOTSPOT OFF INVERSE ON.
  WRITE 'negative' QUICKINFO 'Negative'.
  FORMAT RESET.
