REPORT zgg_ex_102.
PARAMETERS p_value TYPE c LENGTH 20.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR p_value.
  p_value = 'AA'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR p_value.
  MESSAGE 'Dynpro help' TYPE 'I'.
