REPORT zgg_ex_069.

PARAMETERS p_enable AS CHECKBOX DEFAULT 'X' USER-COMMAND enable.
PARAMETERS p_grp_a TYPE c LENGTH 20 MODIF ID grp.
PARAMETERS p_grp_b TYPE c LENGTH 20 MODIF ID grp.
PARAMETERS p_req TYPE c LENGTH 20 OBLIGATORY.

AT SELECTION-SCREEN OUTPUT.
  LOOP AT SCREEN.
    IF screen-group1 = 'GRP'.
      screen-input = COND #( WHEN p_enable = abap_true THEN 1 ELSE 0 ).
      MODIFY SCREEN.
    ENDIF.
  ENDLOOP.

START-OF-SELECTION.
  WRITE p_grp_a.
  WRITE / p_grp_b.
