PROCESS BEFORE OUTPUT.
  MODULE status_0100.

PROCESS AFTER INPUT.
  MODULE exit_0100 AT EXIT-COMMAND.

PROCESS ON VALUE-REQUEST.
  FIELD gv_carrid MODULE f4_carrid.

PROCESS ON HELP-REQUEST.
  FIELD gv_carrid MODULE f1_carrid.
