* Generated by open-abap-gui converter.
* Source object: ZEXAMPLE_TABS
* Source file: input/zexample_tabs.prog.abap
* Source SHA-256: 03576dea8dea1b81c864369de17a73d423964ea8de0c06b864d98198a5ff77b6
* Target class: ZCL_EXAMPLE_TABS
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_example_tabs DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_program_v1.
    INTERFACES zif_gg_list_processing_v1.

  PRIVATE SECTION.
    DATA tab1 TYPE string.
    DATA tab2 TYPE string.
    DATA mv_active_tab TYPE string.
    DATA mv_p_carr TYPE c LENGTH 3.
    DATA mv_p_rows TYPE i.
    METHODS form_init
      IMPORTING
        io_session TYPE REF TO zif_gg_session_v1.
    METHODS form_init_options
      IMPORTING
        io_session TYPE REF TO zif_gg_session_v1.

ENDCLASS.

CLASS zcl_example_tabs IMPLEMENTATION.

  METHOD zif_gg_program_v1~get_program.
    rs_program = VALUE #( program = 'ZEXAMPLE_TABS' description = 'Tab texts set at runtime' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'Tab texts set at runtime' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    ro_list_processing = me.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    io_builder->begin_tabbed_block( VALUE #( name = 'TABS' lines = 6 ) ).
    io_builder->add_tab( VALUE #( name = 'TAB1' text = 'TAB1' subscreen = '0101' ucomm = 'UCOMM1' ) ).
    io_builder->add_tab( VALUE #( name = 'TAB2' text = 'TAB2' subscreen = '0102' ucomm = 'UCOMM2' ) ).
    io_builder->end_tabbed_block( ).
    io_builder->begin_screen( VALUE #( number = '0101' as_subscreen = abap_true ) ).
    io_builder->add_parameter( VALUE #( name = 'P_CARR' text = 'Airline' data_type = VALUE #( typ = 'C' length = 3 ) ) ).
    io_builder->end_screen( ).
    io_builder->begin_screen( VALUE #( number = '0102' as_subscreen = abap_true ) ).
    io_builder->add_parameter( VALUE #( name = 'P_ROWS' text = 'Rows' data_type = VALUE #( typ = 'I' ) default = '10' ) ).
    io_builder->end_screen( ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    mv_p_rows = ct_values[ name = 'P_ROWS' ]-value.
    form_init( io_session = io_session ).
    IF ct_values[ name = 'P_CARR' ]-value <> mv_p_carr.
      ct_values[ name = 'P_CARR' ]-value = |{ mv_p_carr }|.
    ENDIF.
    IF ct_values[ name = 'P_ROWS' ]-value <> mv_p_rows.
      ct_values[ name = 'P_ROWS' ]-value = |{ mv_p_rows }|.
    ENDIF.
    ct_values[ name = 'TAB1' ]-value = tab1.
    ct_values[ name = 'TAB2' ]-value = tab2.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    mv_p_rows = ct_values[ name = 'P_ROWS' ]-value.
    IF mv_p_rows > 100.
      tab2 = 'Many rows'.
    ENDIF.
    IF ct_values[ name = 'P_CARR' ]-value <> mv_p_carr.
      ct_values[ name = 'P_CARR' ]-value = |{ mv_p_carr }|.
    ENDIF.
    IF ct_values[ name = 'P_ROWS' ]-value <> mv_p_rows.
      ct_values[ name = 'P_ROWS' ]-value = |{ mv_p_rows }|.
    ENDIF.
    ct_values[ name = 'TAB1' ]-value = tab1.
    ct_values[ name = 'TAB2' ]-value = tab2.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    IF iv_ucomm = 'UCOMM1' OR iv_ucomm = 'UCOMM2'.
      mv_active_tab = iv_ucomm.
    ENDIF.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    mv_p_rows = ct_values[ name = 'P_ROWS' ]-value.
    IF ct_values[ name = 'P_CARR' ]-value <> mv_p_carr.
      ct_values[ name = 'P_CARR' ]-value = |{ mv_p_carr }|.
    ENDIF.
    IF ct_values[ name = 'P_ROWS' ]-value <> mv_p_rows.
      ct_values[ name = 'P_ROWS' ]-value = |{ mv_p_rows }|.
    ENDIF.
    ct_values[ name = 'TAB1' ]-value = tab1.
    ct_values[ name = 'TAB2' ]-value = tab2.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    mv_p_rows = ct_values[ name = 'P_ROWS' ]-value.
    IF ct_values[ name = 'P_CARR' ]-value <> mv_p_carr.
      ct_values[ name = 'P_CARR' ]-value = |{ mv_p_carr }|.
    ENDIF.
    IF ct_values[ name = 'P_ROWS' ]-value <> mv_p_rows.
      ct_values[ name = 'P_ROWS' ]-value = |{ mv_p_rows }|.
    ENDIF.
    ct_values[ name = 'TAB1' ]-value = tab1.
    ct_values[ name = 'TAB2' ]-value = tab2.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    mv_p_rows = ct_values[ name = 'P_ROWS' ]-value.
    IF ct_values[ name = 'P_CARR' ]-value <> mv_p_carr.
      ct_values[ name = 'P_CARR' ]-value = |{ mv_p_carr }|.
    ENDIF.
    IF ct_values[ name = 'P_ROWS' ]-value <> mv_p_rows.
      ct_values[ name = 'P_ROWS' ]-value = |{ mv_p_rows }|.
    ENDIF.
    ct_values[ name = 'TAB1' ]-value = tab1.
    ct_values[ name = 'TAB2' ]-value = tab2.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    mv_p_rows = ct_values[ name = 'P_ROWS' ]-value.
    IF ct_values[ name = 'P_CARR' ]-value <> mv_p_carr.
      ct_values[ name = 'P_CARR' ]-value = |{ mv_p_carr }|.
    ENDIF.
    IF ct_values[ name = 'P_ROWS' ]-value <> mv_p_rows.
      ct_values[ name = 'P_ROWS' ]-value = |{ mv_p_rows }|.
    ENDIF.
    ct_values[ name = 'TAB1' ]-value = tab1.
    ct_values[ name = 'TAB2' ]-value = tab2.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    mv_p_rows = ct_values[ name = 'P_ROWS' ]-value.
    IF ct_values[ name = 'P_CARR' ]-value <> mv_p_carr.
      ct_values[ name = 'P_CARR' ]-value = |{ mv_p_carr }|.
    ENDIF.
    IF ct_values[ name = 'P_ROWS' ]-value <> mv_p_rows.
      ct_values[ name = 'P_ROWS' ]-value = |{ mv_p_rows }|.
    ENDIF.
    ct_values[ name = 'TAB1' ]-value = tab1.
    ct_values[ name = 'TAB2' ]-value = tab2.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    mv_p_carr = it_values[ name = 'P_CARR' ]-value.
    mv_p_rows = it_values[ name = 'P_ROWS' ]-value.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'Tab texts set at runtime' ).
    DATA(lo_writer) = io_session->get_list( )->get_writer( ).
    mv_p_carr = it_values[ name = 'P_CARR' ]-value.
    mv_p_rows = it_values[ name = 'P_ROWS' ]-value.
    lo_writer->write_field( VALUE #( text = lo_writer->format_value( iv_value = mv_p_carr ) placement = VALUE #( new_line = abap_true ) ) ).
    lo_writer->write_field( VALUE #( text = lo_writer->format_value( iv_value = mv_p_rows ) ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    mv_p_carr = it_values[ name = 'P_CARR' ]-value.
    mv_p_rows = it_values[ name = 'P_ROWS' ]-value.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~get_settings.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~end_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page_during_line_sel.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_line_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_user_command.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_pf.
    RETURN.
  ENDMETHOD.

  METHOD form_init.
    tab1 = 'Carrier'.
    form_init_options( io_session = io_session ).
  ENDMETHOD.

  METHOD form_init_options.
    tab2 = 'Options'.
  ENDMETHOD.

ENDCLASS.
