* Generated by open-abap-gui converter 0.1.0.
* Source object: ZEXAMPLE_FORMAT
* Source file: input/zexample_format.prog.abap
* Source SHA-256: e4fdc96c6876b90d28a3a18db8fa30e495ba8fe210711f7a1700093418660a5a
* Target class: ZCL_EXAMPLE_FORMAT
* Manifest schema: 1
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_example_format DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_transaction_v1.
    INTERFACES zif_gg_list_processing_v1.

ENDCLASS.

CLASS zcl_example_format IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZEXAMPLE_FORMAT' description = 'Converted executable report' program = 'ZEXAMPLE_FORMAT' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    ro_list_processing = me.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'ZCL_EXAMPLE_FORMAT' ).
    DATA(lo_writer) = io_session->get_list( )->get_writer( ).
    lo_writer->set_format( VALUE #( color = zif_gg_list_processing_types_v1=>color_heading intensified = abap_true ) ).
    lo_writer->write_field( VALUE #( text = 'Heading' placement = VALUE #( new_line = abap_true ) ) ).
    lo_writer->reset_format( ).
    lo_writer->uline( VALUE #( position = 1 length = 40 ) ).
    lo_writer->new_line( ).
    lo_writer->set_position( 5 ).
    lo_writer->skip( 2 ).
    lo_writer->write_field( VALUE #( text = 'Positive' format = VALUE #( color = zif_gg_list_processing_types_v1=>color_positive ) placement = VALUE #( new_line = abap_true ) ) ).
    lo_writer->write_field( VALUE #( text = 'Negative' format = VALUE #( color = zif_gg_list_processing_types_v1=>color_negative ) placement = VALUE #( position = 30 ) ) ).
    lo_writer->write_icon( VALUE #( name = 'ICON_OKAY' placement = VALUE #( position = 5 new_line = abap_true ) ) ).
    lo_writer->write_field( VALUE #( text = 'Done' ) ).
    lo_writer->new_line( ).
    lo_writer->write_field( VALUE #( text = 'Same line' format = VALUE #( inverse = abap_true ) ) ).
    lo_writer->new_page( VALUE #(  ) ).
    lo_writer->write_field( VALUE #( text = 'Second page' placement = VALUE #( new_line = abap_true ) ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~get_settings.
    rs_settings = VALUE #( line_size = 80 ).
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~end_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page_during_line_sel.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_line_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_user_command.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_pf.
    RETURN.
  ENDMETHOD.

ENDCLASS.
