REPORT zexample_tabs.

SELECTION-SCREEN BEGIN OF SCREEN 101 AS SUBSCREEN.
PARAMETERS p_carr TYPE c LENGTH 3.
SELECTION-SCREEN END OF SCREEN 101.

SELECTION-SCREEN BEGIN OF SCREEN 102 AS SUBSCREEN.
PARAMETERS p_rows TYPE i DEFAULT 10.
SELECTION-SCREEN END OF SCREEN 102.

SELECTION-SCREEN BEGIN OF TABBED BLOCK tabs FOR 6 LINES.
SELECTION-SCREEN TAB (40) tab1 USER-COMMAND ucomm1 DEFAULT SCREEN 101.
SELECTION-SCREEN TAB (40) tab2 USER-COMMAND ucomm2 DEFAULT SCREEN 102.
SELECTION-SCREEN END OF BLOCK tabs.

INITIALIZATION.
  PERFORM init.

AT SELECTION-SCREEN OUTPUT.
  IF p_rows > 100.
    tab2 = 'Many rows'.
  ENDIF.

START-OF-SELECTION.
  WRITE: / p_carr, p_rows.

FORM init.
  tab1 = 'Carrier'.
  PERFORM init_options.
ENDFORM.

FORM init_options.
  tab2 = 'Options'.
ENDFORM.
