* Generated by open-abap-gui converter 0.1.0.
* Source object: ZEXAMPLE_TEXTS
* Source file: input/zexample_texts.prog.abap
* Source SHA-256: 841c571e90d784b451edc9c3a1d55508414b4b6b931ab25e5f5f8f4ab05861fd
* Target class: ZCL_EXAMPLE_TEXTS
* Manifest schema: 1
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_example_texts DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_transaction_v1.
    INTERFACES zif_gg_list_processing_v1.

  PRIVATE SECTION.
    DATA selection TYPE string.
    DATA mv_p_days TYPE string.
    DATA mv_p_user TYPE string.

ENDCLASS.

CLASS zcl_example_texts IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZEXAMPLE_TEXTS' description = 'Activity report' program = 'ZEXAMPLE_TEXTS' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    io_session->get_list( )->set_title( 'Activity report' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    ro_list_processing = me.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    io_builder->begin_block( VALUE #( name = 'B1' title = 'Selection' with_frame = abap_true ) ).
    io_builder->add_parameter( VALUE #( name = 'P_USER' text = 'User name' data_type = VALUE #( typ = 'C' length = 12 ) ) ).
    io_builder->add_parameter( VALUE #( name = 'P_DAYS' text = 'Number of days' data_type = VALUE #( typ = 'I' ) default = CONV string( 7 ) ) ).
    io_builder->add_comment( VALUE #( name = 'C01' text = 'Leave the user empty to include everyone' position = 1 visible_length = 40 ) ).
    io_builder->end_block( ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    mv_p_days = ct_values[ name = 'P_DAYS' ]-value.
    mv_p_user = ct_values[ name = 'P_USER' ]-value.
    ct_values[ name = 'P_DAYS' ]-value = mv_p_days.
    ct_values[ name = 'P_USER' ]-value = mv_p_user.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    mv_p_days = ct_values[ name = 'P_DAYS' ]-value.
    mv_p_user = ct_values[ name = 'P_USER' ]-value.
    ct_values[ name = 'P_DAYS' ]-value = mv_p_days.
    ct_values[ name = 'P_USER' ]-value = mv_p_user.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    mv_p_days = ct_values[ name = 'P_DAYS' ]-value.
    mv_p_user = ct_values[ name = 'P_USER' ]-value.
    ct_values[ name = 'P_DAYS' ]-value = mv_p_days.
    ct_values[ name = 'P_USER' ]-value = mv_p_user.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    mv_p_days = ct_values[ name = 'P_DAYS' ]-value.
    mv_p_user = ct_values[ name = 'P_USER' ]-value.
    ct_values[ name = 'P_DAYS' ]-value = mv_p_days.
    ct_values[ name = 'P_USER' ]-value = mv_p_user.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    mv_p_days = ct_values[ name = 'P_DAYS' ]-value.
    mv_p_user = ct_values[ name = 'P_USER' ]-value.
    ct_values[ name = 'P_DAYS' ]-value = mv_p_days.
    ct_values[ name = 'P_USER' ]-value = mv_p_user.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    mv_p_days = ct_values[ name = 'P_DAYS' ]-value.
    mv_p_user = ct_values[ name = 'P_USER' ]-value.
    ct_values[ name = 'P_DAYS' ]-value = mv_p_days.
    ct_values[ name = 'P_USER' ]-value = mv_p_user.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    mv_p_days = ct_values[ name = 'P_DAYS' ]-value.
    mv_p_user = ct_values[ name = 'P_USER' ]-value.
    ct_values[ name = 'P_DAYS' ]-value = mv_p_days.
    ct_values[ name = 'P_USER' ]-value = mv_p_user.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    mv_p_days = it_values[ name = 'P_DAYS' ]-value.
    mv_p_user = it_values[ name = 'P_USER' ]-value.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'Activity report' ).
    DATA(lo_writer) = io_session->get_list( )->get_writer( ).
    mv_p_days = it_values[ name = 'P_DAYS' ]-value.
    mv_p_user = it_values[ name = 'P_USER' ]-value.
    lo_writer->write_field( VALUE #( text = |{ TEXT-001 }| placement = VALUE #( new_line = abap_true ) ) ).
    lo_writer->write_field( VALUE #( text = |{ mv_p_user }| ) ).
    lo_writer->write_field( VALUE #( text = |{ TEXT-002 }| placement = VALUE #( new_line = abap_true ) ) ).
    lo_writer->write_field( VALUE #( text = |{ mv_p_days }| ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    mv_p_days = it_values[ name = 'P_DAYS' ]-value.
    mv_p_user = it_values[ name = 'P_USER' ]-value.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~get_settings.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~end_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page_during_line_sel.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_line_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_user_command.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_pf.
    RETURN.
  ENDMETHOD.

ENDCLASS.
