* Generated by open-abap-gui converter 0.1.0.
* Source object: ZEXAMPLE_SQL
* Source file: input/zexample_sql.prog.abap
* Source SHA-256: ade096f767316a43aae98ed646923bdc2312c942f4c39022691e5e5a4ddcfb72
* Target class: ZCL_EXAMPLE_SQL
* Manifest schema: 1
* This file is generated migration output; it is safe to edit after review.
CLASS zcl_example_sql DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_gg_report_v1.
    INTERFACES zif_gg_transaction_v1.
    INTERFACES zif_gg_list_processing_v1.

  PRIVATE SECTION.
    TYPES: BEGIN OF ty_flight, carrid TYPE s_carr_id, connid TYPE s_conn_id, price TYPE s_price, END OF ty_flight.
    DATA gt_flights TYPE STANDARD TABLE OF ty_flight WITH EMPTY KEY.
    DATA gs_flight TYPE ty_flight.
    DATA gv_price TYPE s_price.
    DATA mv_p_carr TYPE string.

ENDCLASS.

CLASS zcl_example_sql IMPLEMENTATION.

  METHOD zif_gg_transaction_v1~get_transaction.
    rs_transaction = VALUE #( tcode = 'ZEXAMPLE_SQL' description = 'Converted executable report' ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~load_of_program.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_logical_database.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~get_list_processing.
    ro_list_processing = me.
  ENDMETHOD.

  METHOD zif_gg_report_v1~build_screen.
    io_builder->add_parameter( VALUE #( name = 'P_CARR' text = 'P_CARR' data_type = VALUE #( typ = 'S_CARR_ID' ) default = 'LH' ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~initialization.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    ct_values[ name = 'P_CARR' ]-value = mv_p_carr.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_output.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    ct_values[ name = 'P_CARR' ]-value = mv_p_carr.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    ct_values[ name = 'P_CARR' ]-value = mv_p_carr.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_field.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    ct_values[ name = 'P_CARR' ]-value = mv_p_carr.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_end_of.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    ct_values[ name = 'P_CARR' ]-value = mv_p_carr.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_block.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    ct_values[ name = 'P_CARR' ]-value = mv_p_carr.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_radio.
    mv_p_carr = ct_values[ name = 'P_CARR' ]-value.
    ct_values[ name = 'P_CARR' ]-value = mv_p_carr.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_value_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_help_req.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_selection_screen_on_exit.
    mv_p_carr = it_values[ name = 'P_CARR' ]-value.
  ENDMETHOD.

  METHOD zif_gg_report_v1~start_of_selection.
    io_session->get_list( )->set_title( 'ZCL_EXAMPLE_SQL' ).
    DATA(lo_writer) = io_session->get_list( )->get_writer( ).
    mv_p_carr = it_values[ name = 'P_CARR' ]-value.
    SELECT carrid connid price FROM sflight INTO TABLE gt_flights WHERE carrid = mv_p_carr.
    LOOP AT gt_flights INTO gs_flight.
      lo_writer->write_field( VALUE #( text = |{ gs_flight-carrid }| placement = VALUE #( new_line = abap_true ) ) ).
      lo_writer->write_field( VALUE #( text = |{ gs_flight-connid }| ) ).
      lo_writer->write_field( VALUE #( text = |{ gs_flight-price }| ) ).
    ENDLOOP.
    SELECT carrid connid price FROM sflight INTO gs_flight UP TO 3 ROWS.
      lo_writer->write_field( VALUE #( text = |{ gs_flight-connid }| placement = VALUE #( new_line = abap_true ) ) ).
    ENDSELECT.
    SELECT SINGLE price FROM sflight INTO gv_price WHERE carrid = mv_p_carr.
      lo_writer->write_field( VALUE #( text = 'First price' placement = VALUE #( new_line = abap_true ) ) ).
      lo_writer->write_field( VALUE #( text = |{ gv_price }| ) ).
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~at_get_late.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_report_v1~end_of_selection.
    mv_p_carr = it_values[ name = 'P_CARR' ]-value.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~get_settings.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~end_of_page.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~top_of_page_during_line_sel.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_line_selection.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_user_command.
    RETURN.
  ENDMETHOD.

  METHOD zif_gg_list_processing_v1~at_pf.
    RETURN.
  ENDMETHOD.

ENDCLASS.
